### ISSUE TITLE
Ruby 2.1.3 failed to build on OSX 10.9

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#32910]
With important problem being "**error: unable to open output file '/dev/fd/8': ''**"
With install flags **--with-gdbm, --with-tcltk, --with-libffi, --with-gmp, --with-doc**

```
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/ruby.rb
==> Upgrading 1 outdated package, with result:
ruby 2.1.3
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/libyaml.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/makedepend.rb
==> Upgrading ruby
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/gdbm.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/brew.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/libffi.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/ruby.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/readline.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/gdbm.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/gmp.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/libffi.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/libyaml.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/Homebrew/build.rb (Formulary::StandardLoader): loading /usr/local/Library/Formula/makedepend.rb
==> Downloading http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.3.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ruby-2.1.3.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/ruby/2.1.3 --enable-shared --disable-silent-rules --with-sitedir=/usr/local/lib/ruby/site_ruby --with-vendordir=/us
==> make
error: unable to open output file '/dev/fd/8': ''
1 error generated.
dtrace: failed to compile script probes.d: Preprocessor failed to process input program
make: *** [probes.h] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/Library/Homebrew/debrew.rb:10:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. shell
Choose an action: 3
/usr/local/Library/Homebrew/debrew.rb:10:in `raise'
/usr/local/Library/Homebrew/formula.rb:562:in `system'
/usr/local/Library/Formula/ruby.rb:67:in `install'
/usr/local/Library/Homebrew/debrew.rb:21:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:105:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:21:in `install'
/usr/local/Library/Homebrew/build.rb:137:in `block in install'
/usr/local/Library/Homebrew/formula.rb:268:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:600:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:66:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:63:in `unpack'
/usr/local/Library/Homebrew/resource.rb:56:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Library/Homebrew/formula.rb:598:in `stage'
/usr/local/Library/Homebrew/formula.rb:263:in `brew'
/usr/local/Library/Homebrew/build.rb:117:in `install'
/usr/local/Library/Homebrew/build.rb:186:in `<main>'
```

**Comment by sparr** [comment]
Commenting to mention this problem is still extant with 2.1.2 and 2.2.0

**Comment by smarek** [comment]
Yes, I've had to change the sources again on upgrade. Thanks for head up @sparr

**Comment by deviantintegral** [comment]
For some other work I had temporarily set the suid bit on /usr/sbin/dtrace. Removing that so the default permissions of -rwxr-xr-x fixed this for me. Another easy way to do the same thing would be to repair disk permissions from Disk Utility.

**Comment by smarek** [comment]
@deviantintegral thank you for hint, I have also SUID set on dtrace, however Disk Utility says `Warning: SUID file “usr/sbin/dtrace” has been modified and will not be repaired.`, which is really strange.

Could Homebrew somehow modify the file?

**Comment by smarek** [comment]
However I can confirm, this issue is cause by SUID bit on `/usr/sbin/dtrace`, removing it solves the problem.

```bash
sudo chmod -s /usr/sbin/dtrace
```

**Comment by jeffshantz** [comment]
@deviantintegral Thank you!  I, too, had set the suid bit temporarily on dtrace and was having issues compiling 2.1.x and 2.2.0 with rvm.  Works just fine now.

**Comment by bruno-** [comment]
Hi,
I also had the issue of installing ruby `2.2.x` (via ruby build) failing with the message `error: unable to open output file '/dev/fd/9'`. I was playing with `dtrace` recently and had the SUID bit set on.

This line by @smarek helped resolve the issue:

    sudo chmod -s /usr/sbin/dtrace

Thanks everyone!
