### ISSUE TITLE
duplicity: cannot find pyrax

### ISSUE THREAD

**Issue by tbfisher** [Homebrew/homebrew#34162]
1. install python via homebrew
2. install pyrax via pip
3. install duplicity via homebrew

duplicity returns error

    BackendException: This backend requires the pyrax library available from Rackspace.

install duplicity from source

    cd duplicity-0.6.25/
    python setup.py install --prefix=/usr/local

works

**Comment by tmikaeld** [comment]
Using brew 0.9.5, Python 2.7.10 (homebrew installed) and pip installed pyrax doesn't work.

Tested on freshly installed OS X 10.11.1 as well as 10.11.

**Comment by SchwarzM** [comment]
seem to have this issue also. :(

**Comment by tdsmith** [comment]
This is technically a re-appearance of this issue from a different cause, but let's handle it here.

This is one way to expose the error:

```
tim@rocketman:local (master)$ PYTHONPATH="/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.06/libexec/lib/python2.7/site-packages" /usr/bin/python -c "import pyrax"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages/pyrax/__init__.py", line 59, in <module>
    from novaclient import client as nc
  File "/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages/novaclient/client.py", line 35, in <module>
    from keystoneclient import adapter
  File "/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages/keystoneclient/adapter.py", line 15, in <module>
    from keystoneclient import utils
  File "/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages/keystoneclient/utils.py", line 25, in <module>
    from keystoneclient import exceptions
  File "/usr/local/Cellar/duplicity/0.7.06/libexec/vendor/lib/python2.7/site-packages/keystoneclient/exceptions.py", line 17, in <module>
    from keystoneauth1 import exceptions as _exc
ImportError: No module named keystoneauth1
```

The value of PYTHONPATH is taken from `cat $(which duplicity)`.
