### ISSUE TITLE
Brew fails to download and install repeatedly on 10.8.5

### ISSUE THREAD

**Issue by ttecon** [Homebrew/homebrew#35711]
All is updated. This is the error message when executing this alias `alias updatebrew='brew update; brew upgrade; brew cleanup; brew upgrade brew-cask; brew cask cleanup'`:

```
$ updatebrew
Already up-to-date.
==> Upgrading 5 outdated packages, with result:
automake 1.15, freetype 2.5.5, gettext 0.19.4, imagemagick 6.8.9-8, xz 5.2.0
==> Upgrading automake
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/automake-1.15.mountain_lion.bottle.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
Error: Failed to download resource "automake"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/automake-1.15.mountain_lion.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Installing automake dependency: xz
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/xz-5.2.0.mountain_lion.bottle.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
Error: Failed to download resource "xz"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/xz-5.2.0.mountain_lion.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading http://fossies.org/linux/misc/xz-5.2.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/xz-5.2.0.tar.gz
==> Patching
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.0
==> make install
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [aclocal.m4] Error 127

READ THIS: http://git.io/brew-troubleshooting


==> Upgrading freetype
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/freetype-2.5.5.mountain_lion.bottle.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
Error: Failed to download resource "freetype"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/freetype-2.5.5.mountain_lion.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://downloads.sf.net/project/freetype/freetype2/2.5.5/freetype-2.5.5.tar.bz2
Already downloaded: /Library/Caches/Homebrew/freetype-2.5.5.tar.bz2
==> Patching
==> ./configure --prefix=/usr/local/Cellar/freetype/2.5.5 --without-harfbuzz
==> make
  "_inflateReset", referenced from:
      _ft_gzip_file_io in ftgzip.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/private/tmp/freetype-5sfCJ3/freetype-2.5.5/objs/libfreetype.la] Error 1

READ THIS: http://git.io/brew-troubleshooting


==> Upgrading gettext
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/gettext-0.19.4.mountain_lion.bottle.tar.gz

curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 54
Error: Failed to download resource "gettext"
Download failed: https://downloads.sf.net/project/machomebrew/Bottles/gettext-0.19.4.mountain_lion.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Upgrading imagemagick
==> Installing dependencies for imagemagick: xz, freetype
Error: brew-cask 0.52.1 already installed
$HOME/.rvm/scripts/functions/rvmrc_project: line 275: rvm_saved_env: unbound variable
cannot resolve: '/usr/local/bin'
```

**Comment by DomT4** [comment]
Maintainers will need your ` brew doctor ` and ` brew config ` here as well. I'm curious as to why it has requested your password towards the end?

**Comment by ttecon** [comment]
Thanks DomT4. That message could have come from the later part of my original update alias. I now tried to update brew only and updated my comment above.

It's curious that `brew cask` just does not work for me anymore. I always get the last error with any `brew cask` command:

```
$HOME/.rvm/scripts/functions/rvmrc_project: line 275: rvm_saved_env: unbound variable
cannot resolve: '/usr/local/bin'
```

I'll post `brew config` and `brew doctor` results next.

**Comment by ttecon** [comment]
`brew config`:

```
brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 9cedafa1a55b55ca728b2ca082d8cada05a153a9
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.8.5-x86_64
Xcode: 5.1.1
CLT: 5.1.0.0.1.1396320587
Clang: 5.1 build 503
X11: 2.7.4 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: $HOME/anaconda/bin/python => /Users/nthakral/anaconda/bin/python2.7
Ruby: $HOME/.rvm/rubies/ruby-2.1.0/bin/ruby
```

`brew doctor`:
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  $HOME/anaconda/bin/curl-config
  $HOME/anaconda/bin/freetype-config
  $HOME/anaconda/bin/libdynd-config
  $HOME/anaconda/bin/libpng-config
  $HOME/anaconda/bin/libpng15-config
  $HOME/anaconda/bin/llvm-config
  $HOME/anaconda/bin/nc-config
  $HOME/anaconda/bin/python-config
  $HOME/anaconda/bin/python2-config
  $HOME/anaconda/bin/python2.7-config
  $HOME/anaconda/bin/xml2-config
  $HOME/anaconda/bin/xslt-config
  /usr/local/opengeo/bin/gdal-config
  /usr/local/opengeo/bin/geos-config
  /usr/local/opengeo/bin/xml2-config

Warning: Your XQuartz (2.7.4) is outdated
Please install XQuartz 2.7.7:
  https://xquartz.macosforge.org

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libcrypto.0.9.8.dylib
    /usr/local/lib/libcrypto.dylib
    /usr/local/lib/libklcskca.dylib
    /usr/local/lib/libklcsrt.dylib
    /usr/local/lib/libklcsstd.dylib
    /usr/local/lib/libklcstr.dylib
    /usr/local/lib/libklmspack.0.1.0.dylib
    /usr/local/lib/libklmspack.0.dylib
    /usr/local/lib/libklmspack.dylib
    /usr/local/lib/libssl.0.9.8.dylib
    /usr/local/lib/libssl.dylib
    /usr/local/lib/libz.1.2.5.dylib
    /usr/local/lib/libz.1.dylib
    /usr/local/lib/libz.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: You have a curlrc file
If you have trouble downloading packages with Homebrew, then maybe this
is the problem? If the following command doesn't work, then try removing
your curlrc:
  curl http://github.com
```

**Comment by mistydemeo** [comment]
I would need full logs to diagnose (please post the logs requested in the [troubleshooting guide](http://git.io/brew-troubleshooting)), but I strongly suspect the unbrewed zlib in `/usr/local/lib` is the source of the problem.

**Comment by DomT4** [comment]
Pretty sure the SSL errors will be the ` curlrc ` file. That's known to cause massive SSL connection problems. If you move it out of the way and try again, do updates work again?

Not sure about the linking problems. That could be the fault of some of those unexpected libs appearing in the ` $PATH ` and things trying to hook into those.

**Comment by ttecon** [comment]
I'm not sure what I tried, but updates work again for `brew update`. However, after updating, `brew cask` now has an issue with RVM. 

```
$HOME/.rvm/scripts/functions/rvmrc_project: line 324: rvm_saved_env: unbound variable
cannot resolve: '/usr/local/bin'
```

I tested this on 3 machines. Before the updates `brew cask` lists the available commands just fine. IMMEDIATELY after the updates, `brew cask` and any of its commands gave the above error or something similar. This happened even though RVM Ruby version varies from 1.9 to 2.1 to 2.2 on 3 of my machines.

Note that if I do `brew install ruby` then `brew cask` works again, but I do want to stick to using RVM. Trying to update to the newest RVM or newest Ruby does not help. 

Please suggest!

**Comment by mistydemeo** [comment]
Can you report the cask issues to the [cask project](https://github.com/caskroom/homebrew-cask), please? It's developed by different people. Thanks!

**Comment by DomT4** [comment]
If it's of any use to the Caskroom/Homebrew-Cask team, I'm not having the same issue as you with ` rbenv `, so it may be a ` RVM ` only issue.

**Comment by ttecon** [comment]
For what it's worth, I am not sure if it's purely a `brew cask` problem. At least on one of my machines, after reloading bash terminal right after doing a round of updates, this is what I see:

```
Error: SIGTERM
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:111:in `wait'
/usr/local/Library/Homebrew/utils.rb:111:in `system'
/usr/local/Library/Homebrew/utils.rb:134:in `safe_system'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `block in pull!'
/usr/local/Library/Homebrew/cmd/update.rb:165:in `block in reset_on_interrupt'
/usr/local/Library/Homebrew/utils.rb:240:in `ignore_interrupts'
/usr/local/Library/Homebrew/cmd/update.rb:165:in `reset_on_interrupt'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `pull!'
/usr/local/Library/Homebrew/cmd/update.rb:29:in `update'
/usr/local/Library/brew.rb:136:in `<main>'
```

**Comment by DomT4** [comment]
IMO, I'd try reporting this to the Cask, and if they have no answer as to why this is happening, it's probably worth kicking upstream to ` RVM ` themselves. If the problem goes away when you install Homebrew's Ruby, and I can't replicate the problem with ` rbenv `, the next likely bug point seems to be ` RVM `'s handling of something :confused:.

**Comment by ttecon** [comment]
Thanks DomT4. That's my guess too. I'll take your advice and move to `rbenv`. I don't use `RVM` enough to justify the investigation.
