### ISSUE TITLE
Error upgrading to Python 2.7.9: AttributeError: 'module' object has no attribute 'openssl_md_meth_names'

### ISSUE THREAD

**Issue by mdazmir** [Homebrew/homebrew#36346]
Hi! I've ran into error after running "brew upgrade python". Below are the outputs:

```
==> Installing python
==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/python-2.7.
######################################################################## 100.0%
==> Pouring python-2.7.9.yosemite.bottle.8.tar.gz
==> Caveats
Setuptools and Pip have been installed. To update them
  pip install --upgrade setuptools
  pip install --upgrade pip

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install 
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python`
==> Summary
🍺  /usr/local/Cellar/python/2.7.9: 4380 files, 69M
```

After that I ran "brew postinstall python" as instructed in the error above and still having the same error. Below are the outputs:

```
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install 
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
```
Below are the output for "brew config":

```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: d9cc3152f572300dea6ea350507a563083760ba0
Last commit: 12 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit penryn
OS X: 10.10.2-x86_64
Xcode: 6.1.1
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/John/.rvm/rubies/ruby-2.0.0-p451/bin/ruby
Java: N/A
```
Below are the output for "brew doctor":

```
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/librsync.1.0.2.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/librsync-config.h
    /usr/local/include/librsync.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/librsync.la

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/librsync.a
```
Below are the output for "ls -l /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib":

```
-r--r--r--  1 John  staff   1.9M Jan 29 08:11 /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
```

Any ideas how to fix this problem? Thanks in advance.

**Comment by tdsmith** [comment]
That symbol was added in 2.7.9 so it looks like an old _hashlib.so might be kicking around. Can I get you to run a few commands in python?

```python
import sys
print sys.path
import _hashlib
print _hashlib.__file__
import hashlib
print hashlib.__file__
```

**Comment by mdazmir** [comment]
Below are the output from your commands:

```
['/Users/John/Desktop', '/Library/Python/2.7/site-packages/APScheduler-2.0.3-py2.7.egg', '/Library/Python/2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages']
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.pyc
```

**Comment by tdsmith** [comment]
That'll do it. Do you know why it's not using the Homebrew Python search path? What is `otool -L $(which python)`? Do you have any PYTHON environment variables set? (`env | grep PYTHON` should tell you.)

**Comment by mdazmir** [comment]
Below are the outputs for "otool -L $(which python)"

```
/usr/local/bin/python:
	/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
There is no output for "env | grep PYTHON"

**Comment by tdsmith** [comment]
Can you open an interactive Python session and run

```python
import sys
print sys.executable, sys.prefix
print sys.path
```

and include the version header in the output you give me? I'm not sure that the Homebrew python is being invoked at all.

**Comment by mdazmir** [comment]
Below are the output from the commands you've requested:

```
Python 2.7.9 (default, Jan  7 2015, 11:49:12) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.executable, sys.prefix
/usr/local/opt/python/bin/python2.7 /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7
>>> print sys.path
['', '/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/colorama-0.2.4-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/argparse-1.2.1-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/List-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/APScheduler-2.0.3-py2.7.egg', '/Library/Python/2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/site-packages/colorama-0.2.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/argparse-1.2.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/List-1.3.0-py2.7.egg', '/usr/local/lib/python2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/usr/local/lib/python2.7/site-packages']
>>>
```

**Comment by tdsmith** [comment]
Did you invoke Python differently than you did the last time? The outputs are not consistent.

**Comment by mdazmir** [comment]
No, I did everything the same and I didn't do any modification to my system. I ran back all the command that you gave me from the beginning and the result are still the same as I posted here.

**Comment by tdsmith** [comment]
Well, to be specific (sorry), `sys.path` here: https://github.com/Homebrew/homebrew/issues/36346#issuecomment-71978784

is different from `sys.path` here: https://github.com/Homebrew/homebrew/issues/36346#issuecomment-72116157

Something must have changed.

**Comment by mdazmir** [comment]
Sorry, my mistake. From your https://github.com/Homebrew/homebrew/issues/36346#issuecomment-71977349 instructions, I've create a file called test.py and used the pathname ```#!/usr/bin/python``` instead of ```#!/usr/local/bin/python```

Below are the new output from my test.py using ```#!/usr/local/bin/python```:

```
['/Users/John/Desktop', '/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/colorama-0.2.4-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/argparse-1.2.1-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/List-1.3.0-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/APScheduler-2.0.3-py2.7.egg', '/Library/Python/2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/site-packages/colorama-0.2.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/argparse-1.2.1-py2.7.egg', '/usr/local/lib/python2.7/site-packages/List-1.3.0-py2.7.egg', '/usr/local/lib/python2.7/site-packages/wolframalpha-1.0.2-py2.7.egg', '/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages', '/usr/local/lib/python2.7/site-packages']
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    import hashlib
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
```

**Comment by tdsmith** [comment]
Do you still have Python 2.7.3 installed? The second entry in your sys.path is `'/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload'`, which probably contains an incompatible _hashlib.so if it still exists. You should remove whatever is adding this to your `sys.path`.

It's possible something you installed configured this for you. You may have a .pth file or a `sitecustomize` or `usercustomize` module that performs this.  `cat <(mdfind -0 -name customize py) <(mdfind -0 -name .pth) | xargs -0 grep lib-dynload` may tell you where this is happening.

If you don't need outdated Homebrew packages, `brew cleanup` will remove old versions of things, including Python 2.7.3.

**Comment by mdazmir** [comment]
I'm not sure which application modified my ```sys.path``` and I'm not well-versed enough in Python to troubleshoot this. My guess is that it could be some of the workflows I've installed for [Alfred v2](http://www.alfredapp.com), but I could be wrong.

Below are the outputs for ```cat <(mdfind -0 -name customize py) <(mdfind -0 -name .pth) | xargs -0 grep lib-dynload```

```
/usr/local/lib/python2.7/site-packages/easy-install.pth:/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
```
Below are the contents for ```/usr/local/lib/python2.7/site-packages/easy-install.pth```

```
import sys; sys.__plen = len(sys.path)
/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
./colorama-0.2.4-py2.7.egg
./argparse-1.2.1-py2.7.egg
./List-1.3.0-py2.7.egg
./wolframalpha-1.0.2-py2.7.egg
./pip-1.5.6-py2.7.egg
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
```
1. If I run ```brew cleanup``` will it solves my python upgrading problem?
2. Will it clean up all the mess inside my ```sys.path```?
3. Will the application that modified my ```sys.path``` cease to function?

**Comment by tdsmith** [comment]
> If I run brew cleanup will it solves my python upgrading problem?

Probably, yes.

> Will it clean up all the mess inside my sys.path?

No, but all you have to do is open the easy_install.pth file in a text
editor and delete the whole line containing lib-dynload.

> Will the application that modified my sys.path cease to function?

It shouldn't break since the right dynamic libs should already be in
sys.path.

**Comment by mdazmir** [comment]
I ran `brew cleanup` and after that `brew postinstall python`. Below are the output from `brew postinstall python` command:
```
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install 
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install 
```
It seems like `brew postinstall python` command cleaned sys.path file. Below are the contents of the file:
```
import sys; sys.__plen = len(sys.path)
./colorama-0.2.4-py2.7.egg
./argparse-1.2.1-py2.7.egg
./List-1.3.0-py2.7.egg
./wolframalpha-1.0.2-py2.7.egg
./pip-6.0.6-py2.7.egg
./setuptools-11.3.1-py2.7.egg
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
```
Thank you so much! I truly appreciate your guidance in solving this problem.

**Comment by tdsmith** [comment]
Great! Glad to hear it.
