### ISSUE TITLE
problem with brew install pig on mac

### ISSUE THREAD

**Issue by sherrylau** [Homebrew/homebrew#36603]
Hi

I have tried to use
brew install pig and export PIG_HOME. However, i got an error message of:
Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:249)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 4 more

I have also tried brew install https://gist.githubusercontent.com/akiatoji/6d67a7fa470e1218dc5b/raw/dff23e5668e0a3855e91a661296503dc6701266a/pig.rb
but it seems like it reference to 0.12.0 and the site is deprecated with the error message:
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "pig"
Download failed: http://mirror.nexcess.net/apache/pig/pig-0.12.0/pig-0.12.0-src.tar.gz

Please help me with this issue and thank you so much for your concern!

Sherry

**Comment by tdsmith** [comment]
When do you get the error message? Please read https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md

**Comment by jacknagel** [comment]
ping.

**Comment by sherrylau** [comment]
Hi Jack and Tim,
Sorry for the late response. I got that error message after running:
brew install https://gist.githubusercontent.com/akiatoji/6d67a7fa470e1218dc5b/raw/dff23e5668e0a3855e91a661296503dc6701266a/pig.rb

Sherry

**Comment by tdsmith** [comment]
Sorry, we can't help with formulas installed from a third-party source.

> I have tried to use
brew install pig and export PIG_HOME. However, i got an error message of:
Exception in thread "main" java.lang.NoClassDefFoundError

When do you receive this error message? How did you export PIG_HOME?

**Comment by johnpkennedy** [comment]
I see the same problem.

I did this:

```
brew install pig
```

then I exported PIG_HOME and source my rc file.

```
echo $PIG_HOME
/usr/local/Cellar/pig/0.14.0
```

```
pig
Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 4 more
```

**Comment by sherrylau** [comment]
Hi Tim,

I did the same thing as John and got the same error. 

Thanks!
Sherry

**Comment by erickhun** [comment]
Hi team, 
same errors as @johnpkennedy . Wonder if we would need to install joda time manually?

**Comment by adamv** [comment]
The formula is only installing the "core" jars, and these jars don't package their dependencies. The formula should almost certainly be installing `bin` and `lib`, and maybe some other subfolders too.

**Comment by adamv** [comment]
(As it stands, just installing the core jars makes the formula less useful than adding a pig dependency to a maven POM file.)

**Comment by adamv** [comment]
(It's possible that earlier versions of the core jars included dependencies; I only started using Pig myself recently.)

**Comment by adamv** [comment]
It works if I `prefix.install 'lib'`, but since we don't allow installing jars to lib, we'll need to make this do a `libexec` install like other Java software.

**Comment by sherrylau** [comment]
It works for me if i install pig-0.12.1 instead of pig-0.14.0

See here: https://sites.google.com/site/continuelearning/Home/hadoop-class/setting-up-apache-pig

**Comment by johnpkennedy** [comment]
I forked an existing homebrew formula gist for pig-0.12.0 and updated it for pig-0.12.1. It's here: https://gist.github.com/johnpkennedy/bde22d874a27eedbcda6

Use it like this:
```
brew install https://gist.githubusercontent.com/johnpkennedy/bde22d874a27eedbcda6/raw/a3c1ec504c687081201aa01515d6ff5c468a015b/pig.rb
```
