### ISSUE TITLE
googlecl crashes

### ISSUE THREAD

**Issue by simonweil** [Homebrew/homebrew#36992]
```bash
$ google help docs
Traceback (most recent call last):
  File "/usr/local/Cellar/googlecl/0.9.14/libexec/bin/google", line 991, in <module>
    main()
  File "/usr/local/Cellar/googlecl/0.9.14/libexec/bin/google", line 977, in main
    run_once(options, args)
  File "/usr/local/Cellar/googlecl/0.9.14/libexec/bin/google", line 651, in run_once
    options.config)
  File "/usr/local/Cellar/googlecl/0.9.14/libexec/bin/google", line 430, in import_service
    service_module = import_at_runtime('googlecl.' + service + '.service')
  File "/usr/local/Cellar/googlecl/0.9.14/libexec/bin/google", line 388, in import_at_runtime
    return __import__(module, globals(), fromlist=['0'])
  File "/usr/local/Cellar/googlecl/0.9.14/lib/python2.7/site-packages/googlecl/docs/service.py", line 32, in <module>
    import gdata.docs.service
ImportError: No module named gdata.docs.service
```

**Comment by jacknagel** [comment]
I can reproduce this, probably this formula is missing some python module resources.

**Comment by simonweil** [comment]
Thank you!
