### ISSUE TITLE
Syntax error in Formula/wget.rb

### ISSUE THREAD

**Issue by williamsmj** [Homebrew/homebrew#37114]
I just ran `brew update` and now both `brew upgrade` and `brew outdated` result in the following error. Any ideas?

```
$ brew upgrade
Error: /usr/local/Library/Formula/wget.rb:55: syntax error, unexpected end-of-input, expecting keyword_end
Please report this bug:
    http://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:519:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:517:in `map'
/usr/local/Library/Homebrew/formula.rb:517:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:9:in `upgrade'
/usr/local/Library/brew.rb:135:in `<main>'
```
Here's my config
```
$ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 1c79178d2151e7ae57c7c046cce3f34e59d38bf3
Last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.2-x86_64
Xcode: N/A
CLT: 6.1.1.0.1.1416017670
Clang: 6.0 build 600
X11: 2.7.6 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /Users/mike/.virtualenvs/ds/bin/python => /Users/mike/.virtualenvs/ds/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_31
```
No complaints from `brew doctor` except that I'm running XQuartz 2.7.6 rather than 2.7.7.

**Comment by mikemcquaid** [comment]
`brew update` again and it'll be fixed. Sorry!

**Comment by williamsmj** [comment]
Whoa. You're right. That was quick! Thanks!
