### ISSUE TITLE
All calls to the brew command seg fault on 10.10.3

### ISSUE THREAD

**Issue by joshourisman** [Homebrew/homebrew#37598]
The title pretty much explains it all. I cannot use the brew command at all, everything results in a segfault. I attempted removing and re-installing homebrew, and I have the same problem after doing so. I cannot follow the normal bug reporting process, because all the commands fail, as demonstrated below. I am running Command Line Tools version 6.2, which was just installed today. This problem existed before I ran that update, which is why I checked to see if there was an update in the first place and then installed it.

```
~ » brew doctor                                                                                                                                                                                                 ~  
[1]    19177 segmentation fault  brew doctor
~ » brew --config                                                                                                                                                                                          ~ 139 ↵ 
[1]    19185 segmentation fault  brew --config
~ » brew update                                                                                                                                                                                            ~ 139 ↵ 
[1]    19193 segmentation fault  brew update
~ » brew help                                                                                                                                                                                              ~ 139 ↵ 
[1]    19204 segmentation fault  brew help
~ » brew gist-logs                                                                                                                                                                                         ~ 139 ↵ 
[1]    19275 segmentation fault  brew gist-logs
~ » brew gist-logs memcached                                                                                                                                                                               ~ 139 ↵ 
[1]    19290 segmentation fault  brew gist-logs memcached
~ » 
```

**Comment by mikemcquaid** [comment]
Try running `ruby -e 'puts :hello'` and `cd /usr/local; git status`

**Comment by joshourisman** [comment]
They all work fine. While attempting to debug and fix before, I was able to run the standard install script (`ruby -e "$(curl …)"`).

```
~ » ruby -e 'puts :hello'                                                                                                                                                                                       ~  
hello
~ » cd /usr/local; git status                                                                                                                                                                                   ~  
On branch master
nothing to commit, working directory clean
```

**Comment by mikemcquaid** [comment]
Try `cd /usr/local; git fetch; git reset --hard origin/master` and `/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -e 'puts :hello'`

**Comment by joshourisman** [comment]
This also works as expected. There were no differences between what my local git state was and origin/master (as I'd deleted my local git repo and re-installed just a few minutes ago).

```
~ » cd /usr/local                                                                                                                                                                                               ~  
local :: (±master) » git fetch                                                                                                                                                                         /usr/local  
remote: Counting objects: 361, done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 361 (delta 141), reused 361 (delta 141), pack-reused 0
Receiving objects: 100% (361/361), 106.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (141/141), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      gh-pages   -> origin/gh-pages
 * [new branch]      go         -> origin/go
local :: (±master) » git reset --hard origin/master                                                                                                                                                    /usr/local  
HEAD is now at 4b1a2b7 google-sql-tool: use https, modernize
local :: (±master) » /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby -e 'puts :hello'                                                                                          /usr/local  
hello
```

**Comment by mikemcquaid** [comment]
Can you try and run `/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby /usr/local/Library/brew.rb`?

**Comment by joshourisman** [comment]
Ah, now we're getting somewhere! My ruby, for the record, is: ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14].

```
~ » /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby /usr/local/Library/brew.rb                                                                                                          ~  
/usr/local/Library/Homebrew/global.rb:52:in `initialize': no implicit conversion of nil into String (TypeError)
        from /usr/local/Library/Homebrew/global.rb:52:in `new'
        from /usr/local/Library/Homebrew/global.rb:52:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by adamv** [comment]
https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/global.rb#L52

**Comment by mikemcquaid** [comment]
Right, now try and add a `set -x` to the top of `/usr/local/bin/brew` and then run any `brew` command, thanks!

**Comment by joshourisman** [comment]
Tried a couple different commands, they all result in this:

```
~ » brew                                                                                                                                                                                                        ~  
++ chdir /usr/local/bin
++ cd /usr/local/bin
++ pwd -P
+ BREW_FILE_DIRECTORY=/usr/local/bin
+ export HOMEBREW_BREW_FILE=/usr/local/bin/brew
+ HOMEBREW_BREW_FILE=/usr/local/bin/brew
++ readlink /usr/local/bin/brew
+ BREW_SYMLINK=
+ '[' -n '' ']'
[1]    23779 segmentation fault  brew
```

My /usr/local/bin/brew file now looks like this:
```
#!/bin/sh

set -x

chdir () {
  cd "$@" >/dev/null
}

BREW_FILE_DIRECTORY=$(chdir "${0%/*}" && pwd -P)
export HOMEBREW_BREW_FILE="$BREW_FILE_DIRECTORY/${0##*/}"

BREW_SYMLINK=$(readlink "$0")
if [ -n "$BREW_SYMLINK" ]
then
    BREW_SYMLINK_DIRECTORY=$(dirname "$BREW_SYMLINK")
    BREW_FILE_DIRECTORY=$(chdir "$BREW_FILE_DIRECTORY" &&
                          chdir "$BREW_SYMLINK_DIRECTORY" && pwd -P)
fi

BREW_LIBRARY_DIRECTORY=$(chdir "$BREW_FILE_DIRECTORY"/../Library && pwd -P)

# Users may have these set, pointing the system Ruby
# at non-system gem paths
unset GEM_HOME
unset GEM_PATH

BREW_SYSTEM=$(uname -s | tr "[:upper:]" "[:lower:]")
if [ "$BREW_SYSTEM" = "darwin" ]
then
    exec "$BREW_LIBRARY_DIRECTORY/brew.rb" "$@"
else
    exec ruby -W0 "$BREW_LIBRARY_DIRECTORY/brew.rb" "$@"
fi
```

**Comment by mikemcquaid** [comment]
Try and run `/usr/bin/readlink /usr/local/bin/brew` and `/usr/bin/dirname /usr/local/bin/brew`

**Comment by joshourisman** [comment]
Here's what I get:

```
~ » /usr/bin/readlink /usr/local/bin/brew                                                                                                                                                                       ~  
~ » /usr/bin/dirname /usr/local/bin/brew                                                                                                                                                                     ~ 1 ↵ 
/usr/local/bin
```

**Comment by mikemcquaid** [comment]
Try the same thing without the `/usr/bin`s. Trying to work out what's segfaulting, here.

**Comment by joshourisman** [comment]
Still seems to work:

```
~ » readlink /usr/local/bin/brew                                                                                                                                                                           ~ 139 ↵ 
~ » dirname /usr/local/bin/brew                                                                                                                                                                              ~ 1 ↵ 
/usr/local/bin
```

**Comment by mikemcquaid** [comment]
Hmm. Try `pwd -P`?

**Comment by joshourisman** [comment]
Works fine:

```
~ » pwd -P                                                                                                                                                                                                      ~  
/Users/josho
~ » cd /usr/local                                                                                                                                                                                               ~  
local :: (±master⚡) » pwd -P                                                                                                                                                                           /usr/local  
/usr/local
```

**Comment by mikemcquaid** [comment]
Hmm. Will need to wait and see if any other @Homebrew/owners have ideas.

**Comment by DomT4** [comment]
I get the same error message from:

```
/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby /usr/local/Library/brew.rb
/usr/local/Library/Homebrew/global.rb:52:in `initialize': no implicit conversion of nil into String (TypeError)
	from /usr/local/Library/Homebrew/global.rb:52:in `new'
	from /usr/local/Library/Homebrew/global.rb:52:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

But no other brew issues though, at all. No segfaults. Nothing broken, etc.

**Comment by jacknagel** [comment]
When did this start happening, and what on your system has changed since then (I know this sounds obvious, but I have to ask...)? Try running it in a clean environment (default shell, no shell config files and whatnot). Perhaps as a different user in order to fully isolate the test.

**Comment by joshourisman** [comment]
Ok, strangest thing. I just got into work, plugged in my laptop, and, out of habit, ran `brew update`, and it worked. Everything appears to be fine now. Between when this was failing yesterday and now, I have not changed a thing. I wasn't even coding yesterday, just in meetings, so I didn't do anything that could possibly have an effect. The App Store also doesn't show that anything happened to auto-update (which was my first guess for both it randomly stopping working and now randomly starting working again). My computer hasn't even been restarted, it was just asleep overnight.

I… don't even know.

**Comment by mikemcquaid** [comment]
Heh, computers.
