### ISSUE TITLE
invalid attribute: version (nil) on brew upgrade or brew doctor

### ISSUE THREAD

**Issue by vendion** [Homebrew/homebrew#37797]
When trying to perform a brew upgrade or a brew doctor I get the following error:

```
╭─vendion@Oden.local ~
╰─➤  brew update
╭─vendion@Oden.local ~
╰─➤  brew update
Updated Homebrew from 7660d0b8 to 43195c23.
==> Updated Formulae
protobuf
╭─vendion@Oden.local ~
╰─➤  brew upgrade
Error: invalid attribute: version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:129:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:96:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:519:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:517:in `map'
/usr/local/Library/Homebrew/formula.rb:517:in `installed'
/usr/local/Library/Homebrew/cmd/upgrade.rb:9:in `upgrade'
/usr/local/Library/brew.rb:135:in `<main>'
╭─vendion@Oden.local ~
╰─➤  brew doctor                                                                                                                                                 1 ↵
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libusb-1.0.0.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/node/ares.h
    /usr/local/include/node/ares_version.h
    /usr/local/include/node/nameser.h
    /usr/local/include/node/node.h
    /usr/local/include/node/node_buffer.h
    /usr/local/include/node/node_internals.h
    /usr/local/include/node/node_object_wrap.h
    /usr/local/include/node/node_version.h
    /usr/local/include/node/openssl/opensslconf.h
    /usr/local/include/node/uv-private/ngx-queue.h
    /usr/local/include/node/uv-private/stdint-msvc2008.h
    /usr/local/include/node/uv-private/tree.h
    /usr/local/include/node/uv-private/uv-bsd.h
    /usr/local/include/node/uv-private/uv-darwin.h
    /usr/local/include/node/uv-private/uv-linux.h
    /usr/local/include/node/uv-private/uv-sunos.h
    /usr/local/include/node/uv-private/uv-unix.h
    /usr/local/include/node/uv-private/uv-win.h
    /usr/local/include/node/uv.h
    /usr/local/include/node/v8-debug.h
    /usr/local/include/node/v8-preparser.h
    /usr/local/include/node/v8-profiler.h
    /usr/local/include/node/v8-testing.h
    /usr/local/include/node/v8.h
    /usr/local/include/node/v8stdint.h
    /usr/local/include/node/zconf.h
    /usr/local/include/node/zlib.h
Error: invalid attribute: version (nil)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:129:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:96:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:71:in `new'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:519:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:517:in `map'
/usr/local/Library/Homebrew/formula.rb:517:in `installed'
/usr/local/Library/Homebrew/cmd/doctor.rb:977:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `doctor'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by mikemcquaid** [comment]
Please run `brew readall` and `brew list` and paste your output here. Thanks!

**Comment by vendion** [comment]
Here is the output of ```brew readall```

```
Error: problem in /usr/local/Library/Formula/extended-status-nginx-module.rb
invalid attribute: version (nil)
```

Here is the output of ```brew list```

```
accept-language-nginx-module    fancyindex-nginx-module         icu4c                           ncmpcpp                         sdl
ack                             feh                             id3lib                          nettle                          sdl2
android-sdk                     ffmpeg                          imlib2                          nginx-full                      sdl2_image
apple-gcc42                     ffmpeg2theora                   inkscape                        openssl                         sdl_image
archey                          fftw                            irssi                           opus                            sl
aria2                           flac                            isl                           opus-tools                      sntop
asciidoc                        fluid-synth                     jpeg                            opusfile                        source-highlight
aspell                          fontconfig                      lame                            ossp-uuid                       speedtest_cli
atk                             fping                           lastpass-cli                    p11-kit                         speex
atkmm                           freetype                        libao                           pango                           sqlite
atool                           gcc                             libcaca                         pangomm                         stow
auth-digest-nginx-module        gdbm    libevent                        par2                            taglib
auto-keepalive-nginx-module     gdk-pixbuf                      libexif                         pcre                            texi2html
autoconf                        gettext                         libffi                          pharcc                          theora
automake                        gh                              libid3tag                       php-session-nginx-module        tig
bazaar                          ghc                             libmpc                          php55                           tmux
bdw-gc                          gist                            libmpdclient                    php55-apcu                      tmux-mem-cpu-load
boost       git                             libogg                          php55-intl                      toilet
boot2docker                     git-cal                         libpng                          php55-pdo-pgsql                 tree
cache-purge-nginx-module        git-flow                        libsamplerate                   php55-xdebug                    two-lame
cairo                           glew                            libshout                        php55-xhprof                    unixodbc
cairomm                         glib                            libsigc++                       phpmd                           upload-nginx-module
cd-discid                       glibmm                          libtasn1                        pinentry     upload-progress-nginx-module
cloog                           glm                             libtiff                         pixman                          vim
cmake                           gmp                             libtool                         pkg-config                      vimpager
coreutils                       gnu-getopt                      libvo-aacenc                    ponysay                         vorbis-tools
cowsay                          gnutls                          libvorbis                       ponysay-tool                    vorbisgain
cscope                          go-app-engine-64                libvpx                          ponythink                       webp
ctags                           gobject-introspection   libyaml                         popt                            wget
curl                            google-perftools                linode-cli                      postgresql                      x264
curl-ca-bundle                  gource                          little-cms                      pypy                            xmlto
dart                            gsl                             lua                             python                          xvid
docbook                         gtk+                            macvim                          python3                         xz
docbook-xsl                     gtkmm                           mariadb                         ranger                          yajl
docker                          harfbuzz                        markdown                        readline                        yasm
dos2unix                        haskell-platform                mercurial                       reattach-to-user-namespace      youtube-dl
doxygen                         healthcheck-nginx-module        mod-zip-nginx-module            ruby                            zlib
extended-status-nginx-module    hicolor-icon-theme              mpd                             ruby-build                      zsh
faac                            highlight                       mpfr                            ruby-install                    zsh-completions
faad2                           htop-osx                        ncdu                            scons                 zsh-syntax-highlighting
```

Did not know about the readall command but seems like that pinpointed where the error is.

**Comment by DomT4** [comment]
There was a change to ` extended-status-nginx-module ` merged into Homebrew/nginx last night, [here](https://github.com/Homebrew/homebrew-nginx/commit/f1e6c8c9c499026595bddd5aae125406a75a3de5). Timeline fits at least.
