### ISSUE TITLE
brew install go failed with '--with-cc-common'

### ISSUE THREAD

**Issue by kuxuxun** [Homebrew/homebrew#37936]
i ran
```
brew install -vd go --with-cc-common
```
and got output
```
...
he binaries expect /private/tmp/go20150321-5456-1r0gm5d/go to be copied or moved to /usr/local/Cellar/go/1.4.2/libexec
==> Cloning https://go.googlesource.com/tools.git
git clone https://go.googlesource.com/tools.git /Library/Caches/Homebrew/go--gotools--git
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
ErrorDuringExecution: Failure while executing: git clone https://go.googlesource.com/tools.git /Library/Caches/Homebrew/go--gotools--git
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Homebrew/utils.rb:151:in `safe_system'
/usr/local/Library/Homebrew/download_strategy.rb:629:in `clone_repo'
/usr/local/Library/Homebrew/download_strategy.rb:121:in `fetch'
/usr/local/Library/Homebrew/resource.rb:109:in `fetch'
/usr/local/Library/Homebrew/resource.rb:80:in `stage'
/usr/local/Library/Homebrew/extend/pathname.rb:16:in `block in install'
/usr/local/Library/Homebrew/extend/pathname.rb:13:in `each'
/usr/local/Library/Homebrew/extend/pathname.rb:13:in `install'
/usr/local/Library/Formula/go.rb:82:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
...

```

it seems failed when simply running git clone command, so i tried just  
```
git clone https://go.googlesource.com/tools.git /Library/Caches/Homebrew/go--gotools--git
```
it finished without any error.

'brew install go' without '--with-cc-common' , it goes fine.

osx:10.9.5

**Comment by mistydemeo** [comment]
Can you post the output of `brew gist-logs go`, please?

**Comment by kuxuxun** [comment]
thank you for your comment

https://gist.github.com/anonymous/f7d9adc64d66aef49c8a

**Comment by wenerme** [comment]
```
brew install go --with-cc-common
```
One more problem

```
	/Users/wener/go/src/unicode (from $GOROOT)
	/private/tmp/go20150331-8218-fs693w/go/src/unicode (from $GOPATH)
../../present/args.go:11:2: cannot find package "unicode/utf8" in any of:
	/Users/wener/go/src/unicode/utf8 (from $GOROOT)
	/private/tmp/go20150331-8218-fs693w/go/src/unicode/utf8 (from $GOPATH)
```

**Comment by mikemcquaid** [comment]
Do you have `GOROOT` set by any chance?

**Comment by wenerme** [comment]
Thanks @mikemcquaid ,I unset the GOROOT and GOPATH, and it works

But after installed, should I set these var ?

**Comment by mikemcquaid** [comment]
No, you shouldn't have to set them.

**Comment by jacknagel** [comment]
Should we unset GOROOT and GOPATH at build-time, or...?

**Comment by wenerme** [comment]
Yes,after install,you need set it again
2015年4月30日 上午9:19于 "Jack Nagel" <notifications@github.com>写道：

**Comment by mikemcquaid** [comment]
> Yes,after install,you need set it again

Why?

> Should we unset GOROOT and GOPATH at build-time, or...?

Quite possibly, yeh.

**Comment by wenerme** [comment]
As `brew info go` said

```
==> Caveats
As of go 1.2, a valid GOPATH is required to use the `go get` command:
  https://golang.org/doc/code.html#GOPATH
```

**Comment by jacknagel** [comment]
Action items:
 * patch to remove GOROOT and GOPATH at build time
 * ??

**Comment by mikemcquaid** [comment]
@jacknagel Yeh, that sounds enough.
