### ISSUE TITLE
Pig installations errors

### ISSUE THREAD

**Issue by prakashn27** [Homebrew/homebrew#38113]
I get the below error when i try to install h=pig latin for hadoop.

Exception in thread "main" java.lang.NoClassDefFoundError: org/joda/time/ReadableInstant
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:214)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: org.joda.time.ReadableInstant
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

Please suggest what has to be done.

i tried to install pig using "brew install pig" command

**Comment by prakashn27** [comment]
i tried to install pig using "brew install pig".

**Comment by xu-cheng** [comment]
Please run `brew update && brew install pig`. It's more than likely you haven't update homebrew for a long time. If problem continues, please try to follow the [trouble shooting](http://git.io/brew-troubleshooting). Thanks.

**Comment by prakashn27** [comment]
Thanks a lot xu-chent. It solved the issue.
