### ISSUE TITLE
Mach-O, But Wrong Architecture error on clean binwalk install

### ISSUE THREAD

**Issue by jogarock** [Homebrew/homebrew#38809]
Context:  I have reinstalled binwalk and libmagic several times and this error keeps occuring when running it on an OS X 10.10 machine.  Previously, I had mucked about with gcc in a somewhat complicated cross-compilation task.  However I believe I restored any compiler settings back to normal afterward.  Running `lipo -info` and `file` on my python and libmagic yields x86_64 which is as expected...

```
$ brew install libmagic
==> Downloading https://homebrew.bintray.com/bottles/libmagic-5.22_1.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/libmagic-5.22_1.yosemite.bottle.tar.gz
==> Pouring libmagic-5.22_1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libmagic/5.22_1: 272 files, 4.7M
$ binwalk xxxxx.bin

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

Signature Exception: dlopen(/usr/local/lib/libmagic.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libmagic.dylib: mach-o, but wrong architecture
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/binwalk/core/module.py", line 481, in main
    self.init()
  File "/usr/local/lib/python2.7/site-packages/binwalk/modules/signature.py", line 85, in init
    self.magic = binwalk.core.magic.Magic(self.mfile)
  File "/usr/local/lib/python2.7/site-packages/binwalk/core/magic.py", line 43, in __init__
    self.libmagic = binwalk.core.C.Library(self.LIBRARY, self.LIBMAGIC_FUNCTIONS)
  File "/usr/local/lib/python2.7/site-packages/binwalk/core/C.py", line 100, in __init__
    self.library = ctypes.cdll.LoadLibrary(self.find_library(library))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libmagic.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libmagic.dylib: mach-o, but wrong architecture
----------------------------------------------------------------------------------------------------
```

**Comment by mistydemeo** [comment]
What is the output of `lipo -info /usr/local/lib/libmagic.dylib`? Is there anything you might have done, out of curiosity, to make the system Python start up in 32-bit mode?

**Comment by jogarock** [comment]
Yes, that is the case.  Is it outside of scope for `brew doctor` to check `[/Library/Preferences/]com.apple.versioner.python` settings and throw a warning if there may be version inconsistencies in global settings?

**Comment by tdsmith** [comment]
I'd accept a pull request if you know what to look for.
