### ISSUE TITLE
Yosemite 10.10.3 is recognised as Snow Leopard while reinstalling valgrind

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#38846]
I've installed `valgrind` (HEAD version), which requires MacOS newer than Maverick.
But when I run `brew reinstall valgrind`, it tells me 
```
==> Reinstalling valgrind
valgrind: OS X Mavericks or older is required.
Error: An unsatisfied requirement failed this build.
```

I tried digging into the problem. I print the sym and call stack in ` Library/Homebrew/os/mac/version.rb`.
```
       def self.from_symbol(sym)
+        puts sym
+        puts caller
```
and the output is as following:
```
mavericks
/usr/local/Library/Homebrew/requirements/maximum_macos_requirement.rb:7:in `initialize'
/usr/local/Library/Homebrew/dependency_collector.rb:142:in `new'
/usr/local/Library/Homebrew/dependency_collector.rb:142:in `parse_class_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:85:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:133:in `depends_on'
/usr/local/Library/Formula/valgrind.rb:18:in `block in <class:Valgrind>'
/usr/local/Library/Homebrew/formula.rb:1001:in `instance_eval'
/usr/local/Library/Homebrew/formula.rb:1001:in `stable'
/usr/local/Library/Formula/valgrind.rb:6:in `<class:Valgrind>'
/usr/local/Library/Formula/valgrind.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/reinstall.rb:5:in `reinstall'
/usr/local/Library/brew.rb:135:in `<main>'
snow_leopard
/usr/local/Library/Homebrew/requirements/minimum_macos_requirement.rb:7:in `initialize'
/usr/local/Library/Homebrew/dependency_collector.rb:107:in `new'
/usr/local/Library/Homebrew/dependency_collector.rb:107:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:81:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:65:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:133:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1033:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1033:in `each'
/usr/local/Library/Homebrew/formula.rb:1033:in `depends_on'
/usr/local/Library/Formula/valgrind.rb:41:in `<class:Valgrind>'
/usr/local/Library/Formula/valgrind.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/reinstall.rb:5:in `reinstall'
/usr/local/Library/brew.rb:135:in `<main>'
==> Reinstalling valgrind
yosemite
/usr/local/Library/Homebrew/bottles.rb:116:in `find_or_later_tag'
/usr/local/Library/Homebrew/bottles.rb:96:in `find_matching_tag'
/usr/local/Library/Homebrew/bottles.rb:70:in `fetch_checksum_for'
/usr/local/Library/Homebrew/software_spec.rb:292:in `checksum_for'
/usr/local/Library/Homebrew/software_spec.rb:279:in `tag?'
/usr/local/Library/Homebrew/software_spec.rb:65:in `bottled?'
/usr/local/Library/Homebrew/formula.rb:152:in `bottled?'
/usr/local/Library/Homebrew/cmd/reinstall.rb:23:in `reinstall_formula'
/usr/local/Library/Homebrew/cmd/reinstall.rb:5:in `block in reinstall'
/usr/local/Library/Homebrew/cmd/reinstall.rb:5:in `each'
/usr/local/Library/Homebrew/cmd/reinstall.rb:5:in `reinstall'
/usr/local/Library/brew.rb:135:in `<main>'
valgrind: OS X Mavericks or older is required.
Error: An unsatisfied requirement failed this build.
```

May it be useful for you to find the problem :)

**Comment by guoxiao** [comment]
Sorry. I just found the `valgrind` formula requires Maverick in stable version, so I should run `brew reinstall valgrind --HEAD` instead.
