### ISSUE TITLE
The test-bot just blew up. (Not literally)

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#38880]
Sometime less than an hour ago, this started happening:

```
[EnvInject] - Variables injected successfully.
[yosemite] $ /bin/sh -xe /var/folders/03/jqjv4qms2b18_hwt2dcgsghc0000gp/T/hudson6211930813668144877.sh
+ brew test-bot --ci-pr
==> brew update								 PASSED
==> git checkout 96e2e3f						 PASSED
==> brew pull --clean https://github.com/Homebrew/homebrew-versions/pull/783 PASSED
==> brew doctor								 PASSED
==> brew --env								 PASSED
==> brew config								 PASSED
==> brew tests								 PASSED
==> brew readall --syntax						 FAILED
Error: problem in /usr/local/Library/Formula/allegro4.rb
Error: problem in /usr/local/Library/Formula/allegro5.rb
Error: problem in /usr/local/Library/Formula/android-ndk-r10c.rb
Error: problem in /usr/local/Library/Formula/android-ndk-r9d.rb
Error: problem in /usr/local/Library/Formula/ansible14.rb
Error: problem in /usr/local/Library/Formula/antlr2.rb
Error: problem in /usr/local/Library/Formula/apache-spark121.rb
Error: problem in /usr/local/Library/Formula/appledoc20.rb
Error: problem in /usr/local/Library/Formula/appledoc21.rb
Error: problem in /usr/local/Library/Formula/appledoc22.rb
Error: problem in /usr/local/Library/Formula/autoconf213.rb
Error: problem in /usr/local/Library/Formula/autoconf264.rb
Error: problem in /usr/local/Library/Formula/automake112.rb
Error: problem in /usr/local/Library/Formula/bash-completion2.rb
Error: problem in /usr/local/Library/Formula/bind99.rb
Error: problem in /usr/local/Library/Formula/bison27.rb
Error: problem in /usr/local/Library/Formula/boost149.rb
Error: problem in /usr/local/Library/Formula/boost150.rb
Error: problem in /usr/local/Library/Formula/boost155.rb
Error: problem in /usr/local/Library/Formula/boot2docker133.rb
Error: problem in /usr/local/Library/Formula/boot2docker141.rb
Error: problem in /usr/local/Library/Formula/camlp5-606.rb
Error: problem in /usr/local/Library/Formula/cassandra-0.6.rb
Error: problem in /usr/local/Library/Formula/cassandra10.rb
Error: problem in /usr/local/Library/Formula/cassandra12.rb
Error: problem in /usr/local/Library/Formula/cassandra20.rb
Error: problem in /usr/local/Library/Formula/clojure14.rb
Error: problem in /usr/local/Library/Formula/cloog-ppl015.rb
Error: problem in /usr/local/Library/Formula/cloog018.rb
Error: problem in /usr/local/Library/Formula/cmake28.rb
Error: problem in /usr/local/Library/Formula/cmake30.rb
Error: problem in /usr/local/Library/Formula/cmake31.rb
Error: problem in /usr/local/Library/Formula/coq83.rb
Error: problem in /usr/local/Library/Formula/cvsps2.rb
Error: problem in /usr/local/Library/Formula/docker133.rb
Error: problem in /usr/local/Library/Formula/docker141.rb
Error: problem in /usr/local/Library/Formula/doxygen1831.rb
Error: problem in /usr/local/Library/Formula/drush4.rb
Error: problem in /usr/local/Library/Formula/drush5.rb
Error: problem in /usr/local/Library/Formula/duplicity06.rb
Error: problem in /usr/local/Library/Formula/eigen2.rb
Error: problem in /usr/local/Library/Formula/elasticsearch-0.20.rb
Error: problem in /usr/local/Library/Formula/elasticsearch090.rb
Error: problem in /usr/local/Library/Formula/elasticsearch11.rb
Error: problem in /usr/local/Library/Formula/elasticsearch12.rb
Error: problem in /usr/local/Library/Formula/elasticsearch13.rb
Error: problem in /usr/local/Library/Formula/elasticsearch14.rb
Error: problem in /usr/local/Library/Formula/erlang-r13.rb
Error: problem in /usr/local/Library/Formula/erlang-r14.rb
Error: problem in /usr/local/Library/Formula/erlang-r15.rb
Error: problem in /usr/local/Library/Formula/erlang-r16.rb
Error: problem in /usr/local/Library/Formula/gawk3.rb
Error: problem in /usr/local/Library/Formula/gcc43.rb
Error: problem in /usr/local/Library/Formula/gcc44.rb
Error: problem in /usr/local/Library/Formula/gcc45.rb
Error: problem in /usr/local/Library/Formula/gcc46.rb
Error: problem in /usr/local/Library/Formula/gcc47.rb
Error: problem in /usr/local/Library/Formula/gcc48.rb
Error: problem in /usr/local/Library/Formula/gcc49.rb
Error: problem in /usr/local/Library/Formula/gcc5.rb
Error: problem in /usr/local/Library/Formula/giflib5.rb
Error: problem in /usr/local/Library/Formula/git-tf-2.0.2.rb
Error: problem in /usr/local/Library/Formula/glfw2.rb
Error: problem in /usr/local/Library/Formula/glfw3.rb
Error: problem in /usr/local/Library/Formula/gmp4.rb
Error: problem in /usr/local/Library/Formula/gnupg21.rb
Error: problem in /usr/local/Library/Formula/gnuplot4.rb
Error: problem in /usr/local/Library/Formula/gnutls34.rb
Error: problem in /usr/local/Library/Formula/go12.rb
Error: problem in /usr/local/Library/Formula/gradle110.rb
Error: problem in /usr/local/Library/Formula/gradle112.rb
Error: problem in /usr/local/Library/Formula/gradle16.rb
Error: problem in /usr/local/Library/Formula/gradle18.rb
Error: problem in /usr/local/Library/Formula/gradle20.rb
Error: problem in /usr/local/Library/Formula/gradle21.rb
Error: problem in /usr/local/Library/Formula/gradle221.rb
Error: problem in /usr/local/Library/Formula/grails13.rb
Error: problem in /usr/local/Library/Formula/grails20.rb
Error: problem in /usr/local/Library/Formula/grails21.rb
Error: problem in /usr/local/Library/Formula/grails22.rb
Error: problem in /usr/local/Library/Formula/grails223.rb
Error: problem in /usr/local/Library/Formula/grails224.rb
Error: problem in /usr/local/Library/Formula/grails23.rb
Error: problem in /usr/local/Library/Formula/gsl114.rb
Error: problem in /usr/local/Library/Formula/gst-ffmpeg010.rb
Error: problem in /usr/local/Library/Formula/gst-plugins-bad010.rb
Error: problem in /usr/local/Library/Formula/gst-plugins-base010.rb
Error: problem in /usr/local/Library/Formula/gst-plugins-good010.rb
Error: problem in /usr/local/Library/Formula/gst-plugins-ugly010.rb
Error: problem in /usr/local/Library/Formula/gst-python010.rb
Error: problem in /usr/local/Library/Formula/gst-rtsp010.rb
Error: problem in /usr/local/Library/Formula/gstreamer010.rb
Error: problem in /usr/local/Library/Formula/guile18.rb
Error: problem in /usr/local/Library/Formula/hadoop0202.rb
Error: problem in /usr/local/Library/Formula/hadoop121.rb
Error: problem in /usr/local/Library/Formula/hadoop25.rb
Error: problem in /usr/local/Library/Formula/hdf4.rb
Error: problem in /usr/local/Library/Formula/hive010.rb
Error: problem in /usr/local/Library/Formula/hive011.rb
Error: problem in /usr/local/Library/Formula/imagemagick-ruby186.rb
Error: problem in /usr/local/Library/Formula/isl011.rb
Error: problem in /usr/local/Library/Formula/isl012.rb
Error: problem in /usr/local/Library/Formula/isl014.rb
Error: problem in /usr/local/Library/Formula/jboss-as5.rb
Error: problem in /usr/local/Library/Formula/jboss-forge1.rb
Error: problem in /usr/local/Library/Formula/jenkins-lts.rb
Error: problem in /usr/local/Library/Formula/jetty76.rb
Error: problem in /usr/local/Library/Formula/jetty8.rb
Error: problem in /usr/local/Library/Formula/jpeg6b.rb
Error: problem in /usr/local/Library/Formula/jpeg9.rb
Error: problem in /usr/local/Library/Formula/json-c010.rb
Error: problem in /usr/local/Library/Formula/kafka080.rb
Error: problem in /usr/local/Library/Formula/ledger26.rb
Error: problem in /usr/local/Library/Formula/leptonica169.rb
Error: problem in /usr/local/Library/Formula/libcouchbase1.rb
Error: problem in /usr/local/Library/Formula/libdvdcss12.rb
Error: problem in /usr/local/Library/Formula/libgee08.rb
Error: problem in /usr/local/Library/Formula/libmongoclient-legacy.rb
Error: problem in /usr/local/Library/Formula/libmpc08.rb
Error: problem in /usr/local/Library/Formula/libotr4.rb
Error: problem in /usr/local/Library/Formula/libpng12.rb
Error: problem in /usr/local/Library/Formula/libpqxx3.rb
Error: problem in /usr/local/Library/Formula/libuv0.rb
Error: problem in /usr/local/Library/Formula/llvm-gcc28.rb
Error: problem in /usr/local/Library/Formula/llvm33.rb
Error: problem in /usr/local/Library/Formula/llvm34.rb
Error: problem in /usr/local/Library/Formula/llvm35.rb
Error: problem in /usr/local/Library/Formula/llvm36.rb
Error: problem in /usr/local/Library/Formula/log4cplus10.rb
Error: problem in /usr/local/Library/Formula/lua53.rb
Error: problem in /usr/local/Library/Formula/mapnik071.rb
Error: problem in /usr/local/Library/Formula/maven2.rb
Error: problem in /usr/local/Library/Formula/maven30.rb
Error: problem in /usr/local/Library/Formula/maven31.rb
Error: problem in /usr/local/Library/Formula/maven32.rb
Error: problem in /usr/local/Library/Formula/mkvtoolnix58.rb
Error: problem in /usr/local/Library/Formula/mongodb24.rb
Error: problem in /usr/local/Library/Formula/mongodb26.rb
Error: problem in /usr/local/Library/Formula/mpfr2.rb
Error: problem in /usr/local/Library/Formula/mysql51.rb
Error: problem in /usr/local/Library/Formula/mysql55.rb
Error: problem in /usr/local/Library/Formula/nettle3.rb
Error: problem in /usr/local/Library/Formula/node010.rb
Error: problem in /usr/local/Library/Formula/node04.rb
Error: problem in /usr/local/Library/Formula/node06.rb
Error: problem in /usr/local/Library/Formula/node08.rb
Error: problem in /usr/local/Library/Formula/nu0.rb
Error: problem in /usr/local/Library/Formula/objective-caml312.rb
Error: problem in /usr/local/Library/Formula/open-mpi16.rb
Error: problem in /usr/local/Library/Formula/openjpeg20.rb
Error: problem in /usr/local/Library/Formula/openjpeg21.rb
Error: problem in /usr/local/Library/Formula/openssl098.rb
Error: problem in /usr/local/Library/Formula/openssl101.rb
Error: problem in /usr/local/Library/Formula/pandoc-citeproc05.rb
Error: problem in /usr/local/Library/Formula/pandoc1131.rb
Error: problem in /usr/local/Library/Formula/percona-server55.rb
Error: problem in /usr/local/Library/Formula/perl514.rb
Error: problem in /usr/local/Library/Formula/perl516.rb
Error: problem in /usr/local/Library/Formula/perl518.rb
Error: problem in /usr/local/Library/Formula/phantomjs17.rb
Error: problem in /usr/local/Library/Formula/phantomjs182.rb
Error: problem in /usr/local/Library/Formula/phantomjs192.rb
Error: problem in /usr/local/Library/Formula/phantomjs198.rb
Error: problem in /usr/local/Library/Formula/play12.rb
Error: problem in /usr/local/Library/Formula/play13.rb
Error: problem in /usr/local/Library/Formula/play22.rb
Error: problem in /usr/local/Library/Formula/plowshare3.rb
Error: problem in /usr/local/Library/Formula/postgis15.rb
Error: problem in /usr/local/Library/Formula/postgis20.rb
Error: problem in /usr/local/Library/Formula/postgresql8.rb
Error: problem in /usr/local/Library/Formula/postgresql9.rb
Error: problem in /usr/local/Library/Formula/postgresql91.rb
Error: problem in /usr/local/Library/Formula/postgresql92.rb
Error: problem in /usr/local/Library/Formula/postgresql93.rb
Error: problem in /usr/local/Library/Formula/povray36.rb
Error: problem in /usr/local/Library/Formula/ppl011.rb
Error: problem in /usr/local/Library/Formula/ppl10.rb
Error: problem in /usr/local/Library/Formula/protobuf240a.rb
Error: problem in /usr/local/Library/Formula/protobuf241.rb
Error: problem in /usr/local/Library/Formula/protobuf250.rb
Error: problem in /usr/local/Library/Formula/qt52.rb
Error: problem in /usr/local/Library/Formula/rabbitmq30.rb
Error: problem in /usr/local/Library/Formula/raptor1.rb
Error: problem in /usr/local/Library/Formula/redis1310.rb
Error: problem in /usr/local/Library/Formula/redis24.rb
Error: problem in /usr/local/Library/Formula/redis26.rb
Error: problem in /usr/local/Library/Formula/redis28.rb
Error: problem in /usr/local/Library/Formula/riak132.rb
Error: problem in /usr/local/Library/Formula/ruby182.rb
Error: problem in /usr/local/Library/Formula/ruby186.rb
Error: problem in /usr/local/Library/Formula/ruby192.rb
Error: problem in /usr/local/Library/Formula/ruby193.rb
Error: problem in /usr/local/Library/Formula/ruby20.rb
Error: problem in /usr/local/Library/Formula/ruby21.rb
Error: problem in /usr/local/Library/Formula/scala210.rb
Error: problem in /usr/local/Library/Formula/scala29.rb
Error: problem in /usr/local/Library/Formula/solr14.rb
Error: problem in /usr/local/Library/Formula/solr36.rb
Error: problem in /usr/local/Library/Formula/solr4.rb
Error: problem in /usr/local/Library/Formula/sonar4.rb
Error: problem in /usr/local/Library/Formula/squid2.rb
Error: problem in /usr/local/Library/Formula/subversion16.rb
Error: problem in /usr/local/Library/Formula/subversion17.rb
Error: problem in /usr/local/Library/Formula/swig2.rb
Error: problem in /usr/local/Library/Formula/swig304.rb
Error: problem in /usr/local/Library/Formula/thrift090.rb
Error: problem in /usr/local/Library/Formula/tomcat6.rb
Error: problem in /usr/local/Library/Formula/tomcat7.rb
Error: problem in /usr/local/Library/Formula/unison232.rb
Error: problem in /usr/local/Library/Formula/unison240.rb
Error: problem in /usr/local/Library/Formula/v8-315.rb
Error: problem in /usr/local/Library/Formula/valgrind36.rb
Error: problem in /usr/local/Library/Formula/valgrind38.rb
Error: problem in /usr/local/Library/Formula/varnish3.rb
Error: problem in /usr/local/Library/Formula/virtuoso616.rb
Error: problem in /usr/local/Library/Formula/zeromq22.rb
Error: problem in /usr/local/Library/Formula/zeromq3.rb
Error: problem in /usr/local/Library/Formula/zeromq32.rb
==> brew uses Homebrew/versions/node010					Error: No available formula for node010 
Please tap it and then try again: brew tap Homebrew/versions
 FAILED
Error: No available formula for node010 
Please tap it and then try again: brew tap Homebrew/versions
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
```

What broke? :smile_cat:. @Homebrew/owners

**Comment by DomT4** [comment]
Got more detail running the command locally:

```
==> brew tests								 FAILED
==> brew readall --syntax						/usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `initialize': No such file or directory - /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb-5aaf13c/homebrew.readall.txt (Errno::ENOENT)
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `open'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `fork'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `test'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:525:in `homebrew'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:619:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:820:in `block in test_bot'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `test_bot'
	from /usr/local/Library/brew.rb:135:in `<main>'
 FAILED
==> brew uses /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb/usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `initialize': No such file or directory - /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb-5aaf13c/formula./usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb.uses.txt (Errno::ENOENT)
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `open'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `fork'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `test'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:368:in `formula'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:621:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:820:in `block in test_bot'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `test_bot'
	from /usr/local/Library/brew.rb:135:in `<main>'
 FAILED
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
==> brew fetch --retry --build-bottle /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb/usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `initialize': No such file or directory - /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb-5aaf13c/formula./usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb.fetch.txt (Errno::ENOENT)
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `open'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `fork'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `test'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:442:in `formula'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:621:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:820:in `block in test_bot'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `test_bot'
	from /usr/local/Library/brew.rb:135:in `<main>'
 FAILED
==> brew install --verbose --build-bottle /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb/usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `initialize': No such file or directory - /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb-5aaf13c/formula./usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb.install.txt (Errno::ENOENT)
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `open'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `fork'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `test'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:461:in `formula'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:621:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:820:in `block in test_bot'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `test_bot'
	from /usr/local/Library/brew.rb:135:in `<main>'
 FAILED
==> brew audit /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb/usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `initialize': No such file or directory - /usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb-5aaf13c/formula./usr/local/Library/Taps/homebrew/homebrew-versions/node010.rb.audit.txt (Errno::ENOENT)
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `open'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:120:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `fork'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:119:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:571:in `test'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:465:in `formula'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:621:in `block in run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:620:in `run'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:820:in `block in test_bot'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `each'
	from /usr/local/Library/Homebrew/cmd/test-bot.rb:812:in `test_bot'
	from /usr/local/Library/brew.rb:135:in `<main>'
 FAILED
```

**Comment by DomT4** [comment]
Running that locally also just untapped everything I had tapped and removed the ` Taps ` directly completely. Welp.

**Comment by DomT4** [comment]
Seems to only impact Taps, not Homebrew/homebrew.

**Comment by jacknagel** [comment]
Only happens if you run the tests. Reverted for now.

**Comment by DomT4** [comment]
Thanks Jack, Appreciated.
