### ISSUE TITLE
undefined method `close' for nil:NilClass

### ISSUE THREAD

**Issue by Burtonia** [Homebrew/homebrew#39006]
As per your request please see below the contents of the bug:

Command run: brew postinstall mysql

```
Error:
undefined method `close' for nil:NilClass
/usr/local/Library/Homebrew/utils/fork.rb:41:in `ensure in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:42:in `safe_fork'
/usr/local/Library/Homebrew/cmd/postinstall.rb:18:in `run_post_install'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `block in postinstall'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `each'
/usr/local/Library/Homebrew/cmd/postinstall.rb:5:in `postinstall'
/usr/local/Library/brew.rb:135:in `<main>'
```

Alex,

**Comment by xu-cheng** [comment]
Please run `brew doctor` and check your write permission to the `/tmp` folder.

**Comment by Burtonia** [comment]
Thanks Jack,

Alex,
