### ISSUE TITLE
Installing LLVM failed with not sticky folder error

### ISSUE THREAD

**Issue by flyswatter** [Homebrew/homebrew#39121]
Was trying to install llvm with clang support with the command `brew install --with-clang --all-targets --rtti --universal --jit llvm`.

```
==> make
==> make install
==> make -C projects/libcxx install DSTROOT=/usr/local/Cellar/llvm/3.5.1 SYMROOT=/tmp/llv
Error: parent directory is world writable but not sticky
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:92:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:481:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by jacknagel** [comment]
What are the permissions on `/tmp`?

```
$ ls -ld /tmp
lrwxr-xr-x@ 1 root  wheel  11 Oct 16  2014 /tmp -> private/tmp
$ ls -ld /private/tmp
drwxrwxrwt  6 root  wheel  204 Apr 27 19:52 /private/tmp
```

**Comment by jacknagel** [comment]
Moving discussion to https://github.com/Homebrew/homebrew/issues/39170
