### ISSUE TITLE
install php54 error

### ISSUE THREAD

**Issue by linxun** [Homebrew/homebrew#39139]
```
Error: no implicit conversion of Float into String
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:330:in `+'
/usr/local/Library/Homebrew/install_renamed.rb:19:in `+'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:72:in `config_path'
/usr/local/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php.rb:420:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:10:in `caveats'
/usr/local/Library/Homebrew/caveats.rb:22:in `empty?'
/usr/local/Library/Homebrew/cmd/info.rb:137:in `info_formula'
/usr/local/Library/Homebrew/cmd/info.rb:31:in `block in print_info'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:28:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by xu-cheng** [comment]
This issue was moved to Homebrew/homebrew-php#1685
