### ISSUE TITLE
testpath too long for pgloader test

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew#39308]
```
$ brew test pgloader
Testing pgloader
==> initdb
==> postgres --listen_addresses= --unix_socket_directories=/private/var/folders/m9/cbwcfhj13zndn6493p2zltd40000gn/T/pgloader20150502-46424-9mh10y/socket
LOG:  Unix-domain socket path "/private/var/folders/m9/cbwcfhj13zndn6493p2zltd40000gn/T/pgloader20150502-46424-9mh10y/socket/.s.PGSQL.5432" is too long (maximum 103 bytes)
WARNING:  could not create Unix-domain socket in directory "/private/var/folders/m9/cbwcfhj13zndn6493p2zltd40000gn/T/pgloader20150502-46424-9mh10y/socket"
FATAL:  could not create any Unix-domain sockets
Error: pgloader: failed
execution expired
/usr/local/Library/Formula/pgloader.rb:333:in `sleep'
/usr/local/Library/Formula/pgloader.rb:333:in `block (2 levels) in launch_postgres'
/usr/local/Library/Formula/pgloader.rb:333:in `block in launch_postgres'
/usr/local/Library/Formula/pgloader.rb:326:in `popen'
/usr/local/Library/Formula/pgloader.rb:326:in `launch_postgres'
/usr/local/Library/Formula/pgloader.rb:369:in `block in <class:Pgloader>'
/usr/local/Library/Homebrew/formula.rb:743:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:739:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

The overlong path is coming from this line in the pgloader test block:

```
ENV["PGHOST"] = testpath/"socket"
```

This is tripping up integration tests for the freetds formula that I'm trying to update (#39255).

**Comment by L2G** [comment]
I've traced this all the way to this line in both Library/Homebrew/config.rb` and Library/Homebrew/test/lib/config.rb:

```
HOMEBREW_TEMP = Pathname.new(ENV["HOMEBREW_TEMP"] || Dir.tmpdir)
```

It would be nice if we could replace `Dir.tmpdir` with something that creates a more compact temporary path, e.g. `/private/tmp/homebrewXXXXX`.

**Comment by L2G** [comment]
https://github.com/Homebrew/homebrew/commit/b95f27ce9f956c56d080b6dc29ba8efb841c6690

:cry:

**Comment by jacknagel** [comment]
Reverted the tmpdir change.
