### ISSUE TITLE
 undefined method `close' for nil:NilClass

### ISSUE THREAD

**Issue by pathikrit** [Homebrew/homebrew#39729]
```
brew install wifi-password 
Error: undefined method `close' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:41:in `ensure in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:42:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:481:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:165:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:135:in `<main>'
```

**Comment by jacknagel** [comment]
`brew update`
