### ISSUE TITLE
Fail @ 'brew update'

### ISSUE THREAD

**Issue by alduxvm** [Homebrew/homebrew#40130]
I was happily trying to update brew when: 
 
```
brew update
error: Your local changes to the following files would be overwritten by merge:
	Library/Formula/boost.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```

Then I try to ask the doctor:

```
brew update
error: Your local changes to the following files would be overwritten by merge:
	Library/Formula/boost.rb
Please, commit your changes or stash them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
AlduxMac:local Aldux$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:

    mercurial
Error: wrong number of arguments (0 for 1..3)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:70:in `instance_eval'
/usr/local/Library/Homebrew/software_spec.rb:70:in `bottle'
/usr/local/Library/Homebrew/formula.rb:994:in `bottle'
/usr/local/Library/Formula/boost.rb:7:in `<class:Boost>'
/usr/local/Library/Formula/boost.rb:3:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/formula.rb:624:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:622:in `map'
/usr/local/Library/Homebrew/formula.rb:622:in `installed'
/usr/local/Library/Homebrew/cmd/doctor.rb:977:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:1256:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1254:in `doctor'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
`git fetch; git reset --hard origin/master` will resolve the boost problem, at your own risk. Try `brew doctor` again after that.

**Comment by alduxvm** [comment]
That did it! thanks!

**Comment by DomT4** [comment]
Great! Glad all is working again :tada:.
