### ISSUE TITLE
ranger fails to launch

### ISSUE THREAD

**Issue by ptzz** [Homebrew/homebrew#40241]
Ranger used to work flawlessly but recently I'm seeing the error below. The issue seems to be with the OS X bundled python: If I replace the shebang in `/usr/local/bin/ranger` from `#!/usr/bin/python -O` to `# !/usr/bin/env python -O` it all works fine. My default python is the Homebrew one.

```sh
~$ ranger
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 40, in <module>
    sys.exit(ranger.main())
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/main.py", line 15, in main
    from ranger.core.fm import FM
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/fm.py", line 16, in <module>
    from ranger.core.actions import Actions
  File "/usr/local/Cellar/ranger/1.7.1/libexec/ranger/core/actions.py", line 9, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

Possibly related to my `PYTHONPATH`? I set `export PYTHONPATH=$(python -c 'import sys; print ":".join(sys.path)')` in my `.bashrc` which expands to

```sh
:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python27.zip:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old:/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/site-packages:/usr/local/lib/python2.7/site-packages/gtk-2.0:/Library/Python/2.7/site-packages
```

**Comment by DomT4** [comment]
CC @tdsmith

**Comment by tdsmith** [comment]
Yes, setting your PYTHONPATH that way will break most of the python apps installed with Homebrew.

**Comment by ptzz** [comment]
Got it. Clearing `PYTHONPATH` breaks python functionality in `vim` though. I have `vim` compiled with Homebrew python. Guess I could create a `vim` alias that sets `PYTHONPATH` to the Homebrew python paths or is there a better solution?

**Comment by tdsmith** [comment]
Why do you need to set PYTHONPATH to sys.path? I think that should just be redundant. What's broken about sys.path from inside vim without PYTHONPATH set?

**Comment by ptzz** [comment]
I always had to do that for vim plugins using python to work (`pymode`, `ctrlp-py-matcher`, etc.), lots of module imports would fail otherwise. For whatever reason, after reinstalling vim it now seems to work without `PYTHONPATH` set :+1:

**Comment by tdsmith** [comment]
Okay, great! Let us know if we can help with anything else.

**Comment by srgrn** [comment]
I have the same issue but my PYTHONPATH is not set at all
Traceback (most recent call last):
  File "/Users/admin/build_tools/scripts/hockeyapp/simplified_ha_uploader.py", line 4, in <module>
    from hockeyapp_python import HockeyAppApi
  File "/Users/admin/build_tools/scripts/hockeyapp/hockeyapp_python/__init__.py", line 1, in <module>
    import Team
  File "/Users/admin/build_tools/scripts/hockeyapp/hockeyapp_python/Team.py", line 2, in <module>
    import requests
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/requests/utils.py", line 12, in <module>
    import cgi
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cgi.py", line 50, in <module>
    import mimetools
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

this fails on importing requests.

**Comment by tdsmith** [comment]
Your environment is somehow misconfigured; there's not enough information here for me to help.

**Comment by srgrn** [comment]
you are correct. i am checking it but i suspect i mixed up the python that came with the mac and the python the homebrew installed. it is not a bug in homebrew
