### ISSUE TITLE
brew install -vd memcached is throwing  curl: (22) The requested URL returned error: 401 Unauthorized

### ISSUE THREAD

**Issue by Shail-Hub** [Homebrew/homebrew#40351]
Hi ,

When I am trying to install **memcached** from brew, I get below issue. Can you please help if I am missing anything here?

**brew install -vd memcached**
```
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/memcached.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/libevent.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/makedepend.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/mysql-cluster.rb
==> Installing dependencies for memcached: openssl, libevent
==> Installing memcached dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; Mac OS X 10.10.2) https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.tar.gz -C 0 -o /Library/Caches/Homebrew/openssl-1.0.2a-1.yosemite.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 401 Unauthorized
Error: Failed to download resource "openssl"
Download failed: https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.tar.gz
Warning: Bottle installation failed: building from source.
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/makedepend.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
Error: /usr/local/opt/makedepend not present or broken
Please reinstall makedepend. Sorry :(
/usr/local/Library/Homebrew/build.rb:163:in `rescue in fixopt'
/usr/local/Library/Homebrew/build.rb:152:in `fixopt'
/usr/local/Library/Homebrew/build.rb:76:in `block in install'
/usr/local/Library/Homebrew/build.rb:75:in `each'
/usr/local/Library/Homebrew/build.rb:75:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by DomT4** [comment]
Looks like your Homebrew may be outdated. Try `brew update && brew install openssl`. The current bottle versions is `openssl-1.0.2a-1.yosemite.bottle.1.tar.gz`.

**Comment by Shail-Hub** [comment]
Thanks @DomT4, I have update brew, but it seems some proxy issue at my end

**Comment by DomT4** [comment]
Do you have a `.curlrc`? They can be known to cause certain issues.

You can always try it manually by clicking on https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.yosemite.bottle.1.tar.gz in your browser and seeing if you can download it that way. If you can, `mv ~/Downloads/openssl-1.0.2a-1.yosemite.bottle.1.tar.gz /Library/Caches/Homebrew` should work.
