### ISSUE TITLE
czmq.rb:2 and euca2ools.rb:2: syntax error, unexpected end-of-input, expecting keyword_end

### ISSUE THREAD

**Issue by aarpon** [Homebrew/homebrew#40416]
I tried running a brew update and got following error:
```
$ brew update
Error: /usr/local/Library/Formula/czmq.rb:2: invalid multibyte char (US-ASCII)
/usr/local/Library/Formula/czmq.rb:2: invalid multibyte char (US-ASCII)
/usr/local/Library/Formula/czmq.rb:2: syntax error, unexpected end-of-input, expecting keyword_end
  desc "High-level C binding for ØMQ"
                                   ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:20:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:20:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:67:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:58:in `klass'
/usr/local/Library/Homebrew/formulary.rb:54:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:166:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
```
When I fixed the character in czmq.rb:2, I got another error in /usr/local/Library/Formula/euca2ools.rb:2.

```
Error: /usr/local/Library/Formula/euca2ools.rb:2: invalid multibyte char (US-ASCII)
/usr/local/Library/Formula/euca2ools.rb:2: invalid multibyte char (US-ASCII)
/usr/local/Library/Formula/euca2ools.rb:2: syntax error, unexpected end-of-input, expecting keyword_end
  desc "Eucalyptus client API tools—works with Amazon EC2 and IAM"
                                     ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:20:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:20:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:67:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:58:in `klass'
/usr/local/Library/Homebrew/formulary.rb:54:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:166:in `factory'
/usr/local/Library/Homebrew/formula.rb:653:in `block in each'
/usr/local/Library/Homebrew/formula.rb:651:in `each'
/usr/local/Library/Homebrew/formula.rb:651:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:941:in `check_for_linked_keg_only_brews'
/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `doctor'
/usr/local/Library/brew.rb:140:in `<main>'
```

After I fixed that, brew update finished successfully.

**Comment by DomT4** [comment]
Should be fixed now after another `brew update`. If you can't update: `git fetch; git reset --hard origin/master`.
