### ISSUE TITLE
Error: cannot load such file -- tap

### ISSUE THREAD

**Issue by mholt** [Homebrew/homebrew#40814]
Running `brew update` gives me this error message:

```
Error: cannot load such file -- tap
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/tap.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/update.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:67:in `require?'
/usr/local/Library/brew.rb:131:in `<main>'
```

It says to report the bug, so here I am.

**Comment by bfontaine** [comment]
Please follow the troubleshooting guide: https://git.io/brew-troubleshooting

**Comment by mholt** [comment]
Right,  so it seems I cannot troubleshoot either. Running `brew doctor` gives:

```
Error: cannot load such file -- tap
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formula.rb:12:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/missing.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/doctor.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:67:in `require?'
/usr/local/Library/brew.rb:131:in `<main>'
```

This isn't specific to any particular formula.

**Comment by DomT4** [comment]
Can you `brew update && brew doctor -d`?

**Comment by mholt** [comment]
When I do, I get this error:

```
$ brew update && brew doctor -d
Error: cannot load such file -- tap
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/tap.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/cmd/update.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:67:in `require?'
/usr/local/Library/brew.rb:131:in `<main>'
```

I have to admit I know nothing about homebrew internals or I'd take a deeper look. The error message seems a bit enigmatic to one like myself. :smile:

**Comment by DomT4** [comment]
> I guess it wouldn't hurt if I just removed homebrew and re-installed it?

May be a bit drastic at this point, but it could help. If you don't, does ```cd `brew --prefix` && git status``` show any unexpected changes?

**Comment by mholt** [comment]
Wow, yep:

```
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Library/Formula/admesh.rb
	modified:   Library/Formula/afl-fuzz.rb
	modified:   Library/Formula/aha.rb
	modified:   Library/Formula/android-sdk.rb
	modified:   Library/Formula/apache-spark.rb
	modified:   Library/Formula/apib.rb
	modified:   Library/Formula/apngasm.rb
	modified:   Library/Formula/ats2-postiats.rb
	modified:   Library/Formula/aws-elasticbeanstalk.rb
	modified:   Library/Formula/awscli.rb
	modified:   Library/Formula/bib-tool.rb
	modified:   Library/Formula/bison.rb
	modified:   Library/Formula/cassandra.rb
	modified:   Library/Formula/ccat.rb
	modified:   Library/Formula/clamav.rb
	modified:   Library/Formula/cmake.rb
	modified:   Library/Formula/conserver.rb
	modified:   Library/Formula/coreutils.rb
	modified:   Library/Formula/crosstool-ng.rb
	modified:   Library/Formula/curlish.rb
	modified:   Library/Formula/dnscrypt-proxy.rb
	modified:   Library/Formula/dynamodb-local.rb
	modified:   Library/Formula/embulk.rb
	modified:   Library/Formula/euler-py.rb
	modified:   Library/Formula/expat.rb
	modified:   Library/Formula/ffmpeg2theora.rb
	modified:   Library/Formula/flatbuffers.rb
	modified:   Library/Formula/flow.rb
	modified:   Library/Formula/freetds.rb
	modified:   Library/Formula/freetype.rb
	modified:   Library/Formula/geos.rb
	modified:   Library/Formula/gistit.rb
	modified:   Library/Formula/git-cal.rb
	modified:   Library/Formula/git-hooks.rb
	modified:   Library/Formula/git-imerge.rb
	modified:   Library/Formula/git-integration.rb
	modified:   Library/Formula/git-octopus.rb
	modified:   Library/Formula/git-ssh.rb
	modified:   Library/Formula/global.rb
	modified:   Library/Formula/gpac.rb
	modified:   Library/Formula/grib-api.rb
	modified:   Library/Formula/gtk+3.rb
	modified:   Library/Formula/gtksourceview3.rb
	modified:   Library/Formula/h2.rb
	modified:   Library/Formula/heroku-toolbelt.rb
	modified:   Library/Formula/hh.rb
	modified:   Library/Formula/httpry.rb
	modified:   Library/Formula/influxdb.rb
	modified:   Library/Formula/iojs.rb
	modified:   Library/Formula/irssi.rb
	modified:   Library/Formula/iso-codes.rb
	modified:   Library/Formula/jboss-forge.rb
	modified:   Library/Formula/jpeg-turbo.rb
	modified:   Library/Formula/jq.rb
	modified:   Library/Formula/juju.rb
	modified:   Library/Formula/kitchen-sync.rb
	deleted:    Library/Formula/kumofs.rb
	modified:   Library/Formula/lastpass-cli.rb
	modified:   Library/Formula/libb2.rb
	modified:   Library/Formula/libgda.rb
	modified:   Library/Formula/libmagic.rb
	modified:   Library/Formula/libopendkim.rb
	modified:   Library/Formula/libp11.rb
	modified:   Library/Formula/libressl.rb
	modified:   Library/Formula/libssh2.rb
	modified:   Library/Formula/libtar.rb
	modified:   Library/Formula/libtomcrypt.rb
	modified:   Library/Formula/libtommath.rb
	modified:   Library/Formula/lz4.rb
	modified:   Library/Formula/lzo.rb
	modified:   Library/Formula/magit.rb
	modified:   Library/Formula/mobile-shell.rb
	modified:   Library/Formula/mongodb.rb
	modified:   Library/Formula/monit.rb
	modified:   Library/Formula/mysql-sandbox.rb
	modified:   Library/Formula/mysql.rb
	modified:   Library/Formula/nexus.rb
	modified:   Library/Formula/objective-caml.rb
	modified:   Library/Formula/openssl.rb
	modified:   Library/Formula/osquery.rb
	modified:   Library/Formula/parallel.rb
	modified:   Library/Formula/passenger.rb
	modified:   Library/Formula/pcre.rb
	modified:   Library/Formula/pcre2.rb
	modified:   Library/Formula/pgloader.rb
	modified:   Library/Formula/pidcat.rb
	modified:   Library/Formula/postgresql.rb
	modified:   Library/Formula/proguard.rb
	modified:   Library/Formula/protobuf-c.rb
	modified:   Library/Formula/pstoedit.rb
	modified:   Library/Formula/pstree.rb
	modified:   Library/Formula/pygobject3.rb
	modified:   Library/Formula/python.rb
	modified:   Library/Formula/python3.rb
	modified:   Library/Formula/q.rb
	modified:   Library/Formula/rename.rb
	modified:   Library/Formula/repo.rb
	modified:   Library/Formula/rethinkdb.rb
	modified:   Library/Formula/selenium-server-standalone.rb
	modified:   Library/Formula/shadowsocks-libev.rb
	modified:   Library/Formula/shpotify.rb
	modified:   Library/Formula/skinny.rb
	modified:   Library/Formula/socat.rb
	modified:   Library/Formula/solr.rb
	modified:   Library/Formula/sqlite.rb
	modified:   Library/Formula/squid.rb
	modified:   Library/Formula/sshuttle.rb
	modified:   Library/Formula/storm.rb
	modified:   Library/Formula/stunnel.rb
	modified:   Library/Formula/syncthing.rb
	modified:   Library/Formula/tegh.rb
	modified:   Library/Formula/the_platinum_searcher.rb
	modified:   Library/Formula/tidy-html5.rb
	modified:   Library/Formula/tor.rb
	modified:   Library/Formula/ucspi-tools.rb
	modified:   Library/Formula/unison.rb
	modified:   Library/Formula/upx.rb
	modified:   Library/Formula/vala.rb
	modified:   Library/Formula/valabind.rb
	modified:   Library/Formula/weechat.rb
	modified:   Library/Formula/wine.rb
	modified:   Library/Formula/winetricks.rb
	modified:   Library/Formula/x265.rb
	modified:   Library/Formula/xctool.rb
	modified:   Library/Formula/youtube-dl.rb
	modified:   Library/Formula/zurl.rb
	modified:   Library/Homebrew/caveats.rb
	modified:   Library/Homebrew/cmd/audit.rb
	modified:   Library/Homebrew/cmd/cleanup.rb
	modified:   Library/Homebrew/cmd/doctor.rb
	modified:   Library/Homebrew/cmd/readall.rb
	modified:   Library/Homebrew/cmd/tap.rb
	modified:   Library/Homebrew/cmd/test-bot.rb
	modified:   Library/Homebrew/cmd/untap.rb
	modified:   Library/Homebrew/cmd/update.rb
	modified:   Library/Homebrew/cmd/uses.rb
	modified:   Library/Homebrew/download_strategy.rb
	modified:   Library/Homebrew/exceptions.rb
	modified:   Library/Homebrew/extend/ENV/std.rb
	modified:   Library/Homebrew/extend/ENV/super.rb
	modified:   Library/Homebrew/extend/pathname.rb
	modified:   Library/Homebrew/formula.rb
	modified:   Library/Homebrew/formula_installer.rb
	modified:   Library/Homebrew/formulary.rb
	modified:   Library/Homebrew/keg_fix_install_names.rb
	modified:   Library/Homebrew/manpages/brew.1.md
	modified:   Library/Homebrew/os/mac.rb
	modified:   Library/Homebrew/os/mac/version.rb
	modified:   Library/Homebrew/os/mac/xcode.rb
	modified:   Library/Homebrew/tap_migrations.rb
	modified:   Library/Homebrew/test/Gemfile.lock
	modified:   Library/Homebrew/utils.rb
	modified:   Library/brew.rb
	modified:   share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md
	modified:   share/doc/homebrew/brew-tap.md

no changes added to commit (use "git add" and/or "git commit -a")
```

Not sure where those came from...

**Comment by DomT4** [comment]
Do `git fetch; git reset --hard origin/master`. See if the `doctor` error persists after that.

**Comment by mholt** [comment]
Ah, that did the trick! Good detective work. Thanks :+1:

**Comment by DomT4** [comment]
Thanks for filing an issue, Happy to help :tada:

**Comment by HarrisonOg** [comment]
warning: unable to unlink CONTRIBUTING.md: Permission denied
warning: unable to unlink SUPPORTERS.md: Permission denied
fatal: cannot create directory at '.github': Permission denied
 
I get this when I try the above steps

**Comment by bfontaine** [comment]
@HarrisonOg Please open a new issue; Thanks!
