### ISSUE TITLE
openssl fails "make test" on 10.10.3

### ISSUE THREAD

**Issue by jshemas** [Homebrew/homebrew#40892]
Hello!

When running ```$ brew install postgresql```

I get the the following output:
```
==> Installing dependencies for postgresql: openssl, readline
==> Installing postgresql dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2c.yosemite.bot
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2c.yosemite.bottle.tar.gz
==> Pouring openssl-1.0.2c.yosemite.bottle.tar.gz
Error: File exists - /usr/local/etc
Warning: Bottle installation failed: building from source.
==> Downloading https://www.openssl.org/source/openssl-1.0.2c.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2c.tar.gz
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2c --openssldir=/usr
==> make depend
==> make
==> make test
C = AU, ST = Queensland, O = CryptSoft Pty Ltd, CN = Test PCA (1024 bit)
error 10 at 0 depth lookup:certificate has expired
OK
make[1]: *** [test_verify] Error 2
make: *** [tests] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Installing Elixir fails due to OpenSSL errors. (https://github.com/Homebrew/homebrew/issues/33218)
```

It looks like this issue is still on going. =/

Running OSX 10.10.3 with the latest xcode.

Running ```brew gist-logs openssl``` returns:

```
$ brew gist-logs openssl
https://gist.github.com/d601ef35a813f59bae32
```

**Comment by jacknagel** [comment]
I think we should concentrate on this error:

```
==> Pouring openssl-1.0.2c.yosemite.bottle.tar.gz
Error: File exists - /usr/local/etc
```

This is preventing the bottle from being installed, which would bypass the compilation problem.

Can you run `brew install openssl --verbose --debug --homebrew-developer` and post the output?

**Comment by jshemas** [comment]
Thanks for getting back to me!

Output:
```
$ brew install openssl --verbose --debug --homebrew-developer
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/openssl.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/makedepend.rb
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/pkg-config.rb
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2c.yosemite.bottle.tar.gz
/usr/bin/curl -fLA Homebrew 0.9.5 (Ruby 2.0.0-481; OS X 10.10.3) https://homebrew.bintray.com/bottles/openssl-1.0.2c.yosemite.bottle.tar.gz -C 0 -o /Library/Caches/Homebrew/openssl-1.0.2c.yosemite.bottle.tar.gz.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 3719k  100 3719k    0     0   323k      0  0:00:11  0:00:11 --:--:--  647k
==> Verifying openssl-1.0.2c.yosemite.bottle.tar.gz checksum
==> Pouring openssl-1.0.2c.yosemite.bottle.tar.gz
tar xf /Library/Caches/Homebrew/openssl-1.0.2c.yosemite.bottle.tar.gz
Error: File exists - /usr/local/etc
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:556:in `mkpath'
/usr/local/Library/Homebrew/extend/pathname.rb:152:in `cp_path_sub'
/usr/local/Library/Homebrew/install_renamed.rb:13:in `cp_path_sub'
/usr/local/Library/Homebrew/formula_installer.rb:625:in `block in pour'
/usr/local/Library/Homebrew/formula_installer.rb:623:in `glob'
/usr/local/Library/Homebrew/formula_installer.rb:623:in `glob'
/usr/local/Library/Homebrew/formula_installer.rb:623:in `pour'
/usr/local/Library/Homebrew/formula_installer.rb:169:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

Hmm... I think its working now. Or atleast I can get pass the error.

```$ brew install postgresql
==> Installing postgresql dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.yosemite.bot
######################################################################## 100.0%
==> Pouring readline-6.3.8.yosemite.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2.1M
==> Installing postgresql
==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.4.4.yosemite.b
######################################################################## 100.0%
==> Pouring postgresql-9.4.4.yosemite.bottle.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.4) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.4/static/upgrading.html


To have launchd start postgresql at login:
    ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents
Then to load postgresql now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
Or, if you don't want/need launchctl, you can just run:
    postgres -D /usr/local/var/postgres
==> /usr/local/Cellar/postgresql/9.4.4/bin/initdb /usr/local/var/postgres
  Reason: image not found
no data was returned by command ""/usr/local/Cellar/postgresql/9.4.4/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/local/Cellar/postgresql/9.4.4/bin/initdb".
Check your installation.
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall postgresql`
==> Summary
🍺  /usr/local/Cellar/postgresql/9.4.4: 3014 files, 40M
```

**Comment by jacknagel** [comment]
What does:

```
ls -ld /usr/local/etc
```

say?

**Comment by jshemas** [comment]
```
$ ls -ld /usr/local/etc
-rw-rw-r--  1 USER  admin  275 Sep  5  2013 /usr/local/etc

```

**Comment by jacknagel** [comment]
It looks like your `/usr/local/etc` is a file rather than a directory. You should delete it.

**Comment by jshemas** [comment]
I just removed it... Do you know how/why this became a file?

**Comment by jacknagel** [comment]
Nope, sorry.

**Comment by DomT4** [comment]
@jacknagel Is it worth adding a `doctor` check to see if the folders we commonly use are actually directories?
