### ISSUE TITLE
`brew deps --installed formula' causes error

### ISSUE THREAD

**Issue by adah1972** [Homebrew/homebrew#41365]
When I type something like:

```
brew deps --installed gcc
```

I got:

```
Error: undefined method `keep_if' for #<Array:0x101a59e00>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/deps.rb:27:in `deps'
/usr/local/Library/brew.rb:124:in `send'
/usr/local/Library/brew.rb:124
```

If I do not specify a formula, it works. I am on Lion. My Ruby version is "ruby 1.8.7 (2012-02-08 patch level 358) [universal-darwin11.0]" (in case it matters).

**Comment by mistydemeo** [comment]
Fixed, thanks for the report!
