### ISSUE TITLE
php55-phalcon install in mac ox bug

### ISSUE THREAD

**Issue by 250121244** [Homebrew/homebrew#41483]
when i execute brew install php55-phalcon at mac os. i got this report.
``` 
Error: undefined method `desc' for Php55Phalcon:Class. 
and the detail error message is :
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php55-phalcon.rb:5:in `<class:Php55Phalcon>'
/usr/local/Library/Taps/homebrew/homebrew-php/Formula/php55-phalcon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:42:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```
how can i do ?  please helpe.

**Comment by bfontaine** [comment]
Please see https://git.io/brew-troubleshooting

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-php#1828
