### ISSUE TITLE
brew requested me to report this bug

### ISSUE THREAD

**Issue by ddd1600** [Homebrew/homebrew#41496]
```
Davids-MacBook-Pro-2:libsigrok daviddouglas$ brew install sigrok-cli
==> Installing sigrok-cli from rene-dev/homebrew-sigrok
==> Installing dependencies for rene-dev/sigrok/sigrok-cli: libzip, libsigc++, glibmm, doxygen, 
==> Installing rene-dev/sigrok/sigrok-cli dependency: libzip
==> Downloading https://homebrew.bintray.com/bottles/libzip-0.11.2.yosemite.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring libzip-0.11.2.yosemite.bottle.2.tar.gz
🍺  /usr/local/Cellar/libzip/0.11.2: 81 files, 536K
==> Installing rene-dev/sigrok/sigrok-cli dependency: libsigc++
==> Downloading https://homebrew.bintray.com/bottles/libsigc++-2.4.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libsigc++-2.4.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/libsigc++/2.4.1: 679 files, 14M
==> Installing rene-dev/sigrok/sigrok-cli dependency: glibmm
==> Downloading https://homebrew.bintray.com/bottles/glibmm-2.44.0.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glibmm-2.44.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/glibmm/2.44.0: 1626 files, 42M
==> Installing rene-dev/sigrok/sigrok-cli dependency: doxygen
==> Downloading https://homebrew.bintray.com/bottles/doxygen-1.8.9.1.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring doxygen-1.8.9.1.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/doxygen/1.8.9.1: 5 files, 15M
==> Installing rene-dev/sigrok/sigrok-cli dependency: autoconf-archive
==> Downloading https://homebrew.bintray.com/bottles/autoconf-archive-2015.02.24.yosemite.bottle.tar.gz
######################################################################## 100.0%
==> Pouring autoconf-archive-2015.02.24.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/autoconf-archive/2015.02.24: 558 files, 4.3M
==> Installing rene-dev/sigrok/sigrok-cli dependency: libsigrok
==> Downloading http://sigrok.org/download/source/libsigrok/libsigrok-0.3.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libsigrok/0.3.0
==> make install
==> ln -s /usr/local/share/ /usr/local/Cellar/libsigrok/0.3.0/share
🍺  /usr/local/Cellar/libsigrok/0.3.0: 12 files, 1.5M, built in 24 seconds
==> Installing rene-dev/sigrok/sigrok-cli dependency: libsigrokdecode
==> Downloading http://sigrok.org/download/source/libsigrokdecode/libsigrokdecode-0.3.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/libsigrokdecode/0.3.0
==> make install
  CCLD     libsigrokdecode.la
ld: library not found for -lsigrokdecode
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tests/runtc] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/Library/Homebrew/build.rb:181:in `dump': can't dump anonymous class #<Class:0x007fc17ba295d8> (TypeError)
	from /usr/local/Library/Homebrew/build.rb:181:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:167:in `<main>'
Error: marshal data too short
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:39:in `load'
/usr/local/Library/Homebrew/utils/fork.rb:39:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils.rb:280:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:483:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:184:in `install'
/usr/local/Library/Homebrew/formula_installer.rb:360:in `install_dependency'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `block in install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `each'
/usr/local/Library/Homebrew/formula_installer.rb:318:in `install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:222:in `compute_and_install_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:149:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:166:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:83:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
Not being a core formula there may be a limited amount we can do to help here, but please add a `brew gist-logs libsigrokdecode` and we'll take a look. Thanks.

**Comment by xu-cheng** [comment]
Please run `brew update` and try again.
