### ISSUE TITLE
Error: uninitialized constant Checks::EOS with El Capitan

### ISSUE THREAD

**Issue by CharlesWiltgen** [Homebrew/homebrew#41667]
Hello,

I was asked to report this error when running `brew doctor` on El Capitan:

```
Error: uninitialized constant Checks::EOS
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/doctor.rb:282:in `check_xcode_up_to_date'
/usr/local/Library/Homebrew/cmd/doctor.rb:1273:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1271:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1271:in `doctor'
/usr/local/Library/brew.rb:124:in `<main>'
```

I'm just a user, but please let me know what I can do (if anything) to help.

— Charles

**Comment by mistydemeo** [comment]
What's the output of:

```
cd /usr/local
git status
```

**Comment by DomT4** [comment]
@mistydemeo There's a double EOS on line 282 [here](https://github.com/Homebrew/homebrew/commit/f71f237bf7fc1c9786587cb37fd96cc096572160).
