### ISSUE TITLE
How to distribute a java app (jar file with bash launcher) through Homebrew?

### ISSUE THREAD

**Issue by Krasnyanskiy** [Homebrew/homebrew#41680]
I have two files: executable jar file `jrsh-2.0.4.jar` and `jrsh.sh` script to run the jar. I want to run it through the Homebrew. What should I do to make it possible?

My `run.sh` script
```bash
#!/usr/bin/env bash
java -jar *.jar $*
```

I created a tar.gz file and made a formula
```bash
brew create 'path/to/my/jrsh-2.0.4.tar.gz'
```
Then I downloaded it using `brew install jrsh`. But it doesn't work.

**Comment by DomT4** [comment]
Something like [this](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/bfg.rb#L7-L10) would work. You could either permit Homebrew to create a new Jar script for you, or simply replace `bin.write_jar_script` with `bin.install_symlink libexec/"run.sh"`. Should work. Let us know if you hit any further issues.

**Comment by Krasnyanskiy** [comment]
I got this error
```bash
Error: undefined method `desc' for Formulary::Formulae::Jrsh:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/jrsh.rb:2:in `<class:Jrsh>'
/usr/local/Library/Formula/jrsh.rb:1:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:92:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:92:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:82:in `klass'
/usr/local/Library/Homebrew/formulary.rb:71:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:200:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
Make sure your brew is up-to-date with `brew update`.

**Comment by Krasnyanskiy** [comment]
After update I got this error
```bash
$ brew install jrsh
==> Downloading https://github.com/Krasnyanskiy/jrsh/releases/download/v2.0.4/jrsh-2.0.4-jar-with-dependencies.jar
==> Downloading from https://s3.amazonaws.com/github-cloud/releases/27540930/a49364a4-29d6-11e5-82a2-44fa98af1423.jar?re
######################################################################## 100.0%
Warning: Cannot verify integrity of jrsh-2.0.4.jar
A checksum was not provided for this resource
For your reference the SHA256 is: 5b3417c6658281ee6db60c8c70aace2d827eeefcffdf4ad822fee4c1fad69596
Error: No such file or directory - bfg-1.12.3.jar
```

**Comment by Krasnyanskiy** [comment]
I fixed `libexec.install` and installed `jrsh` one more time.

```bash
==> Downloading https://github.com/Krasnyanskiy/jrsh/releases/download/v2.0.4/jrsh-2.0.4-jar-with-dependencies.jar
Already downloaded: /Library/Caches/Homebrew/jrsh-2.0.4.jar
Warning: Cannot verify integrity of jrsh-2.0.4.jar
A checksum was not provided for this resource
For your reference the SHA256 is: 5b3417c6658281ee6db60c8c70aace2d827eeefcffdf4ad822fee4c1fad69596
🍺  /usr/local/Cellar/jrsh/2.0.4: 2 files, 13M, built in 2 secondsv
```

**Comment by Krasnyanskiy** [comment]
But I still can not run the app
```bash
$ jrsh
-bash: jrsh: command not found
```

**Comment by Krasnyanskiy** [comment]
Hmmm... I made 
```bash
brew create 'https://github.com/Krasnyanskiy/jrsh/releases/download/v2.0.4/jrsh-2.0.4.zip'
brew audit --strict jrsh
brew update
brew reinstall jrsh
```
And now it works fine.

**Comment by Krasnyanskiy** [comment]
Resolved.

**Comment by Krasnyanskiy** [comment]
Error: No available formula for jrsh 
Searching formulae...
Searching taps...

**Comment by DomT4** [comment]
Did you create the new formula in a branch and then `brew update`? You may need to check the branch out again if so.

**Comment by Krasnyanskiy** [comment]
Oh, how can I do it?

**Comment by DomT4** [comment]
Any idea if you created the new formula in a branch or not?

**Comment by Krasnyanskiy** [comment]
Yes, I guess I changed it.

**Comment by Krasnyanskiy** [comment]
So, I need to make `brew install ...` again, right?

**Comment by DomT4** [comment]
Unless you've uninstalled it, the installation should still be there.

**Comment by Krasnyanskiy** [comment]
I've cleaned up all brew stuff and tried to reinstall the app. Here is what I got

```bash
alexanders-mbp:jrsh akrasnyanskiy$ brew install 'https://github.com/Krasnyanskiy/jrsh/releases/download/v2.0.4/jrsh-2.0.4.zip'
######################################################################## 100.0%
Error: uninitialized constant Formulary::FormulaNamespace3d9081e5aaefaee72d78da84dd674461::PK
Please report this bug:
    https://git.io/brew-troubleshooting
/Library/Caches/Homebrew/Formula/jrsh-2.0.4.zip:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:128:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:170:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:124:in `<main>'
```

**Comment by Krasnyanskiy** [comment]
Seems I uninstalled it
```
$ brew uninstall jrsh
Error: No such keg: /usr/local/Cellar/jrsh
```

**Comment by DomT4** [comment]
You'll need to re-install it from the formula you created.

**Comment by Krasnyanskiy** [comment]
How can I do it?

**Comment by Krasnyanskiy** [comment]
And I've noticed that I can't find the formula: http://brewformulas.org/search?utf8=%E2%9C%93&search%5Bterm%5D=jrsh&commit=Search

**Comment by DomT4** [comment]
brewformulas will only list official formulae, not user-generated ones that haven't been merged into the core.

You'll need to check out whichever branch you created the formula in, and then `brew install jrsh` again. You can see which branches exist by doing `cd $(brew --prefix) && git branch`.

**Comment by Krasnyanskiy** [comment]
Ok, now it works. But other people could not install it. I made pull request with my formula.

**Comment by DomT4** [comment]
Thanks. Will let the test-bot review the submission, Closing here.

**Comment by Krasnyanskiy** [comment]
Ok, thanks.
