### ISSUE TITLE
Python package has no bsddb support

### ISSUE THREAD

**Issue by piejanssens** [Homebrew/homebrew#41875]
Shelve uses bsddb as it's backend db module.
On OS X (10.11) importing shelve produces a module '_bsddb' not found error.

**Comment by piejanssens** [comment]
Traceback (most recent call last):
  File "/Users/Pieter/PycharmProjects/premiumizer/Premiumizer.py", line 53, in <module>
    db = shelve.open('premiumizer.db')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb

**Comment by piejanssens** [comment]
Patch: http://marc-abramowitz.com/download/patches/python/dbhash/dbhash_bsddb3.patch

Maybe this patch needs to be added to python's formulae?

**Comment by tdsmith** [comment]
Per https://docs.python.org/2/library/bsddb.html, the bsddb module is deprecated and requires a Berkeley DB library version from 4.0-4.7. Homebrew does not ship a compatible version of bsddb. `berkeley-db` is v6.1.19 and `berkeley-db4` is v4.8.30.

Shelve can use any of several backends, like gdbm, though obviously if you're trying to read a shelf created by a particular backend, you need the same backend to read it.

**Comment by tdsmith** [comment]
The Python bug tracker says support for 4.8 was added, so this may be easy to fix after all: https://bugs.python.org/issue6949

**Comment by tdsmith** [comment]
Added support in 3f1dfb8; you will be able to `brew reinstall python --with-berkeley-db4` after running `brew update`.
