### ISSUE TITLE
brew gist-logs: buffer error

### ISSUE THREAD

**Issue by tzudot** [Homebrew/homebrew#42100]
```
~ ❯❯❯ brew gist-logs wireshark
Error: buffer error
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:226:in `body'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:163:in `reading_body'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:115:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:72:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:24:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:140:in `gist_logs'
/usr/local/Library/brew.rb:124:in `<main>'
```
**Brew config**
```
~ ❯❯❯ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 627df2a36591418336e0a181ceafc200b8310186
Last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.10.4-x86_64
Xcode: 6.4
CLT: 6.4.0.0.1.1435007323
Clang: 6.1 build 602
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /opt/rubies/ruby-2.2.2/bin/ruby
Java: 1.7.0_75
```

**Comment by DomT4** [comment]
Does this reproduce for you?

**Comment by tzudot** [comment]
No, but it seemed to me earlier that this issue can be replicated when the log files grow in size, beyond 3 MB. Buffer error not happening anymore but I get the following error now,

```sh
$ brew gist-logs wireshark
Error: HTTP 404 Not Found (expected 201)

$ brew doctor
Your system is ready to brew.
```

Any changes to GitHub's Gist API lately? Couldn't find any updates in the [docs](https://developer.github.com/v3/gists/).

**Comment by tzudot** [comment]
I updated my GitHub API token, `HOMEBREW_GITHUB_API_TOKEN` and `404` error is no longer any issue.

**Comment by DomT4** [comment]
Was going to ask about that today - I spent about 30 minutes last night going back through similar issues and that seemed to be the common cause. Glad all is working now, Thanks for the report!

**Comment by sjackman** [comment]
To fix this error, go to https://github.com/settings/tokens
Select `edit` for your `HOMEBREW_GITHUB_API_TOKEN`
Enable the checkbox for `gist`
Select `Update token`

See also https://github.com/Linuxbrew/linuxbrew/issues/673
and https://github.com/Homebrew/homebrew/issues/39864
