### ISSUE TITLE
invalid multibyte char (UTF-8) installing bottle from URL

### ISSUE THREAD

**Issue by dbogdanov** [Homebrew/homebrew#42471]
I got an error when installing a bottle from URL on Yosemite. There are no errors when I download the same bottle file to disk and install providing the path to that file.

I have updated brew to the latest version 0.9.5
```
brew install http://essentia.upf.edu/documentation/homebrew/essentia-HEAD.yosemite.bottle.tar.gz --HEAD
######################################################################## 100,0%
Error: /Library/Caches/Homebrew/Formula/essentia-HEAD.yosemite.bottle.tar.gz:1: Invalid char `\x1F' in expression
/Library/Caches/Homebrew/Formula/essentia-HEAD.yosemite.bottle.tar.gz:1: invalid multibyte char (UTF-8)
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:133:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:41:in `install'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by mistydemeo** [comment]
Installing bottles from URL isn't supported; it's being interpreted as a formula (Ruby source code), hence the error message you're seeing. Sorry!
