### ISSUE TITLE
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by jrp2014** [Homebrew/homebrew#42584]
$ brew update
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
$ brew update
Updated Homebrew from 70752bb2 to 70752bb2.
==> Updated Formulae
homebrew/science/nextflow

**Comment by jrp2014** [comment]
(Sorry, should have looked at earlier thread.)
