### ISSUE TITLE
uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by Godisemo** [Homebrew/homebrew#42597]
Got this message when I tried to update today. Not sure what it means.

```
➜  ~  🐓  brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
```

Updating again seemed to fix the issue.

```
➜  ~  🐓  brew update
Updated Homebrew from 5cd762f5 to 5cd762f5.
==> New Formulae
homebrew/science/psmc
==> Updated Formulae
homebrew/science/htsbox	    homebrew/science/nextflow	homebrew/science/vcftools
```

Feel free to close this if it is a known bug.

**Comment by Godisemo** [comment]
I did not realize this was a dupe of #42553.
