### ISSUE TITLE
On `brew upgrade`:  uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by lthibault** [Homebrew/homebrew#42608]
Hello,

Homebrew kindly asked me to report the following bug:

```
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:214:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
```

Additionally, here is the output of `brew doctor`:

```
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default OS X filesystem is case-insensitive. Please report any apparent problems.

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/python2.7/greenlet/greenlet.h
    /usr/local/include/python2.7/pygame/_camera.h
    /usr/local/include/python2.7/pygame/_pygame.h
    /usr/local/include/python2.7/pygame/_surface.h
    /usr/local/include/python2.7/pygame/bitmask.h
    /usr/local/include/python2.7/pygame/camera.h
    /usr/local/include/python2.7/pygame/fastevents.h
    /usr/local/include/python2.7/pygame/font.h
    /usr/local/include/python2.7/pygame/freetype.h
    /usr/local/include/python2.7/pygame/mask.h
    /usr/local/include/python2.7/pygame/mixer.h
    /usr/local/include/python2.7/pygame/pgarrinter.h
    /usr/local/include/python2.7/pygame/pgbufferproxy.h
    /usr/local/include/python2.7/pygame/pgcompat.h
    /usr/local/include/python2.7/pygame/pgopengl.h
    /usr/local/include/python2.7/pygame/pygame.h
    /usr/local/include/python2.7/pygame/scrap.h
    /usr/local/include/python2.7/pygame/surface.h
```

Best regards,
Louis

**Comment by DomT4** [comment]
Please see #42553. It's a one-time error that won't reproduce and can be vanquished with another `brew update`. Thanks!
