### ISSUE TITLE
user ~ doesn't exist

### ISSUE THREAD

**Issue by wdanilo** [Homebrew/homebrew#42665]
Hello! I'm using home-brew for a while and it as working fine until a small time ago, when I noticed that it stated sometimes throwing a strange error when trying to run some commands. For example `brew search` and `brew update` work fine, but when trying to run `brew doctor` I get:
```
Error: user ~ doesn't exist
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils.rb:247:in `expand_path'
/usr/local/Library/Homebrew/utils.rb:247:in `block in which'
/usr/local/Library/Homebrew/utils.rb:246:in `each'
/usr/local/Library/Homebrew/utils.rb:246:in `which'
/usr/local/Library/Homebrew/os/mac/xcode.rb:79:in `uncached_version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:70:in `version'
/usr/local/Library/Homebrew/os/mac/xcode.rb:129:in `provides_autotools?'
/usr/local/Library/Homebrew/cmd/doctor.rb:933:in `check_for_autoconf'
/usr/local/Library/Homebrew/cmd/doctor.rb:1268:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1266:in `doctor'
/usr/local/Library/brew.rb:127:in `<main>'
```

or `brew cask install time-sink`:

```
Error: user ~ doesn't exist
/usr/local/Library/Homebrew/utils.rb:247:in `expand_path'
/usr/local/Library/Homebrew/utils.rb:247:in `block in which'
/usr/local/Library/Homebrew/utils.rb:246:in `each'
/usr/local/Library/Homebrew/utils.rb:246:in `which'
/usr/local/Library/brew.rb:128:in `<main>'
```

I've reinstalled home-brew but the problem persisted.

**Comment by wdanilo** [comment]
Interesting, I've just found an exactly the same problem with the same solution. I mean - somehow my Path envier was changed to include `~~` on the beginning. Anyway brew works fine after the fix.

**Comment by dunn** [comment]
Glad you were able to figure it out! Please let us know if you have other questions.
