### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by yuanxj1024** [Homebrew/homebrew#42874]
Hi Guys,

I was installed brew for Linux, but when I use 'brew install xxx' or 'brew doctor' to run then I got an error: 

```
[develop@localhost ~]$ brew doctor                                                                      │
Error: invalid byte sequence in US-ASCII                                                                │
Please report this bug:                                                                                 │
    https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshoot│
ing                                                                                                     │
/home/develop/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1199:in `check_xcode_license_approved'          │
/home/develop/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1297:in `block in doctor'                       │
/home/develop/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1295:in `each'                                  │
/home/develop/.linuxbrew/Library/Homebrew/cmd/doctor.rb:1295:in `doctor'                                │
/home/develop/.linuxbrew/Library/brew.rb:127:in `<main>'
```

My system info : 

```
[develop@localhost ~]$ uname -a                                                                         │
Linux localhost.localdomain 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Please give me some help, tks.

**Comment by mistydemeo** [comment]
What are your `LOCALE` and `LANG`?

**Comment by mikemcquaid** [comment]
> I was installed brew for Linux

Please report this to Linuxbrew.
