### ISSUE TITLE
Cannot update brew

### ISSUE THREAD

**Issue by yudaprama** [Homebrew/homebrew#42916]
brew update
```
error: unknown option `short'
usage: git symbolic-ref [options] name [ref]

    -q, --quiet           suppress error message for non-symbolic (detached) refs
    -m <reason>           reason of the update

Error: Failure while executing: git symbolic-ref --short HEAD
```

OSX Mountain Lion

**Comment by bfontaine** [comment]
What is the output of `brew doctor`?

**Comment by yudaprama** [comment]
brew doctor

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: A newer Command Line Tools release is available.
The standalone package can be obtained from
  https://developer.apple.com/downloads
or it can be installed via Xcode's preferences.

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:

  /Users/user/.node/bin/reapp-config

Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew upgrade git

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install fribidi libass libvpx xvid

Run `brew missing` for more details.

Warning: Some directories in your path end in a slash.
Directories in your path should not end in a slash. This can break other
doctor checks. The following directories should be edited:
    /Users/user/.node/bin/

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

    erb
    gem
    irb
    rake
    rdoc
    ri
    ruby

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
    echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile

Warning: Your Xcode (5.0.2) is outdated
Please update to Xcode 5.1.1.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/

Warning: Your Homebrew is outdated.
You haven't updated for at least 24 hours. This is a long time in brewland!
To update Homebrew, run `brew update`.
```

git version
```git version 1.7.9.6 (Apple Git-31.1)```

OSX Mountain Lion

**Comment by yudaprama** [comment]
brew upgrade git
```
Error: No such file or directory - /usr/local/Cellar/git
```

**Comment by bfontaine** [comment]
@yudaprama please run `brew install git` instead.

**Comment by yudaprama** [comment]
After execute ```brew install git```, I got new error on ```brew update```:

```
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:227:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `send'
/usr/local/Library/brew.rb:127
```

**Comment by yudaprama** [comment]
Strange! Second run was solved

**Comment by bfontaine** [comment]
Yes, this is a known issue that happens only one. See #42553.
