### ISSUE TITLE
Formula rename breaks brew upgrade

### ISSUE THREAD

**Issue by guoxiao** [Homebrew/homebrew#42938]
I met a problem after `objective-caml` was renamed to `ocaml` when running `brew upgrade`:
```
% brew upgrade
Error: No such file or directory - /usr/local/Cellar/ocaml
```
I met a similar problem several days ago, and solved it by uninstall and reinstall.

**Comment by vladshablinsky** [comment]
@guoxiao can you reproduce the behaviour? If yes, can you run it with `--debug`?

**Comment by guoxiao** [comment]
@vladshablinsky The output call stack of `--debug` is as following:
```
Error: No such file or directory - /usr/local/Cellar/ocaml
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Library/Homebrew/extend/pathname.rb:282:in `subdirs'
/usr/local/Library/Homebrew/cmd/outdated.rb:19:in `block in outdated_brews'
/usr/local/Library/Homebrew/cmd/outdated.rb:16:in `map'
/usr/local/Library/Homebrew/cmd/outdated.rb:16:in `outdated_brews'
/usr/local/Library/Homebrew/cmd/upgrade.rb:9:in `upgrade'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by guoxiao** [comment]
You can reproduce the problem by the follow steps:
```
% git checkout a5e3fba63882b01dcffa7c9d17da6d5300c3a980^
.....
% brew install libcppa
.....
% git checkout master
....
% brew upgrade
Error: No such file or directory - /usr/local/Cellar/caf
```

**Comment by vladshablinsky** [comment]
@guoxiao thanks, found a problem.

**Comment by mikemcquaid** [comment]
@guoxiao Thanks for the great reproduction instructions. Fixed now.
