### ISSUE TITLE
HOMEBREW_CURL_VERBOSE breaks CurlApacheMirrorDownloadStrategy

### ISSUE THREAD

**Issue by smarek** [Homebrew/homebrew#43002]
When ENV HOMEBREW_CURL_VERBOSE is set, CurlApacheMirrorDownloadStrategy will pass CURL verbose debug info to JSON parsing. Resulting in multiple raisable errors. See the log below.

I was not able to get rid of the issue, so I'm not providing patch PR, sorry.

```
> brew install ant --with-bcel --with-ivy -d
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/ant.rb
/usr/local/Library/Homebrew/build.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/ant.rb
==> Downloading https://www.apache.org/dyn/closer.cgi?path=ant/binaries/apache-ant-1.9.6-bin.tar.bz2
Already downloaded: /Library/Caches/Homebrew/ant-1.9.6.tar.bz2
==> Downloading https://www.apache.org/dyn/closer.cgi?path=ant/ivy/2.4.0/apache-ivy-2.4.0-bin.tar.gz
==> *   Trying 88.198.26.2...
* Connected to www.apache.org (88.198.26.2) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Ser
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
Vendor::OkJson::Error: invalid character at "*   Trying"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
Utils::JSON::Error: invalid character at "*   Trying"
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
CurlDownloadStrategyError: Download failed: Couldn't determine mirror, try again later.
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
DownloadError: Failed to download resource "ant--ivy"
Download failed: Couldn't determine mirror, try again later.
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 1
Error: Failed to download resource "ant--ivy"
Download failed: Couldn't determine mirror, try again later.
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Homebrew/download_strategy.rb:391:in `rescue in _fetch'
/usr/local/Library/Homebrew/download_strategy.rb:378:in `_fetch'
/usr/local/Library/Homebrew/download_strategy.rb:286:in `fetch'
/usr/local/Library/Homebrew/resource.rb:109:in `fetch'
/usr/local/Library/Homebrew/resource.rb:80:in `stage'
/usr/local/Library/Formula/ant.rb:40:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:682:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1095:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:16:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1087:in `stage'
/usr/local/Library/Homebrew/formula.rb:678:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
```

**Comment by DomT4** [comment]
Well, you get further than I do :wink:

```
==> Downloading https://www.apache.org/dyn/closer.cgi?path=ant/binaries/apache-ant-1.9.6-bin.tar.bz2
Error: Failed to download resource "ant"
Download failed: Couldn't determine mirror, try again later.
```

**Comment by smarek** [comment]
@DomT4 that's because I have initially downloaded the ANT package manually and put it into `/Library/Caches/Homebrew` before further investigating why its download failed.

I've tried to add `--silent` argument within `CurlDownloadStrategy` to enforce that, but that's plain wrong, and didn't work either. Also `curl "-s" "#{@url}&asjson=1" ` within `CurlApacheMirrorDownloadStrategy.apache_mirrors` doesn't work as I think it would.

**Comment by smarek** [comment]
@xu-cheng thanks !
