### ISSUE TITLE
cpp-ethereum error: undefined method `dev_tools_path' for OS::Mac:Module

### ISSUE THREAD

**Issue by flyswatter** [Homebrew/homebrew#43012]
I was following [the instructions on the cpp-ethereum github](https://github.com/ethereum/go-ethereum/wiki/Mining#on-macosx), and I got this strange error that asked me to report it here.

```
 brew reinstall cpp-ethereum --with-gpu-mining --devel --headless --build-from-source
==> Reinstalling ethereum/ethereum/cpp-ethereum
==> Installing ethereum/ethereum/cpp-ethereum dependency: homebrew/version
==> Downloading https://github.com/v8/v8/archive/3.15.11.tar.gz
Already downloaded: /Library/Caches/Homebrew/v8-315-3.15.11.tar.gz
Error: undefined method `dev_tools_path' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-versions/v8-315.rb:21:in `install'
/usr/local/Library/Homebrew/build.rb:129:in `block in install'
/usr/local/Library/Homebrew/formula.rb:682:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1095:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:91:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:16:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1087:in `stage'
/usr/local/Library/Homebrew/formula.rb:678:in `brew'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:179:in `<main>'
Dans-Mac-Pro:Desktop danfinlay$ brew gist-logs cpp-ethereum
Error: No logs.
```

**Comment by flyswatter** [comment]
So is this available for install now, @DomT4?  How do I get the master home-brew installed?

**Comment by DomT4** [comment]
It should work now. `brew update && brew install homebrew/versions/v8-315`?
