### ISSUE TITLE
brew update: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

### ISSUE THREAD

**Issue by ahojchris** [Homebrew/homebrew#43033]
Just got this when I tried to update brew... Seems to have resolved itself, as I don't get the same message when I do `brew update` the second time, but thought I'd report it anyway.

```
$ brew update
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:226:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'

$ brew doctor
Your system is ready to brew.

$ brew update
Already up-to-date.

**Comment by DomT4** [comment]
See #42553. If you `brew update` again as you have there the error doesn't reproduce. It's safe to ignore. Thanks for reporting!
