### ISSUE TITLE
Found an issue with brew update

### ISSUE THREAD

**Issue by istx25** [Homebrew/homebrew#43125]
When running `brew update`, I received this error.

```
$ douglas ~/Desktop $ brew update
   Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
   Please report this bug:
       https://git.io/brew-troubleshooting
   /usr/local/Library/Homebrew/formulary.rb:226:in `loader_for'
   /usr/local/Library/Homebrew/formulary.rb:176:in `factory'
   /usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
   /usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
   /usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
   /usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
   /usr/local/Library/brew.rb:124:in `<main>'
```

**Comment by istx25** [comment]
Just saw the note about this already being fixed. Sorry.

**Comment by istx25** [comment]
:+1:
