### ISSUE TITLE
Undefined method `link_overwrite'

### ISSUE THREAD

**Issue by RichardSchmitz** [Homebrew/homebrew#43448]
Homebrew told me to report this error so I'm faithfully doing my duty.

```
11:59:01 mymachine:~$ brew update
Error: undefined method `link_overwrite' for #<Class:0x007f806cf170b8>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Formula/glib-networking.rb:23:in `<class:GlibNetworking>'
/usr/local/Library/Formula/glib-networking.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:78:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:69:in `klass'
/usr/local/Library/Homebrew/formulary.rb:65:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:174:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:191:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:191:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:25:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by DomT4** [comment]
Thanks for the report! It's a harmless bug that you won't see more than once. Can be safely ignored.
