### ISSUE TITLE
Pip not working with python 2.7.10 brew install

### ISSUE THREAD

**Issue by kdsamra** [Homebrew/homebrew#43688]
I have searched online for a solution but nothing solves this problem.  Pip is not working with the latest brew python install. I checked that brew is up to date. Here is the output I get:

pip install virtualenv
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.0', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 210, in main
    cmd_name, cmd_args = parseopts(args)
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 155, in parseopts
    general_options, args_else = parser.parse_args(args)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/optparse.py", line 1384, in parse_args
    values = self.get_default_values()
  File "/usr/local/lib/python2.7/site-packages/pip/baseparser.py", line 282, in get_default_values
    defaults = self._update_defaults(self.defaults.copy())  # ours
  File "/usr/local/lib/python2.7/site-packages/pip/baseparser.py", line 229, in _update_defaults
    val = strtobool(val)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/util.py", line 325, in strtobool
    raise ValueError, "invalid truth value %r" % (val,)
ValueError: invalid truth value 'truec'

**Comment by mistydemeo** [comment]
Do you know if you have a pip config file? The error came up while it was parsing config files.

**Comment by mistydemeo** [comment]
Specifically, I suspect you have one of the following three lines in your pip config file:

```
store_true = truec
store_false = truec
count = truec
```

[This document](http://pip.readthedocs.org/en/latest/user_guide.html#config-file) lists the locations at which pip will look up a config file - you can check those.

**Comment by kdsamra** [comment]
Hi Misty,

Thanks for looking into this.  I haven't been able to locate any pip.conf
file.  I have tried uninstalling everything, including homebrew and
restarting everything from scratch but each time I get the same error.
Please let me know if you have any other ideas.

Thanks,
Kiran

**Comment by kdsamra** [comment]
OK, I figured this out. I had gone through a tutorial that instructed me to update the ~/.bashrc file to include the following:

#pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=truec

I wasn't able to get postgres working so I ended up deleting everything and starting with a clean slate (except that I forgot to delete those two lines from bashrc).

**Comment by mistydemeo** [comment]
Glad you got it resolved!
