### ISSUE TITLE
Brew doctor fails

### ISSUE THREAD

**Issue by ashkan2200** [Homebrew/homebrew#43768]
I have been trying to run brew doctor but I get this error 
```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Setting DYLD_* vars can break dynamic linking.
Set variables:
    DYLD_LIBRARY_PATH: :/opt/intel/lib/
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:315:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:230:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:227:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:227:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1264:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1262:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1262:in `doctor'
/usr/local/Library/brew.rb:127:in `<main>'
```

brew prune also creates the same type of error as below:

```
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:44:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:338:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:331:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:315:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/prune.rb:15:in `block (2 levels) in prune'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/cmd/prune.rb:12:in `block in prune'
/usr/local/Library/Homebrew/cmd/prune.rb:10:in `each'
/usr/local/Library/Homebrew/cmd/prune.rb:10:in `prune'
/usr/local/Library/brew.rb:127:in `<main>'
```

I have tried resetting git, reinstalling brew and repairing permissions.

I have a macbook pro mid 2012 with OS X Yosemite 10.10.5

Thank you for your help.

**Comment by dunn** [comment]
I think this is the same issue as https://github.com/Homebrew/homebrew/issues/41632#issuecomment-123795602, take a look at the discussion there about setting your locale and let us know if that helps.

**Comment by ashkan2200** [comment]
Thank you for the response. Looks like the issue was the locale. Setting it to UTF-8 fixed the doctor.
