### ISSUE TITLE
brew search is failing under a peculiar case

### ISSUE THREAD

**Issue by rakkesh** [Homebrew/homebrew#44141]
```
~ ❯❯❯ brew search ssl
Error: /usr/local/Library/Aliases/wolfssl:1: syntax error, unexpected ..
../Formula/cyassl.rb
  ^
/usr/local/Library/Aliases/wolfssl:1: unknown regexp options - cyal
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:144:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:44:in `search'
/usr/local/Library/brew.rb:133:in `<main>'
```
__Note__: This seems to happen when searching for a word, which is a substring of filename (and not a symlink) in `/usr/local/Library/Aliases`.

Another interesting thing to note is, git shows that the file was never committed - 
```
/usr/local ❯❯❯ git blame Library/Aliases/wolfssl
00000000 (Not Committed Yet 2015-09-20 00:04:32 +0530 1) ../Formula/cyassl.rb
```

```
~ ❯❯❯ brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 7277b98bcfd1e3f542c282452ac90ca283547e84
Last commit: 82 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.0
CLT: 7.0.0.0.1.1441394355
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
```

**Comment by DomT4** [comment]
If it isn't showing as committed, I'd possibly try:
```
cd $(brew --prefix) && git fetch && git reset --hard origin/master
```
Note that if you have local changes to Homebrew core formulae or code, that will overwrite them.

**Comment by rakkesh** [comment]
I had tried it already, and now again. The file status hasn't changed.

```
/u/local ❯❯❯ cd $(brew --prefix) && git fetch && git reset --hard origin/master
remote: Counting objects: 30, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 30 (delta 24), reused 28 (delta 22), pack-reused 0
Unpacking objects: 100% (30/30), done.
From https://github.com/Homebrew/homebrew
   7277b98..fa84e1e  master     -> origin/master
HEAD is now at fa84e1e flow: update 0.16.0 bottle.
tzudot@MBAR /u/local ❯❯❯ brew search ssl
Error: /usr/local/Library/Aliases/wolfssl:1: syntax error, unexpected ..
../Formula/cyassl.rb
  ^
/usr/local/Library/Aliases/wolfssl:1: unknown regexp options - cyal
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/search.rb:144:in `block in search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `map'
/usr/local/Library/Homebrew/cmd/search.rb:143:in `search_formulae'
/usr/local/Library/Homebrew/cmd/search.rb:44:in `search'
/usr/local/Library/brew.rb:133:in `<main>'
```
Could anyone else verify this issue?

**Comment by DomT4** [comment]
Strange. I couldn't reproduce, no. Can you do a `ls -l $(brew --prefix)/Library/Aliases/wolfssl` just to check it's actually resolving to the intended location?

**Comment by rakkesh** [comment]
```
/usr/local ❯❯❯ ls -l $(brew --prefix)/Library/Aliases/wolfssl
-rw-r--r--@ 1 rakkesh  admin  20 Mar  8  2015 /usr/local/Library/Aliases/wolfssl
```
By the way, `wolfssl` is not a symlink but a file, and also the following,
```
/usr/local ❯❯❯ ls -l $(brew --prefix)/Library/Aliases | grep -v '^l'                                                                                           master ✭
total 984
-rw-r--r--  1 rakkesh  admin  17 Sep 14 00:24 actor-framework
-rw-r--r--@ 1 rakkesh  admin  30 Mar  3  2015 adwaita-icon-theme
-rw-r--r--  1 rakkesh  admin  23 Jun 23 22:14 atlassian-cli
-rw-r--r--@ 1 rakkesh  admin  34 Apr  4 06:59 awsebcli
-rw-r--r--@ 1 rakkesh  admin  21 Apr 21 12:24 blazegraph
-rw-r--r--  1 rakkesh  admin  30 Sep 14 00:24 brightness
-rw-r--r--@ 1 rakkesh  admin  24 Jan 26  2015 cmark
-rw-r--r--@ 1 rakkesh  admin  17 Mar  2  2015 docker-compose
-rw-r--r--  1 rakkesh  admin  16 Sep 14 00:24 golang
-rw-r--r--@ 1 rakkesh  admin  29 May 16 12:25 kotlin
-rw-r--r--@ 1 rakkesh  admin  22 Feb 14  2015 mbedtls
-rw-r--r--  1 rakkesh  admin  20 Jun 18 23:56 mdocml
-rw-r--r--  1 rakkesh  admin  19 Sep 14 00:24 o-caml
-rw-r--r--  1 rakkesh  admin  30 Jun  3 23:48 openscenegraph
-rw-r--r--@ 1 rakkesh  admin  18 May  8 01:31 pcre1
-rw-r--r--  1 rakkesh  admin  23 Jun  5 23:37 rtl-sdr
-rw-r--r--  1 rakkesh  admin  19 Jun  9 18:47 sonarqube
-rw-r--r--@ 1 rakkesh  admin  27 May 18 09:33 speedtest-cli
-rw-r--r--@ 1 rakkesh  admin  20 Mar  8  2015 wolfssl
-rw-r--r--@ 1 rakkesh  admin  24 May 12 22:23 yubico-pam
```

_Note_: content of these files under `Library/Alias` is the relative path to which the actual symlink should point.

**Comment by rakkesh** [comment]
@DomT4 I am not certain what has created this state in my local `Homebrew` repository but it's not worth pursuing. I thank you for your time.

**Comment by DomT4** [comment]
They should resolve like this:
```
lrwxr-xr-x 1 example admin 19 Sep 15 20:34 /usr/local/Library/Aliases/o-caml -> ../Formula/ocaml.rb
```
Feel free to open a new issue if there's anything we can help you with.
