### ISSUE TITLE
python3 - pip3 fails on missing zlib

### ISSUE THREAD

**Issue by sammcj** [Homebrew/homebrew#44242]
```
pip3 install csvtomd
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python3.5/site-packages/pip/download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/usr/local/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/response.py", line 5, in <module>
    import zlib
ImportError: No module named 'zlib'
```

Python 3 installed on OSX 10.11 GM as per:

```
brew install python3
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Downloading https://www.python.org/ftp/python/3.5.0/Python-3.5.0.tar.xz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/python3/3.5.0 --enable-ipv6 --datarootdir=/usr/local/Cellar/python3/3.5.0/share --datadir=/usr/local/Cellar/python3/3.5.0/share --enable-framework=/usr/local/Cellar/python3/3.5.0/Frameworks --without-ensurepip --without-gcc CPPFLAGS=-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/S
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python3/3.5.0
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python3/3.5.0/share/python3
==> Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.3.1.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz
######################################################################## 100.0%
==> Downloading https://pypi.python.org/packages/source/w/wheel/wheel-0.24.0.tar.gz
######################################################################## 100.0%
==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr/local
==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr/local
==> /usr/local/Cellar/python3/3.5.0/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.0/bin --install-lib=/usr/local
==> Caveats
Pip and setuptools have been installed. To update them
  pip3 install --upgrade pip setuptools

You can install Python packages with
  pip3 install <package>

They will install into the site-package directory
  /usr/local/lib/python3.5/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python3` to symlink these to /Applications.
==> Summary
🍺  /usr/local/Cellar/python3/3.5.0: 7606 files, 122M, built in 83 seconds
```

**Comment by tdsmith** [comment]
Thanks for the report. This is tracked in #41085. The workaround is to install the Xcode Command Line Tools with `sudo xcode-select --install` and rebuild python3.

**Comment by sammcj** [comment]
@tdsmith thanks, sorry I didn't spot the other ticket!
