### ISSUE TITLE
Error Installing MAYAVI 

### ISSUE THREAD

**Issue by kamalbowselvam** [Homebrew/homebrew#44277]
I successfully installed VTK, but when I tried 

pip install mayavi 

I get this error 
```
Collecting mayavi
  Using cached mayavi-4.4.3.tar.bz2
Requirement already satisfied (use --upgrade to upgrade): apptools in /usr/local/lib/python2.7/site-packages (from mayavi)
Requirement already satisfied (use --upgrade to upgrade): traits in /usr/local/lib/python2.7/site-packages (from mayavi)
Requirement already satisfied (use --upgrade to upgrade): traitsui in /usr/local/lib/python2.7/site-packages (from mayavi)
Requirement already satisfied (use --upgrade to upgrade): configobj in /usr/local/lib/python2.7/site-packages (from apptools->mayavi)
Requirement already satisfied (use --upgrade to upgrade): pyface in /usr/local/lib/python2.7/site-packages (from traitsui->mayavi)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/site-packages (from configobj->apptools->mayavi)
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/site-packages (from pyface->traitsui->mayavi)
Building wheels for collected packages: mayavi
  Running setup.py bdist_wheel for mayavi
  Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools;__file__='/private/var/folders/t_/x10q3tk92ms64kcjqvxy8s8w0000gn/T/pip-build-sDP8my/mayavi/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /var/folders/t_/x10q3tk92ms64kcjqvxy8s8w0000gn/T/tmpaM9zOwpip-wheel-:
  running bdist_wheel
  running build
  ----------------------------------------------------------------------
  Building TVTK classes...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/t_/x10q3tk92ms64kcjqvxy8s8w0000gn/T/pip-build-sDP8my/mayavi/setup.py", line 471, in <module>
      **config
    File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 175, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/t_/x10q3tk92ms64kcjqvxy8s8w0000gn/T/pip-build-sDP8my/mayavi/setup.py", line 303, in run
      build_tvtk_classes_zip()
    File "/private/var/folders/t_/x10q3tk92ms64kcjqvxy8s8w0000gn/T/pip-build-sDP8my/mayavi/setup.py", line 290, in build_tvtk_classes_zip
      gen_tvtk_classes_zip()
    File "tvtk/setup.py", line 62, in gen_tvtk_classes_zip
      gen.generate_code()
    File "tvtk/code_gen.py", line 101, in generate_code
      self._write_wrapper_class(node, tvtk_name)
    File "tvtk/code_gen.py", line 191, in _write_wrapper_class
      self.wrap_gen.generate_code(node, out)
    File "tvtk/wrapper_gen.py", line 80, in generate_code
      self._gen_methods(node, out)
    File "tvtk/wrapper_gen.py", line 180, in _gen_methods
      self._gen_other_methods(klass, out)
    File "tvtk/wrapper_gen.py", line 764, in _gen_other_methods
      self._write_tvtk_method(klass, out, vtk_meth)
    File "tvtk/wrapper_gen.py", line 1066, in _write_tvtk_method
      sig = self.parser.get_method_signature(vtk_meth)
    File "tvtk/vtk_parser.py", line 311, in get_method_signature
      doc = doc[:doc.find('\n\n')]
  AttributeError: 'NoneType' object has no attribute 'find'

  ----------------------------------------
  Failed building wheel for mayavi
Failed to build mayavi
```

Could someone help, Thanks

**Comment by spatala** [comment]
I have the same error.. Any help or updates!

Thank you.

**Comment by dunn** [comment]
Can either of you try repeating the process outside Homebrew and see if you get the same errors? Thanks!

**Comment by spatala** [comment]
How would I go about doing this? I tried simply removing the following lines from .bash_profile:

# some settings to prefer homebrew paths in case it exists:
if which -s brew ; then
    PATH="/usr/local/bin:/usr/local/sbin:$PATH"
    export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH
fi

I thought this would disable homebrew python and will install mayavi outside homebrew python. I doubt it did this as I got the exact same error.

Thank you.

**Comment by tdsmith** [comment]
I don't think this is a Homebrew bug; let me know if I'm mistaken.

**Comment by opoplawski** [comment]
Mayavi issue - https://github.com/enthought/mayavi/issues/261
