### ISSUE TITLE
Formula renames break `outdated` and `upgrade`?

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/homebrew#44306]
```
tim@rocketman:~$ brew update
Updated Homebrew from 6072e88b to e12b24d8.
...
==> Renamed Formulae
fig -> docker-compose

tim@rocketman:~$ brew outdated
Error: No such file or directory - /usr/local/Cellar/docker-compose

tim@rocketman:~$ brew upgrade
Error: No such file or directory - /usr/local/Cellar/docker-compose

tim@rocketman:~$ ls /usr/local/Cellar/fig
1.3.3 1.4.0 1.4.1
```

What should have happened here? One potential complicating factor is that I haven't run `brew update` in a while since I use `git pull` a lot.

**Comment by DomT4** [comment]
I think you have to `brew migrate` or such? @vladshablinsky

**Comment by mikemcquaid** [comment]
The migrate should have happened automatically unless you've used a manual e.g. `git pull` in the past. If it was reported by `brew updated` it probably should have worked though.

**Comment by khannedy** [comment]
I have the same issue

```
brew migrate fig
==> Migrating fig to docker-compose
==> Unlinking fig
Moving to: /usr/local/Cellar/docker-compose
==> Linking docker-compose
Error: An unexpected error occurred during linking
No such file or directory - /usr/local/Cellar/fig
Error: Error occured while migrating.
No such file or directory - /usr/local/Cellar/fig
Backuping...
```

**Comment by mikemcquaid** [comment]
@khannedy Can you try to run `brew migrate fig --debug --verbose`? Thanks!

**Comment by mikemcquaid** [comment]
@tdsmith Did you or did you not see the:
```
==> Migrating fig to docker-compose
==> Unlinking fig
Moving to: /usr/local/Cellar/docker-compose
==> Linking docker-compose
Updated Homebrew from 6072e88b to ad42fc0c.
```
?

If you `git reset --hard 6072e88b` can you reproduce? (I can't)

**Comment by georgebaev** [comment]
This is the output of the ```brew migrate fig --debug --verbose``` command:
```
13:41:03@mbpro ~$ brew migrate fig --debug --verbose
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/docker-compose.rb
==> Migrating fig to docker-compose
==> Unlinking fig
rm /usr/local/bin/docker-compose
rm /usr/local/bin/fig
rm /usr/local/etc/bash_completion.d/docker-compose
rm /usr/local/share/zsh/site-functions/_docker-compose
Moving to: /usr/local/Cellar/docker-compose
==> Linking docker-compose
ln -s ../../Cellar/docker-compose/1.4.0/etc/bash_completion.d/docker-compose docker-compose
ln -s ../Cellar/docker-compose/1.4.0/bin/docker-compose docker-compose
Error: An unexpected error occurred during linking
No such file or directory - /usr/local/Cellar/fig
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/keg.rb:455:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:289:in `link'
/usr/local/Library/Homebrew/migrator.rb:236:in `link_newname'
/usr/local/Library/Homebrew/migrator.rb:166:in `migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:17:in `block in migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `each'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `migrate'
/usr/local/Library/brew.rb:133:in `<main>'
rm /usr/local/bin/docker-compose
rm /usr/local/etc/bash_completion.d/docker-compose
Error: Error occured while migrating.
No such file or directory - /usr/local/Cellar/fig
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/keg.rb:455:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:289:in `link'
/usr/local/Library/Homebrew/migrator.rb:236:in `link_newname'
/usr/local/Library/Homebrew/migrator.rb:166:in `migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:17:in `block in migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `each'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `migrate'
/usr/local/Library/brew.rb:133:in `<main>'
Backuping...
ln -s ../../Cellar/fig/1.4.0/etc/bash_completion.d/docker-compose docker-compose
ln -s ../Cellar/fig/1.4.0/bin/docker-compose docker-compose
ln -s ../Cellar/fig/1.4.0/bin/fig fig
ln -s ../../../Cellar/fig/1.4.0/share/zsh/site-functions/_docker-compose _docker-compose
```

Hope this helps...

**Comment by jboonstra** [comment]
I get similar output when I try to do the same. I ran `brew up` this morning, then `brew outdated` which asked me to migrate fig.

Note that `/usr/local/Cellar/fig` exists for me both before and after the migrate.

```
joel at oscar in ~
$ ls -ald /usr/local/Cellar/fig
drwxr-xr-x  3 joel  admin  102 Aug 18 15:22 /usr/local/Cellar/fig

joel at oscar in ~
$ brew migrate fig --debug --verbose
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/docker-compose.rb
==> Migrating fig to docker-compose
==> Unlinking fig
rm /usr/local/bin/docker-compose
rm /usr/local/bin/fig
rm /usr/local/etc/bash_completion.d/docker-compose
rm /usr/local/share/zsh/site-functions/_docker-compose
Moving to: /usr/local/Cellar/docker-compose
==> Linking docker-compose
ln -s ../../Cellar/docker-compose/1.4.0/etc/bash_completion.d/docker-compose docker-compose
ln -s ../Cellar/docker-compose/1.4.0/bin/docker-compose docker-compose
Error: An unexpected error occurred during linking
No such file or directory - /usr/local/Cellar/fig
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/keg.rb:455:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:289:in `link'
/usr/local/Library/Homebrew/migrator.rb:236:in `link_newname'
/usr/local/Library/Homebrew/migrator.rb:166:in `migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:17:in `block in migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `each'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `migrate'
/usr/local/Library/brew.rb:133:in `<main>'
rm /usr/local/bin/docker-compose
rm /usr/local/etc/bash_completion.d/docker-compose
Error: Error occured while migrating.
No such file or directory - /usr/local/Cellar/fig
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `realpath'
/usr/local/Library/Homebrew/keg.rb:462:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:543:in `find'
/usr/local/Library/Homebrew/keg.rb:455:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:289:in `link'
/usr/local/Library/Homebrew/migrator.rb:236:in `link_newname'
/usr/local/Library/Homebrew/migrator.rb:166:in `migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:17:in `block in migrate'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `each'
/usr/local/Library/Homebrew/cmd/migrate.rb:8:in `migrate'
/usr/local/Library/brew.rb:133:in `<main>'
Backuping...
ln -s ../../Cellar/fig/1.4.0/etc/bash_completion.d/docker-compose docker-compose
ln -s ../Cellar/fig/1.4.0/bin/docker-compose docker-compose
ln -s ../Cellar/fig/1.4.0/bin/fig fig
ln -s ../../../Cellar/fig/1.4.0/share/zsh/site-functions/_docker-compose _docker-compose

joel at oscar in ~
$ ls -ald /usr/local/Cellar/fig
drwxr-xr-x  3 joel  admin  102 Aug 18 15:22 /usr/local/Cellar/fig
```

**Comment by jboonstra** [comment]
Oh, and in case it's helpful, from my original `brew up`:

```
joel at oscar in ~
$ brew up
Error: Failed to update tap: caskroom/versions
==> Migrating fig to docker-compose
==> Unlinking fig
Moving to: /usr/local/Cellar/docker-compose
==> Linking docker-compose
Error: An unexpected error occurred during linking
No such file or directory - /usr/local/Cellar/fig
Error: Error occured while migrating.
No such file or directory - /usr/local/Cellar/fig
Backuping...
Updated Homebrew from 2b6776e5 to 628bde1c.
==> Updated Formulae
[... snip updated formulae ...]
==> Renamed Formulae
fig -> docker-compose
==> Deleted Formulae
[... snip deleted formulae ...]
```
So it looks like the automatic migration attempt was made but failed (in the same way).

**Comment by mikemcquaid** [comment]
Can I see the output of `ls -lha /usr/local/Cellar/fig /usr/local/Cellar/docker-compose` and your `brew doctor` output?

**Comment by jboonstra** [comment]
```
joel at oscar in ~
$ ls -lha /usr/local/Cellar/fig /usr/local/Cellar/docker-compose
ls: /usr/local/Cellar/docker-compose: No such file or directory
/usr/local/Cellar/fig:
total 0
drwxr-xr-x   3 joel  admin   102B Aug 18 15:22 .
drwxr-xr-x  57 joel  admin   1.9K Sep 25 08:41 ..
drwxr-xr-x  10 joel  admin   340B Sep 25 08:41 1.4.0

joel at oscar in ~
$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    bash-completion
    php56

Warning: Some installed formula are missing dependencies.
You should `brew install` the missing dependencies:

    brew install docker-machine

Run `brew missing` for more details.
```

**Comment by mikemcquaid** [comment]
Aha, can I see the output of `ls -lha /usr/local/Cellar/fig/1.4.0/bin`?

**Comment by jboonstra** [comment]
```
joel at oscar in ~
$ ls -lha /usr/local/Cellar/fig/1.4.0/bin
total 16
drwxr-xr-x   4 joel  admin   136B Aug 18 15:22 .
drwxr-xr-x  10 joel  admin   340B Sep 25 08:41 ..
-r-xr-xr-x   1 joel  admin   227B Aug 18 15:22 docker-compose
lrwxr-xr-x   1 joel  admin    46B Aug 12 01:02 fig -> /usr/local/Cellar/fig/1.4.0/bin/docker-compose
```

**Comment by vladshablinsky** [comment]
Will try to figure out what causes the error ASAP unless it's solved by that time.

**Comment by jboonstra** [comment]
Thanks for taking a look, folks! I'm happy to continue providing information, but I'll be heading offline in about 5 hours so if I stop responding... that's why.

**Comment by mikemcquaid** [comment]
So, the issue is the absolute symlink in `/usr/local/Cellar/fig/1.4.0/bin. Its target is missing after the keg is moved so it fails to be linked to `bin`.

**Comment by jboonstra** [comment]
Aha. I can manually tweak that symlink to be relative and then the migrate should work like a champ. That should get me going again; I can hold off doing so if you'd like me to be a guinea pig to test a fix, though.

**Comment by mikemcquaid** [comment]
Got a simple fix, PR incoming.

**Comment by mikemcquaid** [comment]
@jboonstra A quicker workaround is probably just to `brew uninstall --force fig docker-compose; brew install docker-compose`

**Comment by mikemcquaid** [comment]
https://github.com/Homebrew/homebrew/pull/44329 if you're interested.

**Comment by jboonstra** [comment]
@mikemcquaid - the quicker workaround did the trick, thanks.
