### ISSUE TITLE
Error: invalid attribute: url on upgrade or doctor

### ISSUE THREAD

**Issue by hamid914** [Homebrew/homebrew#44443]
This error is produced when i want to run upgrade or doctor for Homebrew:
````
$ brew upgrade --all
Error: invalid attribute: url (" http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2")
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula.rb:190:in `validate_attributes!'
/usr/local/Library/Homebrew/formula.rb:153:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:70:in `new'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:165:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/formulary.rb:223:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:1008:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:1006:in `map'
/usr/local/Library/Homebrew/formula.rb:1006:in `installed'
/usr/local/Library/Homebrew/cmd/doctor.rb:1018:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:1277:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1275:in `doctor'
/usr/local/Library/brew.rb:133:in `<main>'
````
````
$ brew doctor
as the same as previous error
````
I tried `brew update` several times but there is no difference in that error.
There were no errors in on Sep 28 17:04 IRST 2015 when i executed:
````
$ brew update
$ brew upgrade --all
$ brew doctor
````

**Comment by xu-cheng** [comment]
Please run `brew readall`

**Comment by hamid914** [comment]
This is output of `brew readall`:
````
$ brew readall
Error: problem in /usr/local/Library/Taps/weareleka/homebrew-avr/avr-gcc.rb
invalid attribute: url (" http://ftpmirror.gnu.org/gcc/gcc-4.9.2/gcc-4.9.2.tar.bz2")
Error: problem in /usr/local/Library/Taps/weareleka/homebrew-avr/avr-gcc48.rb
stack level too deep
Error: problem in /usr/local/Library/Taps/weareleka/homebrew-avr/avr-libc48.rb
stack level too deep
````

**Comment by xu-cheng** [comment]
This is from a 3rd party tap. You should contact https://github.com/WeAreLeka/homebrew-avr instead.

**Comment by DomT4** [comment]
The problem is the spacing at the start of the URL & mirror. If they remove the extra spacing, the problem will resolve. You can also do this locally with `brew edit avr-gcc` if upstream are unresponsive.
