### ISSUE TITLE
php70-tidy

### ISSUE THREAD

**Issue by PheRum** [Homebrew/homebrew#44585]
```
mac:~ PheRum$ brew search tidy
homebrew/php/php53-tidy	   homebrew/php/php56-tidy    tidyp
homebrew/php/php54-tidy	   homebrew/php/php70-tidy
homebrew/php/php55-tidy	   tidy-html5 (installed)
```

```
mac:~ PheRum$ brew install php70-tidy
==> Installing php70-tidy from homebrew/homebrew-php
Error: undefined method `<' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formula_support.rb:21:in `valid?'
/usr/local/Library/Homebrew/formula.rb:779:in `keg_only?'
/usr/local/Library/Homebrew/formula_installer.rb:129:in `block in check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:128:in `select'
/usr/local/Library/Homebrew/formula_installer.rb:128:in `check_install_sanity'
/usr/local/Library/Homebrew/formula_installer.rb:106:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:188:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:133:in `<main>'
```

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-php#2434
