### ISSUE TITLE
Cat not working when package is not installed

### ISSUE THREAD

**Issue by egeerardyn** [Homebrew/homebrew#44630]
To inspect what happens if I am to install a certain package, I tried to run `brew cat Caskroom/cask/retro-virtual-machine`, but I get the following error message:
```
Error: undefined method `path' for nil:NilClass
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/cmd/cat.rb:9:in `cat'
/usr/local/Library/brew.rb:133:in `<main>'
```

Similarly, `brew desc <package>` returns nothing if the package is not installed yet.

I think both commands should at least produce some informative output (or maybe I'm doing something wrong: I just installed homebrew yesterday).

**Comment by DomT4** [comment]
> I tried to run brew cat Caskroom/cask/retro-virtual-machine

This likely happens because we only support catting Homebrew formulae. The Caskroom is a separate project with its own team & not bound to support our syntax or terminology choices; we share the `brew` ecosystem and try to make life easier for each other but technically speaking `retro-virtual-machine` isn't a *formula*.

> Similarly, brew desc <package> returns nothing if the package is not installed yet.

This shouldn't be the case:

```
$ brew list | grep a2ps

$ brew desc a2ps
a2ps: Any-to-PostScript filter
```
Does `brew doctor` flag anything?

**Comment by egeerardyn** [comment]
@DomT4 Thanks for the quick response. :+1:

For `a2ps` (which I don't have installed), I do get the same output as you do. I've also tried with a formula from the `homebrew/science` tap and that seems to produce good output for both `cat` and `desc`, so I think your observation makes a lot of sense.

`brew doctor` does flag quite a bit (some things that I have installed manually before) and I also do have MacPorts installed. I don't see any obvious cause in there. If it does help you, this is the log it produces:

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
    /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config
    /opt/local/bin/python-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: You have MacPorts or Fink installed:
  /opt/local/bin/port

This can cause trouble. You don't have to uninstall them, but you may want to
temporarily move them out of the way, e.g.

  sudo mv /opt/local ~/macports

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libarena-4e7c5e5c.dylib
    /usr/local/lib/libaspell.15.1.4.dylib
    /usr/local/lib/libbeid.2.7.4.dylib
    /usr/local/lib/libbeidcardlayer.4.0.7.dylib
    /usr/local/lib/libbeidcommon.1.0.0.dylib
    /usr/local/lib/libbeidcommon.4.0.7.dylib
    /usr/local/lib/libbeiddialogsQT.4.0.7.dylib
    /usr/local/lib/libbeidgui.1.5.0.dylib
    /usr/local/lib/libbeidlibjni.2.7.2.dylib
    /usr/local/lib/libbeidlibopensc.2.2.0.dylib
    /usr/local/lib/libbeidlibopenscinternal.2.2.0.dylib
    /usr/local/lib/libbeidpkcs11.4.0.7.dylib
    /usr/local/lib/libflate-4e7c5e5c.dylib
    /usr/local/lib/libflavours.dylib
    /usr/local/lib/libflavoursui.dylib
    /usr/local/lib/libfmt_macros-4e7c5e5c.dylib
    /usr/local/lib/libfreehdl-cdfggen.0.dylib
    /usr/local/lib/libfreehdl-cdfggen.dylib
    /usr/local/lib/libfreehdl-fire.0.dylib
    /usr/local/lib/libfreehdl-fire.dylib
    /usr/local/lib/libfreehdl-kernel.0.dylib
    /usr/local/lib/libfreehdl-kernel.dylib
    /usr/local/lib/libfreehdl-std.0.dylib
    /usr/local/lib/libfreehdl-std.dylib
    /usr/local/lib/libfreehdl-vaul.0.dylib
    /usr/local/lib/libfreehdl-vaul.dylib
    /usr/local/lib/libgetopts-4e7c5e5c.dylib
    /usr/local/lib/libgraphviz-4e7c5e5c.dylib
    /usr/local/lib/liblog-4e7c5e5c.dylib
    /usr/local/lib/libpspell.15.1.4.dylib
    /usr/local/lib/libqt-mt.3.3.8.dylib
    /usr/local/lib/librbml-4e7c5e5c.dylib
    /usr/local/lib/librustc-4e7c5e5c.dylib
    /usr/local/lib/librustc_back-4e7c5e5c.dylib
    /usr/local/lib/librustc_borrowck-4e7c5e5c.dylib
    /usr/local/lib/librustc_driver-4e7c5e5c.dylib
    /usr/local/lib/librustc_llvm-4e7c5e5c.dylib
    /usr/local/lib/librustc_privacy-4e7c5e5c.dylib
    /usr/local/lib/librustc_resolve-4e7c5e5c.dylib
    /usr/local/lib/librustc_trans-4e7c5e5c.dylib
    /usr/local/lib/librustc_typeck-4e7c5e5c.dylib
    /usr/local/lib/librustdoc-4e7c5e5c.dylib
    /usr/local/lib/libserialize-4e7c5e5c.dylib
    /usr/local/lib/libserialport.0.dylib
    /usr/local/lib/libsigrok.1.dylib
    /usr/local/lib/libsigrokdecode.1.dylib
    /usr/local/lib/libstd-4e7c5e5c.dylib
    /usr/local/lib/libsyntax-4e7c5e5c.dylib
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libterm-4e7c5e5c.dylib
    /usr/local/lib/libtest-4e7c5e5c.dylib
    /usr/local/lib/libtk8.6.dylib
    /usr/local/lib/libxerces-c-3.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/aspell.h
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/freehdl/cdfggen-chunk.h
    /usr/local/include/freehdl/fire-chunk.h
    /usr/local/include/freehdl/fire-types.h
    /usr/local/include/freehdl/fire.h
    /usr/local/include/freehdl/FlexLexer.h
    /usr/local/include/freehdl/kernel.h
    /usr/local/include/freehdl/std.h
    /usr/local/include/freehdl/tree-supp.h
    /usr/local/include/freehdl/vaul-chunk.h
    /usr/local/include/freehdl/vaul-creator-base.h
    /usr/local/include/freehdl/vaul-dfile.h
    /usr/local/include/freehdl/vaul-dunit.h
    /usr/local/include/freehdl/vaul-dynarray.h
    /usr/local/include/freehdl/vaul-errors.h
    /usr/local/include/freehdl/vaul-lexer.h
    /usr/local/include/freehdl/vaul-list.h
    /usr/local/include/freehdl/vaul-mempool.h
    /usr/local/include/freehdl/vaul-parser.h
    /usr/local/include/freehdl/vaul-pool.h
    /usr/local/include/freehdl/vaul-printer.h
    /usr/local/include/freehdl/vaul-ref.h
    /usr/local/include/freehdl/vaul-types.h
    /usr/local/include/freehdl/vaul-util.h
    /usr/local/include/freehdl/vaul.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/iverilog/_pli_types.h
    /usr/local/include/iverilog/acc_user.h
    /usr/local/include/iverilog/ivl_target.h
    /usr/local/include/iverilog/veriuser.h
    /usr/local/include/iverilog/vpi_user.h
    /usr/local/include/libserialport.h
    /usr/local/include/libsigrok/libsigrok.h
    /usr/local/include/libsigrok/proto.h
    /usr/local/include/libsigrok/version.h
    /usr/local/include/libsigrokdecode/libsigrokdecode.h
    /usr/local/include/libsigrokdecode/version.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/pspell/pspell.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
    /usr/local/lib/libaspell.la
    /usr/local/lib/libfreehdl-cdfggen.la
    /usr/local/lib/libfreehdl-fire.la
    /usr/local/lib/libfreehdl-kernel.la
    /usr/local/lib/libfreehdl-std.la
    /usr/local/lib/libfreehdl-vaul.la
    /usr/local/lib/libpspell.la
    /usr/local/lib/libserialport.la
    /usr/local/lib/libsigrok.la
    /usr/local/lib/libsigrokdecode.la

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/freehdl.pc
    /usr/local/lib/pkgconfig/libserialport.pc
    /usr/local/lib/pkgconfig/libsigrok.pc
    /usr/local/lib/pkgconfig/libsigrokdecode.pc
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libfreehdl-cdfggen.a
    /usr/local/lib/libfreehdl-fire.a
    /usr/local/lib/libfreehdl-kernel.a
    /usr/local/lib/libfreehdl-std.a
    /usr/local/lib/libfreehdl-vaul.a
    /usr/local/lib/libserialport.a
    /usr/local/lib/libsigrok.a
    /usr/local/lib/libsigrokdecode.a
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a
    /usr/local/lib/libveriuser.a
    /usr/local/lib/libvpi.a
```

In any case: I think the problem is probably my inexperience. Feel free to close this if that is the case.

**Comment by DomT4** [comment]
If you see any build problems check out the warnings about unexpected dylibs/headers/etc, but I wouldn't worry too much about anything on that list unless you do hit failure.

Let us know if you have any further questions. Happy to help :smiley:
