### ISSUE TITLE
Error: uninitialized constant Formulary

### ISSUE THREAD

**Issue by ivanzolotov** [Homebrew/homebrew#44660]
When I try to update homebrew:

```
Mac-mini:~ ivanzolotov$ brew update
Checking out files: 100% (2997/2997), done.
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:260:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'
```

**Comment by ivanzolotov** [comment]
Sorry, guys. It's already there: https://github.com/Homebrew/homebrew/issues/42553
