### ISSUE TITLE
brew update returns error -9806

### ISSUE THREAD

**Issue by hylinlin** [Homebrew/homebrew#45084]
Ran `brew update` and got this error
```
brew update    
                                                                                                                                                                                            
Error: uninitialized constant Formulary::HOMEBREW_CORE_FORMULA_REGEX

Please report this bug:
    https://git.io/brew-troubleshooting

/usr/local/Library/Homebrew/formulary.rb:265:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
```

Ran `brew update` again per instructions on the [troubleshooting page](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting) and got this error

```
brew update

fatal: unable to access 'https://github.com/Homebrew/homebrew/': SSLRead() return error -9806

Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master
```

**Comment by DomT4** [comment]
What's OS X version are you running? Does the error reproduce if you try `brew update` again?

**Comment by hylinlin** [comment]
I'm running OS X Yosemite (10.10.5). Just ran `brew update` again and am no longer seeing errors.
