### ISSUE TITLE
my error when I modified the attica package and then brew update

### ISSUE THREAD

**Issue by tingyu66** [Homebrew/homebrew#45428]
I first ran `brew install attica`, then I found that the link in the attica formula is not working, so I made some modification to get it to work. Since then, every time I `brew update` or `brew doctor`, it gave me an error as below:

```
Error: /usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:5: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:7: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Library/Taps/adymo/homebrew-kde/attica.rb:9: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/formulary.rb:214:in `from_rack'
/usr/local/Library/Homebrew/cmd/uninstall.rb:57:in `rm_pin'
/usr/local/Library/Homebrew/cmd/uninstall.rb:16:in `block (2 levels) in uninstall'
/usr/local/Library/Homebrew/keg.rb:230:in `block in lock'
/usr/local/Library/Homebrew/formula_lock.rb:29:in `with_lock'
/usr/local/Library/Homebrew/keg.rb:226:in `lock'
/usr/local/Library/Homebrew/cmd/uninstall.rb:11:in `block in uninstall'
/usr/local/Library/Homebrew/cmd/uninstall.rb:10:in `each'
/usr/local/Library/Homebrew/cmd/uninstall.rb:10:in `uninstall'
/usr/local/Library/brew.rb:146:in `<main>'
```

```
attica.rb: needs merge
attica.rb: needs merge
attica.rb: unmerged (e28400c1e33ca206e7d8c9ffe11b032afd9a6908)
attica.rb: unmerged (26c7d0039f8007a67d594fcc7aa59d90822693cf)
attica.rb: unmerged (fb1f909f95d56d4778316dd8ae5c64b3397730f6)
fatal: git-write-tree: error building trees
Cannot save the current index state
Error: Failed to update tap: adymo/kde
```

So I just deleted the attica package by running `brew uninstall attica`, however, I still get an error when `brew update`. Can someone lend some help? Thank you.

**Comment by tingyu66** [comment]
I just deleted the tap that made this error. `brew untap adymo/kde`.
