### ISSUE TITLE
Elasticsearch 2.0.0 does not start

### ISSUE THREAD

**Issue by radar** [Homebrew/homebrew#45593]
I've installed elasticsearch 2.0.0 today with `brew install elasticsearch`. I have previously installed 1.7.2 using the same method. I have run both `brew update` and `brew doctor`.

OS X 10.11.1, if that matters.

When running `elasticsearch`, this happens:

```
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: sun.misc.Launcher$AppClassLoader@33909752
	at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:210)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:127)
	at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:86)
	at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:514)
	at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:413)
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:216)
	at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:151)
	at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
	at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:266)
	at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:968)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:672)
	at org.joda.time.format.DateTimeFormatter.printTo(DateTimeFormatter.java:560)
	at org.joda.time.format.DateTimeFormatter.print(DateTimeFormatter.java:644)
	at org.elasticsearch.Build.<clinit>(Build.java:51)
	at org.elasticsearch.node.Node.<init>(Node.java:135)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
[2015-11-02 10:47:59,881][INFO ][node                     ] [Invisible Girl] version[2.0.0], pid[2542], build[de54438/2015-10-22T08:09:48Z]
[2015-11-02 10:47:59,882][INFO ][node                     ] [Invisible Girl] initializing ...
Exception in thread "main" java.lang.IllegalStateException: failed to load bundle [] due to jar hell
Likely root cause: java.security.AccessControlException: access denied ("java.io.FilePermission" "/usr/local/Cellar/elasticsearch/2.0.0/libexec/antlr-runtime-3.5.jar" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.util.zip.ZipFile.<init>(ZipFile.java:210)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:173)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:340)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:113)
	at org.elasticsearch.node.Node.<init>(Node.java:144)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

I also have another Macbook Pro here, a new one, running 10.11 which also has the same issue.

**Comment by mikemcquaid** [comment]
Reproduced locally. Reverted in 2289405. That should fix the issue for now while we work out how to update safely. Sorry!

**Comment by radar** [comment]
No worries :) Thanks for the quick response.

**Comment by ilkkao** [comment]
Thanks, noticed the same problem.

Another minor issue is that `brew info` says that elasticsearch can be started manually with

`elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml`

This will produce an error:

`es.config is no longer supported. elasticsearch.yml must be placed in the config directory and cannot be renamed`

I interpret the error so that `--config` parameter is not supported anymore. I think `brew info` output should be updated.

**Comment by jasontedor** [comment]
Relates elastic/elasticsearch#14424.
