### ISSUE TITLE
EmacsRequirement error on brew update

### ISSUE THREAD

**Issue by daanemanz** [Homebrew/homebrew#45616]
When running `brew update` I'm encountering the following error:
```
Error: Specify a version for EmacsRequirement
```

Version:
```
$ brew --version
0.9.5 (git revision dc5a; last commit 2015-10-22)
```

I'm seeing this both on Travis CI and on my local machine.

**Comment by bfontaine** [comment]
What does `brew update --verbose` say?

**Comment by daanemanz** [comment]
@bfontaine nothing but the cloning of repositories; it just hangs there:

```
$ brew update --verbose
==> git symbolic-ref --short HEAD 2>/dev/null
master
==> git rev-parse -q --verify HEAD
dc5a7e797bc1d6411699090fef6d86d7292a94cb
git config core.autocrlf false
git pull --ff --no-rebase origin refs/heads/master:refs/remotes/origin/master
remote: Counting objects: 3896, done.
remote: Compressing objects: 100% (1107/1107), done.
remote: Total 3896 (delta 3069), reused 3600 (delta 2777), pack-reused 0
Receiving objects: 100% (3896/3896), 537.78 KiB | 0 bytes/s, done.
Resolving deltas: 100% (3069/3069), completed with 501 local objects.
From https://github.com/Homebrew/homebrew
   dc5a7e7..18c483f  master     -> origin/master
Updating dc5a7e7..18c483f
Fast-forward
 .travis.yml                                        |   5 +-
<snippety snip>
...
</snip>
 520 files changed, 3529 insertions(+), 1696 deletions(-)
 create mode 100644 Library/Formula/carina.rb
 create mode 100644 Library/Formula/dfmt.rb
 create mode 100644 Library/Formula/gdub.rb
 create mode 100644 Library/Formula/glslang.rb
 create mode 100644 Library/Formula/libmill.rb
 create mode 100644 Library/Formula/librest.rb
 create mode 100644 Library/Formula/libsoundio.rb
 create mode 100644 Library/Formula/libstatgrab.rb
 create mode 100644 Library/Formula/mailhog.rb
 create mode 100644 Library/Formula/ne.rb
 create mode 100644 Library/Formula/otto.rb
 create mode 100644 Library/Formula/shairport-sync.rb
 create mode 100644 Library/Formula/sqliteodbc.rb
 create mode 100644 Library/Formula/swagger-codegen.rb
 create mode 100644 Library/Formula/tailor.rb
 create mode 100644 Library/Formula/whatmp3.rb
 delete mode 100644 Library/Formula/whereami.rb
 create mode 100644 Library/Formula/xalan-c.rb
 create mode 100644 Library/Formula/ykneomgr.rb
==> git rev-parse -q --verify HEAD
18c483f1a1fd5eb4d7257590ebe0
```

Debug output:
```
7.30s$ brew update --debug
Updated Homebrew from dc5a7e79 to 18c483f1.
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/abcde.rb
/usr/local/Library/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Library/Formula/abcde.rb
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/aces_container.rb
/usr/local/Library/brew.rb (Formulary::FormulaContentsLoader): loading /usr/local/Library/Formula/aces_container.rb
/usr/local/Library/brew.rb (Formulary::FromPathLoader): loading /usr/local/Library/Formula/agda.rb
Error: Specify a version for EmacsRequirement
/usr/local/Library/Homebrew/requirements/emacs_requirement.rb:7:in `initialize'
/usr/local/Library/Homebrew/dependency_collector.rb:116:in `new'
/usr/local/Library/Homebrew/dependency_collector.rb:116:in `parse_symbol_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:73:in `parse_spec'
/usr/local/Library/Homebrew/dependency_collector.rb:61:in `build'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `block in fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:48:in `fetch'
/usr/local/Library/Homebrew/dependency_collector.rb:38:in `add'
/usr/local/Library/Homebrew/software_spec.rb:151:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1750:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1750:in `each'
/usr/local/Library/Homebrew/formula.rb:1750:in `depends_on'
/usr/local/Library/Formula/agda.rb:47:in `<class:Agda>'
/usr/local/Library/Formula/agda.rb:3:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:205:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:309:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:295:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:295:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:47:in `update'
/usr/local/Library/brew.rb:146:in `<main>'
The
```

**Comment by daanemanz** [comment]
Running `brew update` a second time seems to "fix" the issue.

**Comment by bfontaine** [comment]
cc @dunn the Emacs guy :smile:

**Comment by mistydemeo** [comment]
It looks like the bug is coming from the agda formula, but it doesn't use `EmacsRequirement`.

**Comment by bfontaine** [comment]
@mistydemeo `agda` depends on `:emacs` which itself uses `EmacsRequirement`: https://github.com/Homebrew/homebrew/blob/8c6777b2b8e847d5f2b447eae532fa8ecffa6467/Library/Homebrew/dependency_collector.rb#L116

**Comment by jlaxson** [comment]
The new agda as of this weekend changed from depending on the package to using the EmacsRequirement without a version.  The issue is that if your existing homebrew install is old enough to not support the versionless EmacsRequirement, it crashes during update.

**Comment by jlaxson** [comment]
c.f. https://github.com/Homebrew/homebrew/commit/3fff92687c2d7ef50d5274ee2ee244d30fe38e68

**Comment by daanemanz** [comment]
@jlaxson Is there a way to get this working without running `brew update` twice? E.g. Travis CI errors out on the first `brew update` so is there a workaround?

**Comment by bfontaine** [comment]
@daanemanz If you don’t care about the new/modified formulae you can run `cd $(brew --repo) && git pull` instead of `brew update`.

**Comment by ejona86** [comment]
@daanemanz, you can do `brew update || brew update`

**Comment by daanemanz** [comment]
@ejona86 thanks, that worked as well.

**Comment by 2rs2ts** [comment]
This affects me as well, awaiting a true fix. :)

**Comment by carlos-aguayo** [comment]
This just happened to me as well.

**Comment by longkt90** [comment]
@daanemanz :+1: Running brew update a second time seems to "fix" the issue.

**Comment by mikemcquaid** [comment]
CC @xu-cheng as we hoped the updater test would stop issues like this :sob:

**Comment by mikemcquaid** [comment]
FWIW I now think the solution is: `brew update` shouldn't load Ruby and/or Formula code.

**Comment by kathyonu** [comment]
Just ran into this on the `brew doctor` command used after the `brew update` run the first time. Searching the error, I arrived here and after I run `brew update` the second time, it now responds __Already up-to-date.__  Running `brew doctor` the second time now responds with the familiar __Your system is ready to brew.__ Thank you StackOverflow contributors, in my case, 2nd running of both commands did the trick.

**Comment by xu-cheng** [comment]
@mikemcquaid `brew update-test` can only catch problem when it's caused in single PR. While here, it's caused by multiple commits. 

We have to load formula code in order to support version check and formula rename. Short term, I think we should rescue anything whenever we load formula inside `update`.

**Comment by mikemcquaid** [comment]
> We have to load formula code in order to support version check and formula rename. Short term, I think we should rescue anything whenever we load formula inside update.

That doesn't mean that code needs to be in `brew update`. It could (and probably should) be printed from after the new code has been loaded.

**Comment by mikemcquaid** [comment]
To be more clear: I think we should have `brew update` just do the actual Git update and then another process handle all the formulae loading. `brew update` could be written in shell or Ruby in that case but shell seems like a better fit to me so e.g. in future we can use it to update people and ensure a particular Ruby version is installed and setup.

**Comment by diogoguimaraes** [comment]
Having this issue again when building with travis ci:
```Bash
$ brew update
Updated Homebrew from 91b03473 to 749bb020.
Error: Specify a version for EmacsRequirement
The command "brew update" failed and exited with 1 during .
```

Any ideas on why it's happening again?

**Comment by xu-cheng** [comment]
@diogoguimaraes  should fix now. Can you try to run Travis CI build again?

**Comment by diogoguimaraes** [comment]
@xu-cheng fixed.
Thanks!
