### ISSUE TITLE
a bug for Mac OS X EI Captain(10.11.1)

### ISSUE THREAD

**Issue by zyyw** [Homebrew/homebrew#45653]
After issuing "brew doctor", I was prompt with something like these:
```
Error: /usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:94: syntax error, unexpected <<, expecting keyword_end
<<<<<<< Updated upstream
  ^
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:100: syntax error, unexpected ===, expecting keyword_end
=======
   ^
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:103: syntax error, unexpected >>, expecting keyword_end
>>>>>>> Stashed changes
  ^
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/formulary.rb:22:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:22:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:79:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:70:in `klass'
/usr/local/Library/Homebrew/formulary.rb:66:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:153:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:176:in `factory'
/usr/local/Library/Homebrew/formulary.rb:194:in `from_rack'
/usr/local/Library/Homebrew/formula.rb:861:in `block in installed'
/usr/local/Library/Homebrew/formula.rb:859:in `map'
/usr/local/Library/Homebrew/formula.rb:859:in `installed'
/usr/local/Library/Homebrew/cmd/doctor.rb:1022:in `check_missing_deps'
/usr/local/Library/Homebrew/cmd/doctor.rb:1284:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1282:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1282:in `doctor'
/usr/local/Library/brew.rb:127:in `<main>'
```

**Comment by bfontaine** [comment]
@zyyw I edited your post to put the code between backquotes:

    ```
    your code
    ```

This prevents GitHub from interpreting it as Markdown.

**Comment by bfontaine** [comment]
Did you edit `opencv.rb`? If not you can run the following:

```
cd /usr/local/Library/Taps/homebrew/homebrew-science
git fetch
git reset --hard origin/master
```

**Comment by DomT4** [comment]
Can't reproduce this locally, and the `Stashed changes` line suggest the formula was modified locally. Baptiste's instructions should sort it out.

**Comment by zyyw** [comment]
@bfontaine It fixed the error by issuing these commands you provided. And homebrew is back now. Thanks. 
I didn't edit opencv.rb file. But I upgraded my OS from Yosemite to EI Captain.
