### ISSUE TITLE
Weird Error when installing libxslt

### ISSUE THREAD

**Issue by CamJN** [Homebrew/homebrew#46105]
```
brew install libxslt
==> Downloading https://homebrew.bintray.com/bottles/libxslt-1.1.28_1.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libxslt-1.1.28_1.el_capitan.bottle.tar.gz
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getusersitepackages'
==> Caveats
To allow the nokogiri gem to link against this libxslt run:
  gem install nokogiri -- --with-xslt-dir=/usr/local/opt/libxslt

This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libxslt/lib
    CPPFLAGS: -I/usr/local/opt/libxslt/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/libxslt/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/libxslt.pth
  mkdir -p 
  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> homebrew.pth
==> Summary
🍷  /usr/local/Cellar/libxslt/1.1.28_1: 145 files, 3.3M
brew gist-logs libxslt
Error: No logs.
brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: d4040592fa7ab61020a1535f2f2a8609e03d334e
Last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.1-x86_64
Xcode: 7.1.1
CLT: N/A
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /Users/camdennarzt/Developer/Python/bedrock/venv/bin/python
Ruby: /Users/camdennarzt/.rbenv/shims/ruby => /Users/camdennarzt/.rbenv/versions/2.2.3/bin/ruby
Java: N/A

**Comment by apjanke** [comment]
That's weird. Looks like an error [detecting the Python `site-packages` location](https://github.com/Homebrew/homebrew/blob/5a2292ff22d08b6c8b7c06bb15d6812577c977d2/Library/Homebrew/language/python.rb#L43-L45).

Possibly something to do with the custom Python environment or installation it's picking up? Does it work if you deactivate that venv and run with the plain system or Homebrew `python`?

```
Python: /Users/camdennarzt/Developer/Python/bedrock/venv/bin/python
Ruby: /Users/camdennarzt/.rbenv/shims/ruby => /Users/camdennarzt/.rbenv/versions/2.2.3/bin/ruby
```

**Comment by CamJN** [comment]
Yeah it installs fine without the venv.

**Comment by mikemcquaid** [comment]
If the `venv` fixes it I'll close this and recommend you don't use one when using Homebrew.
