### ISSUE TITLE
`brew info --json=v1 $pkg` broken when $pkg not installed

### ISSUE THREAD

**Issue by staticfloat** [Homebrew/homebrew#46463]
When running `brew info --json=v1 $pkg`, valid json is not returned if the package is not installed:

```
$ brew info --json=v1 par
Error: No such file or directory - /usr/local/Cellar/par
```

Whereas if I omit the `--json=v1` argument I get:

```
$ brew info par
par: stable 1.52 (bottled)
Paragraph reflow for email
http://www.nicemice.net/par/
Conflicts with: rancid
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/par.rb
```

Is this intended?  If so, what is the best (machine-parseable) way to get information about formulae from `brew`?

**Comment by staticfloat** [comment]
It looks like this is happening due to 24763f01873fd7c55bdad674114c47a1151e0714; `to_hash` is calling `outdated?` which expects at least one version of the formula to be installed:

```
$ brew info -d --json=v1 par
/usr/local/Library/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Formula/par.rb
Error: No such file or directory - /usr/local/Cellar/par
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `foreach'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:425:in `children'
/usr/local/Library/Homebrew/extend/pathname.rb:281:in `subdirs'
/usr/local/Library/Homebrew/formula.rb:941:in `outdated_versions'
/usr/local/Library/Homebrew/formula.rb:963:in `outdated?'
/usr/local/Library/Homebrew/formula.rb:1245:in `to_hash'
/usr/local/Library/Homebrew/cmd/info.rb:57:in `map'
/usr/local/Library/Homebrew/cmd/info.rb:57:in `print_json'
/usr/local/Library/Homebrew/cmd/info.rb:14:in `info'
/usr/local/Library/brew.rb:146:in `<main>'
```

**Comment by mistydemeo** [comment]
I don't think this should be a tough fix - the method just needs to make sure it exits early if `rack.exist?` returns false.

**Comment by mikemcquaid** [comment]
Thanks for the report @staticfloat and sorry for the bug. Looks like @xu-cheng has a fix that will be merged soon.

**Comment by staticfloat** [comment]
That was an incredibly fast fix, thanks guys!
