### ISSUE TITLE
Error: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by jyyen** [Homebrew/homebrew#46558]
when I typed
    brew doctor
in the terminal, **brew** asked me to report the bug, and showed a bunch of error messages:

```
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
    /usr/local/Library/Homebrew/extend/pathname.rb:296:in `resolved_path_exists?'
    /usr/local/Library/Homebrew/cmd/doctor.rb:232:in `block (2 levels) in check_for_broken_symlinks'
   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
   /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
    /usr/local/Library/Homebrew/cmd/doctor.rb:231:in `block in check_for_broken_symlinks'
    /usr/local/Library/Homebrew/cmd/doctor.rb:229:in `each'
    /usr/local/Library/Homebrew/cmd/doctor.rb:229:in `check_for_broken_symlinks'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1314:in `block in doctor'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1312:in `each'
    /usr/local/Library/Homebrew/cmd/doctor.rb:1312:in `doctor'
    /usr/local/Library/brew.rb:146:in `<main>'
```

**Comment by UniqMartin** [comment]
Can you try if the suggestions made in #44744 help in your case?

**Comment by DomT4** [comment]
Yeah, track the above issue. I'll try and set aside some time to test fixes for this soon.
