### ISSUE TITLE
 undefined method `desc' for Opencv:Class

### ISSUE THREAD

**Issue by michaelkamprath** [Homebrew/homebrew#46758]
Got this error message when running the command `brew install tesseract cmake opencv log4cplus`:

```
Error: undefined method `desc' for Opencv:Class
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:2:in `<class:Opencv>'
/usr/local/Library/Taps/homebrew/homebrew-science/opencv.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/formulary.rb:65:in `klass'
/usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:198:in `factory'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:28:in `install'
/usr/local/Library/brew.rb:136:in `<main>'
```

**Comment by bfontaine** [comment]
Please run `brew update` and try again.

**Comment by michaelkamprath** [comment]
I guess I might have a permissions problem. What's the best way to clean install?

```
$ brew update
error: unable to unlink old '.gitignore' (Permission denied)
error: unable to create file .travis.yml (Permission denied)
error: unable to unlink old '.yardopts' (Permission denied)
error: unable to unlink old 'CODEOFCONDUCT.md' (Permission denied)
error: unable to unlink old 'CONTRIBUTING.md' (Permission denied)
error: unable to unlink old 'LICENSE.txt' (Permission denied)
error: unable to unlink old 'README.md' (Permission denied)
error: unable to unlink old 'SUPPORTERS.md' (Permission denied)
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```

**Comment by DomT4** [comment]
```
sudo chown -R $(whoami):admin /usr/local
```
For now. We're working on a less blunt solution in https://github.com/Homebrew/homebrew/pull/45934.

**Comment by michaelkamprath** [comment]
Yeah, that did the trick. Thanks!
