### ISSUE TITLE
Undefined method 'dev_tools_path' when installing old version of Node

### ISSUE THREAD

**Issue by tuupola** [Homebrew/homebrew#46902]
I am building an Mountain Lion Vagrant box for legacy application. Box has command line tools installed but no XCode. Homebrew is installed and working. I can for example install latest node.

```shell
$ brew install node
...
$ node --version
v5.2.0
```

However when trying to install older version 0.8.x version of node it errors with `undefined method 'dev_tools_path' for OS::Mac:Module`.

```shell
$ brew update
Already up-to-date.
$ brew install homebrew/versions/node08 
==> Installing node08 from homebrew/versions
==> Downloading https://nodejs.org/dist/v0.8.28/node-v0.8.28.tar.gz
Already downloaded: /Library/Caches/Homebrew/node08-0.8.28.tar.gz
Error: undefined method `dev_tools_path' for OS::Mac:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/homebrew/homebrew-versions/node08.rb:42:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `install'
/usr/local/Library/Homebrew/formula.rb:922:in `brew'
/usr/local/Library/Homebrew/formula.rb:1516:in `stage'
/usr/local/Library/Homebrew/resource.rb:91:in `unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1507:in `stage'
/usr/local/Library/Homebrew/formula.rb:918:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177
```

```shell
$ brew irb
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
>> MacOS::Xcode.installed?
=> false
>> MacOS::CLT.installed?
=> true
>> MacOS.dev_tools_path
NoMethodError: undefined method `dev_tools_path' for OS::Mac:Module
	from (irb):3
>> MacOS::CLT.usr_dev_tools?
NoMethodError: undefined method `usr_dev_tools?' for OS::Mac::CLT:Module
	from (irb):4
```

Wild guess is that `MacOS.dev_tools_path` has been removed at some point but [recipe still uses it](https://github.com/Homebrew/homebrew-versions/blob/master/node08.rb#L42).

**Comment by tuupola** [comment]
Following workaround seems to fix the problem:

```shell
$ xcode-select -switch /usr/bin
$ brew install homebrew/versions/node08
```

**Comment by mikemcquaid** [comment]
Thanks for the report, should be fixed.
