### ISSUE TITLE
Mapnik2 binary hardcodes icu4c

### ISSUE THREAD

**Issue by Fonsan** [Homebrew/homebrew#46993]
Hi

The formula is broken since icu4c has been updated. From what I can tell it is the "precompiled" version that hardcodes a old version of icu4c. When installing and passing a parameter that requires compiling from source it detects the new icu4c version and works

``` $ brew install mapnik2
==> Installing mapnik2 from homebrew/versions
==> Downloading https://homebrew.bintray.com/bottles-versions/mapnik2-2.2.0.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/mapnik2-2.2.0.yosemite.bottle.tar.gz
==> Pouring mapnik2-2.2.0.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/mapnik2/2.2.0: 382 files, 46M```

``` $ python world.py && open world_style.png
Traceback (most recent call last):
  File "world.py", line 5, in <module>
    import mapnik
  File "/usr/local/lib/python2.7/site-packages/mapnik/__init__.py", line 69, in <module>
    from _mapnik import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/mapnik/_mapnik.so, 2): Library not loaded: /usr/local/opt/icu4c/lib/libicuuc.55.dylib
  Referenced from: /usr/local/Cellar/mapnik2/2.2.0/lib/libmapnik.dylib
  Reason: image not found```

But If i run it 

```brew install -vd mapnik2 --with-cairo
lots of output
```

Thus triggering a compile from source

Python can successfully load mapnik

**Comment by dunn** [comment]
This issue was moved to Homebrew/homebrew-versions#1079
