### ISSUE TITLE
Error: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by miguelorcinha** [Homebrew/homebrew#47212]
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 89d672b9818fa1e22ffbf9408e3d1ee55fe7de50
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: 8-core 64-bit haswell
OS X: 10.11.2-x86_64
Xcode: 7.2
CLT: 7.2.0.0.1.1447826929
Clang: 7.0 build 700
X11: 2.7.8 => /opt/X11
System Ruby: 2.0.0-p645
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_45
```

```
Error: invalid byte sequence in US-ASCII
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `=~'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:45:in `chop_basename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:341:in `plus'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:334:in `+'
/usr/local/Library/Homebrew/extend/pathname.rb:296:in `resolved_path_exists?'
/usr/local/Library/Homebrew/cmd/doctor.rb:232:in `block (2 levels) in check_for_broken_symlinks'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/cmd/doctor.rb:231:in `block in check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:229:in `check_for_broken_symlinks'
/usr/local/Library/Homebrew/cmd/doctor.rb:1301:in `block in doctor'
/usr/local/Library/Homebrew/cmd/doctor.rb:1299:in `each'
/usr/local/Library/Homebrew/cmd/doctor.rb:1299:in `doctor'
/usr/local/Library/brew.rb:143:in `<main>'
```

**Comment by UniqMartin** [comment]
Thank you for the report! Do the solutions in #44744 work?

**Comment by DomT4** [comment]
This should be fixed now.

**Comment by miguelorcinha** [comment]
yes, it worked, thank you.
