### ISSUE TITLE
Possible regression of 39950

### ISSUE THREAD

**Issue by imrook** [Homebrew/homebrew#47533]
It appears that commit 7916ef26c137ab23849c7a4bed0f216ee8361d71 has caused a regression of https://github.com/Homebrew/homebrew/issues/39950 that was fixed in 10103ca25f03be844454bf37835b20ad5e281a26. A `brew info git-annex` gives the following output:
~~~
Error: undefined method `fails_with' for Language::Haskell::Cabal:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/language/haskell.rb:7:in `included'
/usr/local/Library/Formula/git-annex.rb:4:in `include'
/usr/local/Library/Formula/git-annex.rb:4:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/cmd/info.rb:35:in `print_info'
/usr/local/Library/brew.rb:69:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `each_with_index'
/usr/local/Library/Homebrew/cmd/info.rb:29:in `print_info'
/usr/local/Library/Homebrew/cmd/info.rb:18:in `info'
/usr/local/Library/brew.rb:143:in `send'
/usr/local/Library/brew.rb:143
~~~
After `git revert 7916ef26c137ab23849c7a4bed0f216ee8361d71`, the output is as follows:

~~~
git-annex: stable 5.20151218, HEAD
Manage files with git without checking in file contents
https://git-annex.branchable.com/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/git-annex.rb
==> Dependencies
Build: ghc ✘, cabal-install ✘, pkg-config ✔
Required: gsasl ✔, libidn ✔, gnutls ✔, quvi ✔
==> Options
--with-git-union-merge
        Build the git-union-merge tool
--HEAD
        Install HEAD version
~~~

**Comment by mistydemeo** [comment]
I see the issue, will fix.

**Comment by mistydemeo** [comment]
Should be fixed.

**Comment by imrook** [comment]
Confirmed this fix works for me. Thanks Misty!

**Comment by mistydemeo** [comment]
No problem, glad it works for you!

**Comment by mietek** [comment]
Thanks for catching this.
