### ISSUE TITLE
Error: undefined method `strip_prefix' for "homebrew-cask":String

### ISSUE THREAD

**Issue by jadams103** [Homebrew/homebrew#47684]
Running 'brew update' without sudo errored with the following (I know I shouldn't need or want to use sudo but...something changed):   

```
$brew update
/usr/local/.git: Permission denied
Error: Failure while executing: git init
```

So...being in a hurry....sudo to the rescue (right...)

```
$sudo brew update
Password:
Initialized empty Git repository in /usr/local/.git/
remote: Counting objects: 321953, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 321953 (delta 26), reused 0 (delta 0), pack-reused 321908
Receiving objects: 100% (321953/321953), 64.67 MiB | 1.05 MiB/s, done.
Resolving deltas: 100% (240237/240237), done.
From https://github.com/Homebrew/homebrew
 * [new branch]      master     -> origin/master
HEAD is now at 5745ef3 doctor: add explicit anaconda warning
Error: undefined method `strip_prefix' for "homebrew-cask":String
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/tap.rb:29:in `fetch'
/usr/local/Library/Homebrew/formula.rb:146:in `initialize'
/usr/local/Library/Homebrew/formulary.rb:72:in `new'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:39:in `block (2 levels) in update'
/usr/local/Library/Homebrew/extend/pathname.rb:278:in `block in cd'
/usr/local/Library/Homebrew/extend/pathname.rb:278:in `chdir'
/usr/local/Library/Homebrew/extend/pathname.rb:278:in `cd'
/usr/local/Library/Homebrew/cmd/update.rb:31:in `block in update'
/usr/local/Library/Homebrew/cmd/tap.rb:60:in `block (2 levels) in each_tap'
/usr/local/Library/Homebrew/cmd/tap.rb:59:in `each'
/usr/local/Library/Homebrew/cmd/tap.rb:59:in `block in each_tap'
/usr/local/Library/Homebrew/cmd/tap.rb:58:in `each'
/usr/local/Library/Homebrew/cmd/tap.rb:58:in `each_tap'
/usr/local/Library/Homebrew/cmd/update.rb:30:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
```

Information on my running environment:

```
$/usr/sbin/system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,3
      Processor Name: Intel Core i7
      Processor Speed: 2.5 GHz
      Number of Processors: 1
      Total Number of Cores: 4
      L2 Cache (per Core): 256 KB
      L3 Cache: 6 MB
      Memory: 16 GB
      Boot ROM Version: MBP112.0138.B16
      SMC Version (system): 2.19f12
      Serial Number (system):
      Hardware UUID: B2DCEFF5-C426-5AD3-8438-xxxxxxxxxxxxxxx
```

```
$sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1021
```

**Comment by mistydemeo** [comment]
Most likely fixed by 6f7f407410cd6028295b936bb3b847d7ce567cdc.
