### ISSUE TITLE
duplicity ssh backend scheme not supported

### ISSUE THREAD

**Issue by mszymczak** [Homebrew/homebrew#47725]
Hey,

yesterday I did update duplicity from `v0.6.26` to `v0.7.06` using `brew upgrade` command and my backup script stopped to work.

I'm trying to debug this and I'm getting:
```
maciek@empro ~ $ /usr/local/bin/duplicity collection-status ssh://maciek@host:22/path/blah/ -v9
Using archive dir: /Users/maciek/.cache/duplicity/923e779c80ec3c719a582a07bbe9be0f
Using backup name: 923e779c80ec3c719a582a07bbe9be0f
Import of duplicity.backends.azurebackend Succeeded
Import of duplicity.backends.b2backend Succeeded
Import of duplicity.backends.botobackend Succeeded
Import of duplicity.backends.cfbackend Succeeded
Import of duplicity.backends.copycombackend Succeeded
Import of duplicity.backends.dpbxbackend Succeeded
Import of duplicity.backends.gdocsbackend Succeeded
Import of duplicity.backends.giobackend Succeeded
Import of duplicity.backends.hsibackend Succeeded
Import of duplicity.backends.hubicbackend Succeeded
Import of duplicity.backends.imapbackend Succeeded
Import of duplicity.backends.lftpbackend Succeeded
Import of duplicity.backends.localbackend Succeeded
Import of duplicity.backends.megabackend Succeeded
Import of duplicity.backends.multibackend Succeeded
Import of duplicity.backends.ncftpbackend Succeeded
Import of duplicity.backends.onedrivebackend Succeeded
Import of duplicity.backends.par2backend Succeeded
Import of duplicity.backends.pydrivebackend Succeeded
Import of duplicity.backends.rsyncbackend Succeeded
Import of duplicity.backends.ssh_paramiko_backend Succeeded
Import of duplicity.backends.ssh_pexpect_backend Succeeded
Import of duplicity.backends.swiftbackend Succeeded
Import of duplicity.backends.sxbackend Succeeded
Import of duplicity.backends.tahoebackend Succeeded
Import of duplicity.backends.webdavbackend Succeeded
Using temporary directory /var/folders/65/t_3xpz3n25j6sb1d_kh1jqmm0000gn/T/duplicity-fGM87r-tempdir
User error detail: Traceback (most recent call last):
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1532, in <module>
    with_tempdir(main)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1526, in with_tempdir
    fn()
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1364, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/commandline.py", line 1108, in ProcessCommandLine
    globals.backend = backend.get_backend(args[0])
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/backend.py", line 204, in get_backend_object
    raise UnsupportedBackendScheme(url_string)
UnsupportedBackendScheme: scheme not supported in url: ssh://maciek@host:22/path/blah/

UnsupportedBackendScheme: scheme not supported in url: ssh://maciek@host:22/path/blah/
maciek@empro ~ $
```

Version:

```
maciek@empro ~ $ brew info duplicity
duplicity: stable 0.7.06 (bottled)
Bandwidth-efficient encrypted backup
http://www.nongnu.org/duplicity/
/usr/local/Cellar/duplicity/0.7.06_1 (3,769 files, 37.3M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/duplicity.rb
==> Dependencies
Required: librsync ✔, openssl ✔
Optional: par2 ✘
==> Options
--universal
	Build a universal binary
--with-par2
	Build with par2 support
maciek@empro ~ $ ls -l /usr/local/bin/duplicity
lrwxr-xr-x  1 maciek  admin  42 Jan  4 22:55 /usr/local/bin/duplicity -> ../Cellar/duplicity/0.7.06_1/bin/duplicity
maciek@empro ~ $ /usr/local/bin/duplicity --version
duplicity 0.7.06
maciek@empro ~ $
```

OS:
```
maciek@empro ~ $ sw_vers -productVersion
10.11.3
```

I also tried to check `collection-status` using `scp://` and I'm getting "empty collection" in this path (which is not true, collection exists).

Please advise.

Thanks,

**Comment by dunn** [comment]
Can you try building Duplicity outside of Homebrew, to see if it might be an upstream issue?

**Comment by mszymczak** [comment]
Hey I've done build from sources (`duplicity-0.7.06` and python module `lockfile-0.12.2`) and the problem still exists.


```
User error detail: Traceback (most recent call last):
  File "/usr/local/bin/duplicity", line 1532, in <module>
    with_tempdir(main)
  File "/usr/local/bin/duplicity", line 1526, in with_tempdir
    fn()
  File "/usr/local/bin/duplicity", line 1364, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/duplicity/commandline.py", line 1108, in ProcessCommandLine
    globals.backend = backend.get_backend(args[0])
  File "/usr/local/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/lib/python2.7/site-packages/duplicity/backend.py", line 204, in get_backend_object
    raise UnsupportedBackendScheme(url_string)
UnsupportedBackendScheme: scheme not supported in url: ssh://maciek@host:22/path/blah/
```

**Comment by dunn** [comment]
Thank you! That suggests it's a problem that should be reported to the Duplicity developers.  If you could do that we'd be very grateful.

**Comment by DomT4** [comment]
Does this still reproduce?

**Comment by DomT4** [comment]
Closing as dead but please let us know if this issue does still persist, Thanks!

**Comment by bramanis** [comment]
I'm having the same problem without homebrew, with Duplicity 0.7.07.1
