### ISSUE TITLE
undefined method `option_names' for #<Dependency: "cd-discid" []>

### ISSUE THREAD

**Issue by Jokcy** [Homebrew/homebrew#48058]
```
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: c7ea17f92ca507eafec0a7b4c95176f47cf9ea5b
Last commit: 7 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.5-x86_64
Xcode: 7.0.1
CLT: N/A
Clang: 7.0 build 700
X11: N/A
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby
Java: 1.8.0_40
```
run brew update

```
Error: undefined method `option_names' for #<Dependency: "cd-discid" []>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:188:in `add_dep_option'
/usr/local/Library/Homebrew/software_spec.rb:156:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1865:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1865:in `each'
/usr/local/Library/Homebrew/formula.rb:1865:in `depends_on'
/usr/local/Library/Formula/abcde.rb:31:in `<class:Abcde>'
/usr/local/Library/Formula/abcde.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:173:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:159:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:140:in `<main>'
```

**Comment by DomT4** [comment]
Try running `brew update` again, I suspect it'll self-resolve. You'll run into less of these things with more regular `brew update`s; even if you don't upgrade it's important to keep the repo up-to-date.

**Comment by Jokcy** [comment]
@DomT4 THX for answering me, after I try `brew doctor` it seems OK for me now

**Comment by dunn** [comment]
Glad to hear it! Let us know if you run into further issues.
