### ISSUE TITLE
brew install failed on mac os EI Capitan

### ISSUE THREAD

**Issue by kevin4044** [Homebrew/homebrew#48227]
```text
WeRoadShowDevs-MacBook-Pro-3:~ weroadshowdev$ brew install neovim/neovim/neovimError:     undefined method `desc' for Neovim:Class
    Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
    /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb:2:in `<class:Neovim>'
    /usr/local/Library/Taps/neovim/homebrew-neovim/Formula/neovim.rb:1:in `<top (required)>'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    /usr/local/Library/Homebrew/formulary.rb:65:in `klass'
    /usr/local/Library/Homebrew/formulary.rb:50:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:185:in `get_formula'
    /usr/local/Library/Homebrew/formulary.rb:198:in `factory'
    /usr/local/Library/Homebrew/extend/ARGV.rb:12:in `block in formulae'
    /usr/local/Library/Homebrew/extend/ARGV.rb:12:in `map'
    /usr/local/Library/Homebrew/extend/ARGV.rb:12:in `formulae'
    /usr/local/Library/Homebrew/cmd/install.rb:27:in `install'
    /usr/local/Library/brew.rb:131:in `<main>'
```

**Comment by dunn** [comment]
First guess is that you haven't run `brew update` in a while.  Do that and try again, please!

**Comment by kevin4044** [comment]
@dunn thx for your advise , it works, my bad, T.T

**Comment by kevin4044** [comment]
@dunn who is responsible to close this issue? you or me ?

**Comment by DomT4** [comment]
Feel free to close Issues you create when they are resolved if you wish to :)
