### ISSUE TITLE
undefined method `option_names' for #<Dependency: "cd-discid" []>

### ISSUE THREAD

**Issue by BillZong** [Homebrew/homebrew#48272]
I've got an error when I'm trying to update my homebrew.
My mac version is V10.10.5, and I'm using bash V4.3. Here is my error log:
```
ZongBilldeMac-mini:~ bill$ brew update
Checking out files: 100% (2964/2964), done.
Error: undefined method `option_names' for #<Dependency: "cd-discid" []>
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:188:in `add_dep_option'
/usr/local/Library/Homebrew/software_spec.rb:156:in `depends_on'
/usr/local/Library/Homebrew/formula.rb:1850:in `block in depends_on'
/usr/local/Library/Homebrew/formula.rb:1850:in `each'
/usr/local/Library/Homebrew/formula.rb:1850:in `depends_on'
/usr/local/Library/Formula/abcde.rb:31:in `<class:Abcde>'
/usr/local/Library/Formula/abcde.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:205:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:127:in `<main>'
ZongBilldeMac-mini:~ bill$ ls -la /usr/local/
total 104
drwxrwxr-x   23 root  admin    782  1 20 09:41 .
drwxr-xr-x@  12 root  wheel    408  1 11 18:11 ..
(more ignored...)
```

**Comment by DomT4** [comment]
Please `brew update` and try again. This sort of error seems to be a reproduction of an old issue for users who haven't updated for a while.

**Comment by BillZong** [comment]
Done, and thanks very much. Close the issue now!
