### ISSUE TITLE
major python problems

### ISSUE THREAD

**Issue by ryanGT** [Homebrew/homebrew#48301]
I sent this to the mailing list (librelist.com) but I get the impression that list isn't active.  I hope this is the right place to ask for help.

I recently did a brew update and then tried to upgrade sympy via pip.  Now my python installation is majorly broken.  Almost anything python related that I try to do results in this traceback:

rkrauss|krauss_syllabi$ pip install hashlib

ERROR:root:code for hash md5 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type md5

ERROR:root:code for hash sha1 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha1

ERROR:root:code for hash sha224 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha224

ERROR:root:code for hash sha256 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha256

ERROR:root:code for hash sha384 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha384

ERROR:root:code for hash sha512 was not found.

Traceback (most recent call last):

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>

    globals()[__func_name] = __get_hash(__func_name)

  File "/usr/local/Cellar/python/2.7.10_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor

    raise ValueError('unsupported hash type ' + name)

ValueError: unsupported hash type sha512

Traceback (most recent call last):

  File "/usr/local/bin/pip", line 7, in <module>

    from pip import main

  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>

    from pip.vcs import git, mercurial, subversion, bazaar  # noqa

  File "/usr/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 10, in <module>

    from pip.download import path_to_url

  File "/usr/local/lib/python2.7/site-packages/pip/download.py", line 38, in <module>

    from pip._vendor import requests, six

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>

    from . import utils

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 26, in <module>

    from .compat import parse_http_list as _parse_list_header

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>

    from .packages import chardet

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>

    from . import urllib3

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 10, in <module>

    from .connectionpool import (

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 31, in <module>

    from .connection import (

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 45, in <module>

    from .util.ssl_ import (

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>

    from .ssl_ import (

  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 2, in <module>

    from hashlib import md5, sha1, sha256

ImportError: cannot import name md5

Trying to run brew update now results in this:

error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libcurl.pc' (Permission denied)

error: unable to unlink old 'Library/ENV/pkgconfig/10.11/libxml-2.0.pc' (Permission denied)

error: unable to unlink old 'Library/ENV/pkgconfig/10.11/sqlite3.pc' (Permission denied)

Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master

I went in and changed the owner of all .pc files in that folder to me and even did a chmod 777.  I still get that error with brew update.

Here is the output of brew doctor.  I don't think these are critical:

rkrauss|10.11[master*]$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    docbook-xsl
    unison240

Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.

How do I get python working again?

Thanks,

Ryan

**Comment by tdsmith** [comment]
You will need to:

* reset permissions on /usr/local with e.g. `sudo chown -R $USER /usr/local`
* install the Xcode Command-Line Tools with `xcode-select --install`
* run `brew update`
* run `brew reinstall python`

**Comment by ryanGT** [comment]
Thanks for the help.  brew update now seems to finish cleanly.

Having trouble with brew reinstall python:

rkrauss|usr$ brew reinstall python
==> Reinstalling python with --universal
Error: No available formula with the name "homebrew/dupes/tcl-tk" 
Please tap it and then try again: brew tap homebrew/dupes

**Comment by tdsmith** [comment]
This is good advice:

> Please tap it and then try again: brew tap homebrew/dupes

**Comment by ryanGT** [comment]
I didn't realize that was a verbatim command. Trying that now.

**Comment by ryanGT** [comment]
Things seem to be fixed.  Thank you very much.
