### ISSUE TITLE
postgresql test

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew#48596]
Fails:
```
==> brew test --verbose postgresql
==> FAILED
Testing postgresql
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160129-45417-1pjzmcp.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Formula/postgresql.rb --verbose
==> /usr/local/Cellar/postgresql/9.5.0/bin/initdb /private/tmp/postgresql20160129-45418-16ljr1w/test
The files belonging to this database system will be owned by user "brew".
This user must also own the server process.

initdb: file "/usr/local/share/postgresql/postgres.bki" does not exist
This might mean you have a corrupted installation or identified
the wrong directory with the invocation option -L.
Error: postgresql: failed
Failed executing: /usr/local/Cellar/postgresql/9.5.0/bin/initdb /private/tmp/postgresql20160129-45418-16ljr1w/test
/usr/local/Library/Homebrew/formula.rb:1477:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1414:in `open'
/usr/local/Library/Homebrew/formula.rb:1414:in `system'
/usr/local/Library/Formula/postgresql.rb:133:in `block in <class:Postgresql>'
/usr/local/Library/Homebrew/formula.rb:1323:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:17:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1319:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'
```

**Comment by DomT4** [comment]
False positive: https://github.com/Homebrew/homebrew/pull/48598
