### ISSUE TITLE
Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master

### ISSUE THREAD

**Issue by pascalandy** [Homebrew/homebrew#49006]
Hey guys, if this can help.

Cheers!

```
Error: Failure while executing: git pull --quiet origin refs/heads/master:refs/remotes/origin/master
Pascals-MacBook-Pro:~ pascalandy$ sudo brew update
Password:
Error: undefined method `new' for Patch:Module
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1910:in `each'
/usr/local/Library/Homebrew/formula.rb:1910:in `patch'
/usr/local/Library/Formula/a2ps.rb:19:in `<class:A2ps>'
/usr/local/Library/Formula/a2ps.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:124:in `<main>'
```

**Comment by DomT4** [comment]
Please `brew update` again and see if it persists. I suspect it won't.

**Comment by pascalandy** [comment]
I confirm. It's now running smoothly.

Thanks
Pascal

**Comment by jmevalentin** [comment]
@DomT4, I have a similar error which is persisting after several tries: I get the following:

`Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master
`

It's always after these last few lines appear:
>Library/Formula/utf8proc.rb
> Library/Formula/vamp-plugin-sdk.rb
> Library/Formula/vapoursynth.rb
>Library/F

Thoughts?

**Comment by jmevalentin** [comment]
The suggestion by @kevin under the solution here helped:  http://stackoverflow.com/questions/14113427/brew-update-failed

**Comment by DomT4** [comment]
Aye. In those situations, if you don't care about keeping the changes the solution is almost universally:
```shell
git fetch && git reset --hard origin/master
```
