### ISSUE TITLE
[pkg-config] Error: can't convert Fixnum into String

### ISSUE THREAD

**Issue by jeroenooms** [Homebrew/homebrew#49045]
Trying to brew openssl on osx 10.6.8 fails with the following error. Any guess to what the issue is?

```
Note: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
==> Installing dependencies for openssl: pkg-config, makedepend
==> Installing openssl dependency: pkg-config
==> Downloading http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
==> Downloading from https://pkg-config.freedesktop.org/releases/pkg-config-0.29.tar.gz
Error: can't convert Fixnum into String
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:987:in `fu_get_gid'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:926:in `chown'
/private/tmp/homebrew/Library/Homebrew/extend/fileutils.rb:26:in `mktemp'
/private/tmp/homebrew/Library/Homebrew/resource.rb:88:in `unpack'
/private/tmp/homebrew/Library/Homebrew/resource.rb:81:in `stage'
/private/tmp/homebrew/Library/Homebrew/formula.rb:1536:in `stage'
/private/tmp/homebrew/Library/Homebrew/formula.rb:922:in `brew'
/private/tmp/homebrew/Library/Homebrew/build.rb:108:in `install'
/private/tmp/homebrew/Library/Homebrew/build.rb:177
```

**Comment by DomT4** [comment]
My money is on this being related to https://github.com/Homebrew/homebrew/commit/3446b57db2d886b89a103e0ea4cd2087a04a7595 being merged 5 days ago.

I'll ask Misty if she's aware of any obvious issues there'd be here that wouldn't have been discovered by CI testing Ruby 1.8.x when this passed as a PR.

**Comment by UniqMartin** [comment]
@jeroenooms Copying from the output in your message, note that:

```
Note: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
```

Nonetheless, I would like to help, but I can't, because I don't know what version of Ruby you are running (and I don't know all ancient OS X releases by heart). Quoting again from the output in your message:

```
Please report this bug:
    https://git.io/brew-troubleshooting
```

That link contains instructions on what to do. It also kindly asks you to provide certain information you haven't provided, namely the output of `brew config` and `brew doctor`.

**Comment by jeroenooms** [comment]
Right, here you go
```
mac:homebrew mac$ ./bin/brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /private/tmp/homebrew
HOMEBREW_REPOSITORY: /private/tmp/homebrew
HOMEBREW_CELLAR: /private/tmp/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: single-core 64-bit nehalem
OS X: 10.6.7-i386
Xcode: 4.2
CLT: N/A
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.7.8 => /opt/X11
System Ruby: 1.8.7-p174
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_24-b07-334
```

And

```
mac:homebrew mac$ ./bin/brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The system curl on 10.8 and below is often incapable of supporting
modern secure connections & will fail on fetching formulae.

We recommend you:
  brew install curl

Warning: An outdated version of Git was detected in your PATH.
Git 1.7.10 or newer is required to perform checkouts over HTTPS from GitHub.
Please upgrade: brew install git

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/fakemysql.h
    /usr/local/include/fakepq.h
    /usr/local/include/fakesql.h
    /usr/local/include/itcl.h
    /usr/local/include/itcl2TclOO.h
    /usr/local/include/itclDecls.h
    /usr/local/include/itclInt.h
    /usr/local/include/itclIntDecls.h
    /usr/local/include/itclMigrate2TclCore.h
    /usr/local/include/itclTclIntStubsFcn.h
    /usr/local/include/mysqlStubs.h
    /usr/local/include/odbcStubs.h
    /usr/local/include/pqStubs.h
    /usr/local/include/tcl.h
    /usr/local/include/tclDecls.h
    /usr/local/include/tclOO.h
    /usr/local/include/tclOODecls.h
    /usr/local/include/tclPlatDecls.h
    /usr/local/include/tclThread.h
    /usr/local/include/tclTomMath.h
    /usr/local/include/tclTomMathDecls.h
    /usr/local/include/tdbc.h
    /usr/local/include/tdbcDecls.h
    /usr/local/include/tdbcInt.h
    /usr/local/include/tk.h
    /usr/local/include/tkDecls.h
    /usr/local/include/tkPlatDecls.h

Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .pc files:
    /usr/local/lib/pkgconfig/tcl.pc
    /usr/local/lib/pkgconfig/tk.pc

Warning: Unbrewed static libraries were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected static libraries:
    /usr/local/lib/libtclstub8.6.a
    /usr/local/lib/libtkstub8.6.a

Warning: You are using OS X 10.6.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.

Warning: Your Homebrew is not installed to /usr/local
You can install Homebrew anywhere you want, but some brews may only build
correctly if you install in /usr/local. Sorry!

Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
    echo 'export PATH="/private/tmp/homebrew/bin:$PATH"' >> ~/.bash_profile
```

**Comment by jeroenooms** [comment]
Actually this problem seems to have disappeared after I upgraded the build server from 10.6.7 to 10.6.8.

**Comment by UniqMartin** [comment]
That's good news! I think it's fair of us to assume that people run the latest bugfix release, even if they decide to rely on an outdated and unsupported OS X release, right? Just out of curiosity, what is the output of `brew config` after the update (I suspect the Ruby version has changed)?

**Comment by jeroenooms** [comment]
Yes I'm not sure why this vm was still on 10.6.7, sorry for that. Here is the new `brew config` output:

```
mac:Desktop mac$ /tmp/homebrew/bin/brew config
HOMEBREW_VERSION: 0.9.5
ORIGIN: (none)
HEAD: (none)
Last commit: never
HOMEBREW_PREFIX: /private/tmp/homebrew
HOMEBREW_REPOSITORY: /private/tmp/homebrew
HOMEBREW_CELLAR: /private/tmp/homebrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: single-core 64-bit nehalem
OS X: 10.6.8-i386
Xcode: 4.2
CLT: N/A
LLVM-GCC: build 2336
Clang: 3.0 build 211
X11: 2.7.8 => /opt/X11
System Ruby: 1.8.7-p358
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: 1.6.0_65-b14-462
```

**Comment by UniqMartin** [comment]
Thanks for the quick response and the confirmation! It is Ruby 1.8.7-p174 (on 10.6.7) vs. Ruby 1.8.7-p358 (on 10.6.8) and I'm pretty certain the former has some bug in (or lacking implementation of) the problematic `chown` method that we don't want to work around in Homebrew. Closing as resolved.

**Comment by jeroenooms** [comment]
Awesome thanks.

**Comment by ilovezfs** [comment]
@UniqMartin It was a one line change in the ruby method `fu_get_gid`, and is a one line fix in master, if we want to patch it:
https://github.com/Homebrew/homebrew/issues/49348#issuecomment-186500526

PR or leave it broken for <=10.6.7?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew/pull/49369/files
