### ISSUE TITLE
radare2 failed to build on 10.11.3

### ISSUE THREAD

**Issue by inokii** [Homebrew/homebrew#49102]
`brew install radare2` worked without issue, however, `brew install --HEAD radare2` failed. HEAD built without issue a few days ago.

[`brew gist-logs radare2` output](https://gist.github.com/987f81e7641bb29e4983)

`brew install --HEAD radare2` console output:
```
==> Installing dependencies for radare2: yara
==> Installing radare2 dependency: yara
==> Downloading https://homebrew.bintray.com/bottles/yara-3.4.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring yara-3.4.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/yara/3.4.0: 37 files, 1M
==> Installing radare2

==> Cloning https://github.com/radare/radare2.git
Updating /Library/Caches/Homebrew/radare2--git
==> Checking out branch master
==> ./configure --prefix=/usr/local/Cellar/radare2/HEAD --with-openssl
==> make CS_PATCHES=0
==> make install
Error: radare2 does not define resource "extras"
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/software_spec.rb:106:in `block in resource'
/usr/local/Library/Homebrew/software_spec.rb:106:in `fetch'
/usr/local/Library/Homebrew/software_spec.rb:106:in `resource'
/usr/local/Library/Homebrew/formula.rb:302:in `resource'
/usr/local/Library/Formula/radare2.rb:51:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:926:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1546:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:92:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:35:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1536:in `stage'
/usr/local/Library/Homebrew/formula.rb:922:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'
```

**Comment by ilovezfs** [comment]
This fixes it:
```
diff --git a/Library/Formula/radare2.rb b/Library/Formula/radare2.rb
index 691986c..8672753 100644
--- a/Library/Formula/radare2.rb
+++ b/Library/Formula/radare2.rb
@@ -29,6 +29,11 @@ class Radare2 < Formula
     resource "bindings" do
       url "https://github.com/radare/radare2-bindings.git"
     end
+
+    resource "extras" do
+      url "https://github.com/radare/radare2-extras.git"
+    end
+
   end
 
   depends_on "pkg-config" => :build
bash-3.2$
```

**Comment by DomT4** [comment]
Closing in favour of #49134.
