### ISSUE TITLE
Emacs installation fails after prompting for interactive mode

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [Homebrew/homebrew#49234]
See the following:

```
> brew install emacs --HEAD -use-git-head --with-cocoa --with-gnutls --with-rsvg --with-imagemagick -srgb

==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Library/Caches/Homebrew/emacs--git
==> Checking out branch master
Reinitialized existing Git repository in /private/tmp/emacs20160216-66957-lr47cx/.git/
==> Entering interactive mode
Type `exit' to return and finalize the installation
Install to this prefix: /usr/local/Cellar/emacs/HEAD
This directory is now a git repo. Make your changes and then use:
  git diff | pbcopy
to copy the diff to the clipboard.
amelio% exit
Error: Empty installation
/usr/local/Library/Homebrew/formula_installer.rb:579:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:219:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:215:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
```

[Here](https://gist.github.com/amelio-vazquez-reina/1db60384b2cf313f8a7a) is my `brew doctor`.

**Comment by dunn** [comment]
You're using some invalid options:
- `-use-git-head` doesn't exist anymore
- `--with-rsvg` should be `--with-librsvg`
- `-srgb` doesn't exist

Use `brew info emacs` to see the current set of options.  Try re-running without the invalid ones and let us know if you still have trouble!

**Comment by amelio-vazquez-reina** [comment]
Thanks @dunn This is what I got:

```
$ brew install emacs --HEAD --with-cocoa --with-gnutls --with-glib --with-librsvg --with-imagemagick
==> Cloning https://github.com/emacs-mirror/emacs.git
Updating /Library/Caches/Homebrew/emacs--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/emacs/HEAD --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs/HEAD/share/info/emacs --wi
Last 15 lines from /Users/avazquez/Library/Logs/Homebrew/emacs/02.configure:
checking whether malloc is Doug Lea style... no
checking for getpagesize... yes
checking for working mmap... yes
checking for main in -lXbsd... no
checking for pthread library... none needed
checking for RSVG... yes
checking for IMAGEMAGICK... yes
checking for MagickExportImagePixels... yes
checking for MagickMergeImageLayers... yes
checking for MagickAutoOrientImage... yes
checking for lgetfilecon in -lselinux... no
checking for LIBGNUTLS... yes
checking for LIBGNUTLS3... yes
configure: error: '--with-file-notification=gfile' is not supported in NextStep builds.
Consider kqueue instead.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Emacs installation fails after prompting for interactive mode https://github.com/Homebrew/homebrew/issues/49234
emacs can be linked against XQuartz or Brew font-config https://github.com/Homebrew/homebrew/issues/37803
Emacs Failed to Build on OS X Yosemite v10.10.5 With Options Specified in Issue Body https://github.com/Homebrew/homebrew/issues/43619
```

**Comment by amelio-vazquez-reina** [comment]
@dunn  It looks like I only run into that problem above if I use `--with-lib`.

**Comment by dunn** [comment]
Gotcha, good to know that `--with-cocoa` and `--with-glib` are incompatible.

**Comment by ilovezfs** [comment]
http://i.imgur.com/QkPSlQk.jpg

@amelio-vazquez-reina @dunn The problem was `-use-git-head`

Using  `-` instead of `--` is not supported. It thinks you asked for interactive mode since `-i` is a shortcut for that.

**Comment by dunn** [comment]
Yeah, that's what I figured.

Closing as resolved.  Let us know if you have further questions!

**Comment by chetstone** [comment]
@amelio-vazquez-reina what did you do to get rid of the error 
```
configure: error: '--with-file-notification=gfile' is not supported in NextStep builds.
```
??
I'm getting that with `brew reinstall emacs --HEAD --with-cocoa`

adding various combinations of other options such as `--with-gnutls --with-glib --with-librsvg --with-imagemagick` doesn't help.

I wonder if there's a problem with reinstalling over my old HEAD install, perhaps I need to completely delete it first? When I run the command I get this:

```
$ brew reinstall emacs --HEAD --with-cocoa
==> Reinstalling emacs with --use-git-head, --srgb, --with-glib, --with-cocoa
```

**Comment by dunn** [comment]
@chetstone Yeah, `brew reinstall` preserves the options you originally used, so it's still using `--with-glib` there.

**Comment by amelio-vazquez-reina** [comment]
@ilovezfs Thanks, but I am confused. When I do:

> brew info

I get the options below, which don't include `--use-git-head`. Does that mean the option is not supported anymore? What is the difference between using it and using `--HEAD`?

```
$ brew info emacs
emacs: stable 24.5 (bottled), devel 25.0.91, HEAD
GNU Emacs text editor
https://www.gnu.org/software/emacs/
Not installed
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/emacs.rb
==> Dependencies
Build: xz ✔, pkg-config ✔
Optional: d-bus ✘, gnutls ✔, librsvg ✔, imagemagick ✔, mailutils ✘, glib ✔
==> Options
--with-cocoa
        Build a Cocoa version of emacs
--with-ctags
        Don't remove the ctags executable that emacs provides
--with-d-bus
        Build with d-bus support
--with-glib
        Build with glib support
--with-gnutls
        Build with gnutls support
--with-imagemagick
        Build with imagemagick support
--with-librsvg
        Build with librsvg support
--with-mailutils
        Build with mailutils support
--with-x11
        Build with x11 support
--without-libxml2
        Don't build with libxml2 support
--devel
        Install development version 25.0.91
--HEAD
        Install HEAD version
==> Caveats
To have launchd start emacs at login:
  ln -sfv /usr/local/opt/emacs/*.plist ~/Library/LaunchAgents
Then to load emacs now:
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.emacs.plist

WARNING: launchctl will fail when run under tmux.
```

**Comment by dunn** [comment]
@amelio-vazquez-reina correct, `--use-git-head` isn't a valid option anymore; you want to use `--HEAD` instead.
