### ISSUE TITLE
curl build issue

### ISSUE THREAD

**Issue by GregFleming** [Homebrew/homebrew#49348]
# Please follow the general troubleshooting steps first:

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports:

```
==> Installing dependencies for curl: openssl
==> Installing curl dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2f.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2f.tar.gz
Error: can't convert Fixnum into String
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:987:in `fu_get_gid'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb:926:in `chown'
/usr/local/Library/Homebrew/extend/fileutils.rb:26:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1542:in `stage'
/usr/local/Library/Homebrew/formula.rb:928:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177
```

`brew gist-logs <formula>`
```
Error: getaddrinfo: nodename nor servname provided, or not known
Please report this bug:
    https://git.io/brew-troubleshooting
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:93:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:542:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:1035:in `request'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:139:in `post'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:96:in `create_gist'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:35:in `gistify_logs'
/usr/local/Library/Homebrew/cmd/gist-logs.rb:164:in `gist_logs'
/usr/local/Library/brew.rb:83:in `send'
/usr/local/Library/brew.rb:83
```

### Feature/Formula Requests:

**Please note by far the quickest way to get a new feature or formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

### Report a security vulnerability

* [Email security@brew.sh](mailto:security@brew.sh) (a private mailing list) with detailed reproduction instructions optionally using [our PGP key](https://keybase.io/homebrew/key.asc)

**Comment by ilovezfs** [comment]
What OS X is this? brew config output would be helpful.

**Comment by ilovezfs** [comment]
BTW, you can try this change:

```
Josephs-MacBook-Pro:local joe$ git diff
diff --git a/Library/Homebrew/extend/fileutils.rb b/Library/Homebrew/extend/fileutils.rb
index 9717c69..1704187 100644
--- a/Library/Homebrew/extend/fileutils.rb
+++ b/Library/Homebrew/extend/fileutils.rb
@@ -18,9 +18,9 @@ module FileUtils
     # > When a new file is created, it is given the group of the directory which
     # contains it.
     group_id = if HOMEBREW_BREW_FILE.grpowned?
-      HOMEBREW_BREW_FILE.stat.gid
+      HOMEBREW_BREW_FILE.stat.gid.to_s
     else
-      Process.gid
+      Process.gid.to_s
     end
     begin
       chown(nil, group_id, tmp)
Josephs-MacBook-Pro:local joe$ 
```

**Comment by DomT4** [comment]
I suspect it's a reproduction of this [issue](https://github.com/Homebrew/homebrew/issues/49045).

**Comment by ilovezfs** [comment]
@DomT4 Thanks. I'll see if I can fire up a 10.6 VM and make sure that fixes it.

**Comment by ilovezfs** [comment]
@DomT4 @GregFleming Yup that fixes it
https://gist.github.com/ilovezfs/9e93ab0934174ebdfc7f

```
# OS X 10.8.5
#    def fu_get_gid(group)   #:nodoc:
#      return nil unless group
#      group = group.to_s
#      if /\A\d+\z/ =~ group
#      then group.to_i
#      else Etc.getgrnam(group).gid
#      end
#    end
#    private_module_function :fu_get_gid

# OS X 10.6.7
    def fu_get_gid(group)   #:nodoc:
      return nil unless group
      if /\A\d+\z/ =~ group
      then group.to_i
      else Etc.getgrnam(group).gid
      end
    end
    private_module_function :fu_get_gid
```

So you can upgrade to >=10.6.8, or fix your ruby locally by adding that one line, `group = group.to_s` to /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/fileutils.rb or we can apply this patch to master:

```
Josephs-MacBook-Pro:local joe$ git diff
diff --git a/Library/Homebrew/extend/fileutils.rb b/Library/Homebrew/extend/fileutils.rb
index 9717c69..61c50de 100644
--- a/Library/Homebrew/extend/fileutils.rb
+++ b/Library/Homebrew/extend/fileutils.rb
@@ -22,6 +22,7 @@ module FileUtils
     else
       Process.gid
     end
+    group_id = group_id.to_s #Make OS X 10.6.7 ruby-1.8.7-p174 happy
     begin
       chown(nil, group_id, tmp)
     rescue Errno::EPERM
Josephs-MacBook-Pro:local joe$
```

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew/pull/49369/files
