### ISSUE TITLE
fmdiff needs a PourBottleCheck and a check for FileMerge.app

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew#49637]
brew install -v fmdiff
https://gist.github.com/64febfe041f4a0375aeb
Debug backtrace:
```
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
No such file or directory - /Applications/Xcode.app
/usr/local/Library/Homebrew/keg.rb:485:in `realpath'
/usr/local/Library/Homebrew/keg.rb:485:in `realpath'
/usr/local/Library/Homebrew/keg.rb:485:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/keg.rb:478:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:310:in `link'
/usr/local/Library/Homebrew/formula_installer.rb:625:in `link'
/usr/local/Library/Homebrew/formula_installer.rb:464:in `finish'
/usr/local/Library/Homebrew/cmd/install.rb:216:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
Error: No such file or directory - /Applications/Xcode.app
/usr/local/Library/Homebrew/keg.rb:485:in `realpath'
/usr/local/Library/Homebrew/keg.rb:485:in `realpath'
/usr/local/Library/Homebrew/keg.rb:485:in `block in link_dir'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:43:in `block in find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/find.rb:42:in `find'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:546:in `find'
/usr/local/Library/Homebrew/keg.rb:478:in `link_dir'
/usr/local/Library/Homebrew/keg.rb:310:in `link'
/usr/local/Library/Homebrew/formula_installer.rb:625:in `link'
/usr/local/Library/Homebrew/formula_installer.rb:464:in `finish'
/usr/local/Library/Homebrew/cmd/install.rb:216:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
```

brew install -v --build-from-source fmdiff
https://gist.github.com/e8bb497dbdfa084d262a
Debug backtrace:
```
==> make
{ test -x /Library/Developer/CommandLineTools/../Applications/FileMerge.app/Contents/MacOS/FileMerge && ln -s /Library/Developer/CommandLineTools/../Applications/FileMerge.app/Contents/MacOS/FileMerge filemerge; } || { test -x /Applications/Xcode.app/Contents/Applications/FileMerge.app/Contents/MacOS/FileMerge && ln -s /Applications/Xcode.app/Contents/Applications/FileMerge.app/Contents/MacOS/FileMerge filemerge; } || { test -x /Developer/Applications/Utilities/FileMerge.app/Contents/MacOS/FileMerge && ln -s /Developer/Applications/Utilities/FileMerge.app/Contents/MacOS/FileMerge filemerge; } || false
make: *** [filemerge] Error 1
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
/usr/local/Library/Homebrew/formula.rb:1482:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1419:in `open'
/usr/local/Library/Homebrew/formula.rb:1419:in `system'
/usr/local/Library/Formula/fmdiff.rb:15:in `install'
/usr/local/Library/Homebrew/debrew.rb:22:in `block in install'
/usr/local/Library/Homebrew/debrew.rb:97:in `debrew'
/usr/local/Library/Homebrew/debrew.rb:22:in `install'
/usr/local/Library/Homebrew/build.rb:130:in `block in install'
/usr/local/Library/Homebrew/formula.rb:931:in `block in brew'
/usr/local/Library/Homebrew/formula.rb:1551:in `block in stage'
/usr/local/Library/Homebrew/resource.rb:92:in `block in unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:37:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:171:in `stage'
/usr/local/Library/Homebrew/formula.rb:1541:in `stage'
/usr/local/Library/Homebrew/formula.rb:927:in `brew'
/usr/local/Library/Homebrew/build.rb:108:in `install'
/usr/local/Library/Homebrew/build.rb:177:in `<main>'
```

**Comment by javian** [comment]
I can install fmdiff without problems. After a quick google search I think a requirement is that you have XCode installed - not just the command line tools required for homebrew.

**Comment by ilovezfs** [comment]
yes, as I said, the appropriate checks need to be added to the formula and the bottles.
