### ISSUE TITLE
Octave (--with-gui) failed to build on 10.11

### ISSUE THREAD

**Issue by mstatongk1** [Homebrew/homebrew#49695]
# Please follow the general troubleshooting steps first:

- [ y] Ran `brew update` and retried your prior step?
- [ y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ n/a] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

_You can erase any parts of this template not applicable to your Issue._

### Bug reports:

I cannot install the gui version of octave. Octave will install without gui, although I get a ton of font errors, saying it cannot find any usable font.

Install always hangs on MAKE ALL_DOCS=TARGETS
```
Matts-MacBook-Pro:~ mstatongk1$ brew uninstall octave
Uninstalling /usr/local/Cellar/octave/4.0.0_5... (2,176 files, 47.6M)
Matts-MacBook-Pro:~ mstatongk1$ brew install octave --without-check --with-gui
==> Installing octave from homebrew/science
==> Installing dependencies for homebrew/science/octave: tbb
==> Installing homebrew/science/octave dependency: tbb
==> Downloading https://homebrew.bintray.com/bottles/tbb-4.4-20160128.el_capitan
######################################################################## 100.0%
==> Pouring tbb-4.4-20160128.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/tbb/4.4-20160128: 108 files, 1.9M
==> Installing homebrew/science/octave
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://ftpmirror.gnu.org/octave/octave-4.0.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/octave-4.0.0.tar.gz
==> Downloading http://savannah.gnu.org/support/download.php?file_id=34691
Already downloaded: /Library/Caches/Homebrew/octave--patch-25a9c0b937b50de0acb4dc50e4d6d285ef54f1673e4b84530b53effe983bdd88.php
==> Downloading https://savannah.gnu.org/patch/download.php?file_id=35085
Already downloaded: /Library/Caches/Homebrew/octave--patch-3a7f72f76329e0f40857587e06a1a9074da320423a85a6821b6fbc46bde6140d.php
==> Patching
==> Applying download.php
patching file libinterp/octave-value/ov-classdef.cc
Hunk #1 succeeded at 1937 (offset -9 lines).
patching file libinterp/octave-value/ov-classdef.h
==> Applying download.php
patching file libinterp/dldfcn/__osmesa_print__.cc
==> ./configure --prefix=/usr/local/Cellar/octave/4.0.0_5 --enable-dependency-tr
==> make all DOC_TARGETS=
Error: SIGTERM
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/utils/fork.rb:36:in `read'
/usr/local/Library/Homebrew/utils/fork.rb:36:in `block (3 levels) in safe_fork'
/usr/local/Library/Homebrew/utils.rb:437:in `ignore_interrupts'
/usr/local/Library/Homebrew/utils/fork.rb:26:in `block (2 levels) in safe_fork'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `open'
/usr/local/Library/Homebrew/utils/fork.rb:7:in `block in safe_fork'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tmpdir.rb:88:in `mktmpdir'
/usr/local/Library/Homebrew/utils/fork.rb:6:in `safe_fork'
/usr/local/Library/Homebrew/formula_installer.rb:572:in `build'
/usr/local/Library/Homebrew/formula_installer.rb:231:in `install'
/usr/local/Library/Homebrew/cmd/install.rb:215:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:94:in `install'
/usr/local/Library/brew.rb:83:in `<main>'
Matts-MacBook-Pro:~ mstatongk1$ /usr/local/Library/Homebrew/build.rb:180:in `close': Broken pipe (Errno::EPIPE)
	from /usr/local/Library/Homebrew/build.rb:180:in `rescue in <main>'
	from /usr/local/Library/Homebrew/build.rb:168:in `<main>'
```

Matts-MacBook-Pro:~ mstatongk1$ brew gist-logs octave
https://gist.github.com/666d3748e827593f64e1

https://gist.github.com/anonymous/666d3748e827593f64e1

**Comment by DomT4** [comment]
This issue was moved to Homebrew/homebrew-science#3387

**Comment by DomT4** [comment]
Octave is a Science formulae so they'll be able to assist you further. Moved your Issue to there.
