### ISSUE TITLE
Duplicity python import problem, `novaclient.v1_1` via `pyrax`

### ISSUE THREAD

**Issue by Thinkscape** [Homebrew/homebrew#49754]
Supposedly fixed via PR #47410 (thanks @tdsmith !), but it resurfaced.

Running latest version, still getting 
> BackendException: This backend requires the pyrax library available from Rackspace.

Stack:
````
Backend error detail: Traceback (most recent call last):
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1532, in <module>
    with_tempdir(main)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1526, in with_tempdir
    fn()
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/bin/duplicity", line 1364, in main
    action = commandline.ProcessCommandLine(sys.argv[1:])
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/commandline.py", line 1116, in ProcessCommandLine
    backup, local_pathname = set_backend(args[0], args[1])
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/commandline.py", line 1005, in set_backend
    globals.backend = backend.get_backend(bend)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/backend.py", line 223, in get_backend
    obj = get_backend_object(url_string)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/backend.py", line 209, in get_backend_object
    return factory(pu)
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages/duplicity/backends/hubicbackend.py", line 40, in __init__
    raise BackendException("This backend requires the pyrax "
BackendException: This backend requires the pyrax library available from Rackspace.
````
I've removed previous versions, run `brew clean` and `brew doctor`. 
There's no local pyrax install (tested with `pip list | grep pyrax`).

How can I help nail this down ?

**Comment by Thinkscape** [comment]
Ok, it's something else than the original issue...

```
# PYTHONPATH="/usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages:/usr/local/Cellar/duplicity/0.7.06_1/libexec/lib/python2.7/site-packages" /usr/bin/python -c "import pyrax"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/duplicity/0.7.06_1/libexec/vendor/lib/python2.7/site-packages/pyrax/__init__.py", line 64, in <module>
    from novaclient.v1_1 import client as _cs_client
ImportError: No module named v1_1
````

**Comment by tdsmith** [comment]
Does this work after #49710?

**Comment by Thinkscape** [comment]
@tdsmith all the deps works fine now, thank you!

**However** duplicity now crashes without any message :-1: It worked fine from brew in `0.7.04` version after I manually fixed all the deps and imports, but now it seems to crash without removing lockfile:
![image](https://cloud.githubusercontent.com/assets/270528/13523646/04b16c86-e1f7-11e5-9904-64841d1981c0.png)

I found this upstream: https://answers.launchpad.net/duplicity/+question/284756

## Consider duplicity unstable on OSX in version 0.7.06 !!!
