### ISSUE TITLE
brew ...  can`t run

### ISSUE THREAD

**Issue by yuanzhenjie** [Homebrew/homebrew#49825]
localhost:Cellar xxxx$   brew 

then show the follow info :

```
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mach (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
```

**Comment by bfontaine** [comment]
Please run `cd /usr/local && git fetch && git reset --hard origin/master` then try again.

**Comment by Soleone** [comment]
yep that fixed it for me, thanks!

`sudo git reset --hard origin/master`

**Comment by yuanzhenjie** [comment]
thank you for your reply.
I uninstall home-brew . after backup folder "Cellar".
then reinstall home-brew, restore  folder "Cellar", brew update ,brew upgrade.

the issue isn`t  exist now.

**Comment by dongchuant** [comment]
@bfontaine I fixed it. Thanks. It's not necessary  to uninstall homebrew:)
