### ISSUE TITLE
brew update in OS X El Capitan

### ISSUE THREAD

**Issue by amarsh1** [Homebrew/homebrew#50538]
- [ ] Ran `brew update` and retried your prior step?
**Tried several times**

- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
**Tried**.

- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
**Tried**

Acting on request from brew to report issue see Gist Error: undefined method `new' for Patch:Module
```
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Homebrew/patch.rb:115:in `initialize'
/usr/local/Library/Homebrew/patch.rb:18:in `new'
/usr/local/Library/Homebrew/patch.rb:18:in `create'
/usr/local/Library/Homebrew/software_spec.rb:168:in `patch'
/usr/local/Library/Homebrew/formula.rb:1919:in `block in patch'
/usr/local/Library/Homebrew/formula.rb:1919:in `each'
/usr/local/Library/Homebrew/formula.rb:1919:in `patch'
/usr/local/Library/Formula/a2ps.rb:19:in `<class:A2ps>'
/usr/local/Library/Formula/a2ps.rb:1:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:21:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:21:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:34:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:83:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:74:in `klass'
/usr/local/Library/Homebrew/formulary.rb:70:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/cmd/update.rb:204:in `block in report'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `each_line'
/usr/local/Library/Homebrew/cmd/update.rb:190:in `report'
/usr/local/Library/Homebrew/cmd/update.rb:24:in `update'
/usr/local/Library/brew.rb:125:in `<main>'
```

**Comment by ilovezfs** [comment]
Can we see output of `brew config` and `git -C /usr/local status`?

You probably just need to
```
cd /usr/local
git reset --hard origin/master
brew update
brew update
```

**Comment by amarsh1** [comment]
Sorted thanks very much.

Yes I did

sudo chown -R $(whoami):admin /usr/local

cd /usr/local && git fetch && git reset --hard origin/master

and brew update, brew doctor a few times.

Sorry for bothering you.

**Comment by ilovezfs** [comment]
Great, glad you got it working again :)
